CREATE TABLE MASTER_BRAND_FUNNEL (
  taigek_word VARCHAR(50),
  tiger_th VARCHAR(50),
  tiger_en VARCHAR(50),
  sku_brand_standard VARCHAR(50),
  funnel_level VARCHAR(10),
  PRIMARY KEY (taigek_word, sku_brand_standard)
);

INSERT INTO MASTER_BRAND_FUNNEL VALUES
('เวส', 'เวส', 'VESS', 'VESS', 'BOTTOM'),
('เวสเขียว', 'เวส', 'VESS', 'VESS', 'MIDDLE'),
('วส', 'เวส', 'VESS', 'VESS', 'TOP'),
('โกลด์เมาท์', 'โกลด์เมาท์', 'GOLD MOUNT', 'GOLD MOUNT', 'BOTTOM'),
('โกล', 'โกลด์เมาท์', 'GOLD MOUNT', 'GOLD MOUNT', 'MIDDLE'),
('โกลเม้า', 'โกลด์เมาท์', 'GOLD MOUNT', 'GOLD MOUNT', 'MIDDLE'),
('โกเม้า', 'โกลด์เมาท์', 'GOLD MOUNT', 'GOLD MOUNT', 'MIDDLE'),
('มิลาโน่', 'มิลาโน่', 'MILANO', 'MILANO', 'BOTTOM'),
('มิลา', 'มิลาโน่', 'MILANO', 'MILANO', 'MIDDLE'),
('มิ', 'มิลาโน่', 'MILANO', 'MILANO', 'TOP'),
('มิลาโน', 'มิลาโน่', 'MILANO', 'MILANO', 'MIDDLE'),
('มินาโน่', 'มิลาโน่', 'MILANO', 'MILANO', 'MIDDLE'),
('ม่อน', 'ม่อน', 'MOND', 'MOND', 'BOTTOM'),
('มอน', 'ม่อน', 'MOND', 'MOND', 'MIDDLE'),
('ม่อนเขียว', 'ม่อน', 'MOND', 'MOND', 'MIDDLE'),
('แพลตตินั่ม', 'แพลตตินั่ม', 'PLATINUM', 'PLATINUM', 'BOTTOM'),
('แพลต', 'แพลตตินั่ม', 'PLATINUM', 'PLATINUM', 'MIDDLE'),
('แพตตินั่ม', 'แพลตตินั่ม', 'PLATINUM', 'PLATINUM', 'MIDDLE'),
('แพลตตินัม', 'แพลตตินั่ม', 'PLATINUM', 'PLATINUM', 'MIDDLE'),
('ซีวอส', 'ซีวอส', 'SEVIOS', 'SEVIOS', 'BOTTOM'),
('เซวียส', 'ซีวอส', 'SEVIOS', 'SEVIOS', 'MIDDLE'),
('ซีวอสเขียว', 'ซีวอส', 'SEVIOS', 'SEVIOS', 'MIDDLE'),
('เอสเอ็มเอส', 'เอสเอ็มเอส', 'SMS', 'SMS', 'BOTTOM'),
('เอส', 'เอสเอ็มเอส', 'SMS', 'SMS', 'MIDDLE'),
('SMS', 'เอสเอ็มเอส', 'SMS', 'SMS', 'MIDDLE'),
('เอสเอมเอส', 'เอสเอ็มเอส', 'SMS', 'SMS', 'MIDDLE'),
('เท็กซัส', 'เท็กซัส', 'TEXAS', 'TEXAS', 'BOTTOM'),
('เท็ก', 'เท็กซัส', 'TEXAS', 'TEXAS', 'MIDDLE'),
('เทกซัส', 'เท็กซัส', 'TEXAS', 'TEXAS', 'MIDDLE'),
('เท็กซัสเขียว', 'เท็กซัส', 'TEXAS', 'TEXAS', 'MIDDLE'),
('ว็อกซ์', 'ว็อกซ์', 'VOXX', 'VOXX', 'BOTTOM'),
('ว็อก', 'ว็อกซ์', 'VOXX', 'VOXX', 'MIDDLE'),
('วอค', 'ว็อกซ์', 'VOXX', 'VOXX', 'MIDDLE'),
('VOXX', 'ว็อกซ์', 'VOXX', 'VOXX', 'MIDDLE'),
('เซียร์ร่า', 'เซียร์ร่า', 'SIERRA', 'SIERRA', 'BOTTOM'),
('เซียร่า', 'เซียร์ร่า', 'SIERRA', 'SIERRA', 'MIDDLE'),
('เซีย', 'เซียร์ร่า', 'SIERRA', 'SIERRA', 'MIDDLE'),
('โอเอส', 'โอเอส', 'OS', 'OS', 'BOTTOM'),
('โอ', 'โอเอส', 'OS', 'OS', 'TOP'),
('โอเอส บูล', 'โอเอส', 'OS', 'OS', 'MIDDLE'),
('OS', 'โอเอส', 'OS', 'OS', 'TOP'),
('วอลตัน', 'วอลตัน', 'WALTON', 'WALTON', 'BOTTOM'),
('วอล', 'วอลตัน', 'WALTON', 'WALTON', 'MIDDLE'),
('วอลตันแดง', 'วอลตัน', 'WALTON', 'WALTON', 'MIDDLE'),
('วอลตันเขียว', 'วอลตัน', 'WALTON', 'WALTON', 'MIDDLE'),
('จอห์น', 'จอห์น', 'JOHN', 'JOHN', 'BOTTOM'),
('จอน', 'จอห์น', 'JOHN', 'JOHN', 'MIDDLE'),
('JHON', 'จอห์น', 'JOHN', 'JOHN', 'MIDDLE'),
('จอห์นแดง', 'จอห์น', 'JOHN', 'JOHN', 'MIDDLE'),
('บารูซัน', 'บารูซัน', 'BAROESAN', 'BAROESAN', 'BOTTOM'),
('บารู', 'บารูซัน', 'BAROESAN', 'BAROESAN', 'MIDDLE'),
('บาซัน', 'บารูซัน', 'BAROESAN', 'BAROESAN', 'MIDDLE'),
('คาวาโร่', 'คาวาโร่', 'CAVALLO', 'CAVALLO', 'BOTTOM'),
('คา', 'คาวาโร่', 'CAVALLO', 'CAVALLO', 'TOP'),
('คาวา', 'คาวาโร่', 'CAVALLO', 'CAVALLO', 'MIDDLE'),
('คาวาโล่', 'คาวาโร่', 'CAVALLO', 'CAVALLO', 'MIDDLE'),
('คาวาโร', 'คาวาโร่', 'CAVALLO', 'CAVALLO', 'MIDDLE'),
('รอยัล', 'รอยัล', 'ROYAL', 'ROYAL', 'BOTTOM'),
('รอย', 'รอยัล', 'ROYAL', 'ROYAL', 'MIDDLE'),
('รอยัลเขียว', 'รอยัล', 'ROYAL', 'ROYAL', 'MIDDLE'),
('235', '235', '235', '235', 'BOTTOM'),
('235เขียว', '235', '235', '235', 'MIDDLE'),
('235แดง', '235', '235', '235', 'MIDDLE'),
('แคนยอน', 'แคนยอน', 'CANYON', 'CANYON', 'BOTTOM'),
('แคน', 'แคนยอน', 'CANYON', 'CANYON', 'MIDDLE'),
('แคนย่อน', 'แคนยอน', 'CANYON', 'CANYON', 'MIDDLE'),
('แอลแอนด์เอ็ม', 'แอลแอนด์เอ็ม', 'L&M', 'L&M', 'BOTTOM'),
('แอล', 'แอลแอนด์เอ็ม', 'L&M', 'L&M', 'MIDDLE'),
('L&M', 'แอลแอนด์เอ็ม', 'L&M', 'L&M', 'MIDDLE'),
('แอลแอนด์เอม', 'แอลแอนด์เอ็ม', 'L&M', 'L&M', 'MIDDLE'),
('มาโบโร่', 'มาโบโร่', 'MARLBORO', 'MARLBORO', 'BOTTOM'),
('มาโบ', 'มาโบโร่', 'MARLBORO', 'MARLBORO', 'MIDDLE'),
('มาโบโร', 'มาโบโร่', 'MARLBORO', 'MARLBORO', 'MIDDLE'),
('มาโบโร่แดง', 'มาโบโร่', 'MARLBORO', 'MARLBORO', 'MIDDLE'),
('แคปิตอล', 'แคปิตอล', 'CAPITAL', 'CAPITAL', 'BOTTOM'),
('แคป', 'แคปิตอล', 'CAPITAL', 'CAPITAL', 'MIDDLE'),
('แคปิตอลฟ้า', 'แคปิตอล', 'CAPITAL', 'CAPITAL', 'MIDDLE'),
('โอริส', 'โอริส', 'ORIS', 'ORIS', 'BOTTOM'),
('โอริ', 'โอริส', 'ORIS', 'ORIS', 'MIDDLE'),
('ORIS', 'โอริส', 'ORIS', 'ORIS', 'MIDDLE'),
('จีเอ็ม', 'จีเอ็ม', 'GM', 'GM', 'BOTTOM'),
('GM', 'จีเอ็ม', 'GM', 'GM', 'TOP'),
('จีเอม', 'จีเอ็ม', 'GM', 'GM', 'MIDDLE'),
('กรองทิพย์', 'กรองทิพย์', 'KRONG THIP', 'KRONG THIP', 'BOTTOM'),
('กรอง', 'กรองทิพย์', 'KRONG THIP', 'KRONG THIP', 'MIDDLE'),
('กรองทิพ', 'กรองทิพย์', 'KRONG THIP', 'KRONG THIP', 'MIDDLE'),
('สุข', 'สุข', 'SUK', 'SUK', 'BOTTOM'),
('สุขดั้งเดิม', 'สุข', 'SUK', 'SUK', 'MIDDLE'),
('บลูไอซ์', 'บลูไอซ์', 'BLUE ICE', 'BLUE ICE', 'BOTTOM'),
('บลู', 'บลูไอซ์', 'BLUE ICE', 'BLUE ICE', 'MIDDLE'),
('บลูไอ', 'บลูไอซ์', 'BLUE ICE', 'BLUE ICE', 'MIDDLE'),
('ดีแอนด์เจ', 'ดีแอนด์เจ', 'D&J', 'D&J', 'BOTTOM'),
('ดีแอนด์', 'ดีแอนด์เจ', 'D&J', 'D&J', 'MIDDLE'),
('D&J', 'ดีแอนด์เจ', 'D&J', 'D&J', 'MIDDLE');