-- ============================================================================
-- BLACKBOX ALERT CENTER · MAIN ALERT SQL
-- ============================================================================
-- BB STORE / Supabase PostgreSQL
-- ไฟล์เดียวจบ: ตาราง + ห้อง 4 ห้อง + ป้ายเตือน + หลักฐาน + รอยมือ + View
--
-- หลักการ:
--   1) ไม่ลบ bb_orders และไม่เขียนทับหลักฐานต้นทาง
--   2) ทุกป้ายเตือนมีปลายทางว่าต้องไปห้องไหน
--   3) ทุกการตัดสินใจกลายเป็นรอยมือย้อนกลับได้
--   4) ใช้ room_key เป็นตัวเลือกห้อง (dropdown) ในหน้าเว็บได้ทันที
--
-- ห้องที่ล็อกไว้ 4 ห้อง:
--   BLACKBOX_ALERT_CENTER = ศูนย์ป้ายเตือนกลาง (ห้องหลักของไฟล์นี้)
--   ORDER_CONTROL          = ห้องออเดอร์หลัก
--   BLACKBOX_ROOM          = ห้องแกะรอยออเดอร์
--   TELEGRAM_ROOM          = ห้องคุมการส่ง
--
-- หมายเหตุเรื่อง DROP:
--   DROP VIEW เป็นการรีบิลด์ View เท่านั้น ไม่แตะข้อมูลตารางจริง
--   ห้ามใส่ DROP TABLE ในไฟล์นี้ เพราะป้ายเตือนและรอยมือต้องอยู่รอด
-- ============================================================================

BEGIN;

-- --------------------------------------------------------------------------
-- 0) DROP เฉพาะ View เพื่อให้รันไฟล์ซ้ำได้
-- --------------------------------------------------------------------------
DROP VIEW IF EXISTS public.vw_blackbox_hot_feed;
DROP VIEW IF EXISTS public.vw_blackbox_room_dropdown;
DROP VIEW IF EXISTS public.vw_blackbox_alert_center;

-- --------------------------------------------------------------------------
-- 1) ROOM CATALOG · รายชื่อห้องกลางของระบบ
-- --------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.blackbox_rooms (
  room_key text PRIMARY KEY,
  room_name text NOT NULL,
  room_name_th text NOT NULL,
  room_role text NOT NULL,
  room_color text NOT NULL DEFAULT 'violet',
  room_icon text NOT NULL DEFAULT '◈',
  is_destination boolean NOT NULL DEFAULT true,
  sort_order integer NOT NULL DEFAULT 100,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT blackbox_rooms_key_ck CHECK (
    room_key IN (
      'BLACKBOX_ALERT_CENTER',
      'ORDER_CONTROL',
      'BLACKBOX_ROOM',
      'TELEGRAM_ROOM'
    )
  )
);

INSERT INTO public.blackbox_rooms
  (room_key, room_name, room_name_th, room_role, room_color, room_icon, is_destination, sort_order)
VALUES
  ('BLACKBOX_ALERT_CENTER', 'BLACKBOX ALERT CENTER', 'ศูนย์ป้ายเตือน', 'รับสัญญาณและชี้ปลายทาง', 'pink', '◉', false, 10),
  ('ORDER_CONTROL', 'ORDER CONTROL', 'ห้องออเดอร์หลัก', 'แก้ไขและจัดการข้อมูลออเดอร์', 'violet', '▣', true, 20),
  ('BLACKBOX_ROOM', 'BLACKBOX ROOM', 'ห้องแกะรอยออเดอร์', 'สืบสาเหตุซ้ำ เปลี่ยนของ และรอยหลักฐาน', 'fuchsia', '◈', true, 30),
  ('TELEGRAM_ROOM', 'TELEGRAM ROOM', 'ห้องคุมการส่ง', 'คิวส่ง สถานะส่ง และประวัติการส่ง', 'cyan', '➤', true, 40)
ON CONFLICT (room_key) DO UPDATE SET
  room_name = EXCLUDED.room_name,
  room_name_th = EXCLUDED.room_name_th,
  room_role = EXCLUDED.room_role,
  room_color = EXCLUDED.room_color,
  room_icon = EXCLUDED.room_icon,
  is_destination = EXCLUDED.is_destination,
  sort_order = EXCLUDED.sort_order,
  updated_at = now();

-- --------------------------------------------------------------------------
-- 2) ALERT EVENTS · ตารางป้ายเตือนหลัก
-- --------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.blackbox_alert_events (
  alert_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  source_event_id text,
  source_system text NOT NULL DEFAULT 'n8n',
  source_payload jsonb NOT NULL DEFAULT '{}'::jsonb,

  -- ป้ายเตือน
  alert_type text NOT NULL DEFAULT 'WATCH',
  severity text NOT NULL DEFAULT 'INFO',
  headline text NOT NULL,
  reason text,
  required_action text,
  status text NOT NULL DEFAULT 'NEW',

  -- ตัวตนออเดอร์/เพจ/ลูกค้า
  order_id text,
  upsert_key text,
  order_number text,
  page_name text,
  customer_name text,
  phone text,
  thread_id text,

  -- เวลาและเงิน
  occurred_at timestamptz,
  detected_at timestamptz NOT NULL DEFAULT now(),
  order_date text,
  cod_before numeric(12,2),
  cod_after numeric(12,2),

  -- สินค้าก่อนและหลังการเปลี่ยน
  product_before text,
  product_after text,
  quantity_before integer,
  quantity_after integer,
  change_decision_minutes integer,

  -- เหตุผลเฉพาะของระบบ
  duplicate_group_id text,
  duplicate_reason text,
  evidence_summary text,

  -- ทางส่งต่อ
  destination_room text NOT NULL DEFAULT 'BLACKBOX_ALERT_CENTER',
  destination_url text,
  assigned_to text,
  closed_at timestamptz,
  closed_by text,
  close_reason text,

  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),

  CONSTRAINT blackbox_alert_type_ck CHECK (alert_type IN (
    'DUPLICATE_FROM_FOUR',
    'QUESTION_NOT_ORDER',
    'CUSTOMER_CHANGED_PRODUCT',
    'MIDDLE_BUCKET_RISK',
    'INCOMPLETE_DATA',
    'PRODUCT_MISMATCH',
    'COD_MISMATCH',
    'DELIVERY_FAILED',
    'DELIVERY_SENT',
    'SYSTEM_SILENT',
    'WATCH'
  )),
  CONSTRAINT blackbox_severity_ck CHECK (severity IN ('CRITICAL', 'REVIEW', 'INCOMPLETE', 'INFO')),
  CONSTRAINT blackbox_alert_status_ck CHECK (status IN ('NEW', 'ACKNOWLEDGED', 'IN_REVIEW', 'ROUTED', 'RESOLVED', 'DISMISSED')),
  CONSTRAINT blackbox_destination_room_ck CHECK (destination_room IN (
    'BLACKBOX_ALERT_CENTER', 'ORDER_CONTROL', 'BLACKBOX_ROOM', 'TELEGRAM_ROOM'
  ))
);

-- --------------------------------------------------------------------------
-- 3) EVIDENCE · หลักฐานหลายชิ้นต่อหนึ่งป้าย
-- --------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.blackbox_alert_evidence (
  evidence_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  alert_id bigint NOT NULL REFERENCES public.blackbox_alert_events(alert_id) ON DELETE RESTRICT,
  evidence_type text NOT NULL DEFAULT 'NOTE',
  evidence_label text NOT NULL,
  evidence_text text,
  source_system text,
  source_event_id text,
  evidence_payload jsonb NOT NULL DEFAULT '{}'::jsonb,
  occurred_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT blackbox_evidence_type_ck CHECK (evidence_type IN (
    'RAW_PAYLOAD', 'CHAT', 'ORDER', 'SYSTEM_RETRY', 'LOCATION', 'NOTE', 'SCREENSHOT'
  ))
);

-- --------------------------------------------------------------------------
-- 4) DECISIONS · รอยมือการตัดสินใจของคน/ระบบ
-- --------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.blackbox_alert_decisions (
  decision_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  alert_id bigint NOT NULL REFERENCES public.blackbox_alert_events(alert_id) ON DELETE RESTRICT,
  actor_type text NOT NULL DEFAULT 'HUMAN',
  actor_name text,
  decision_code text NOT NULL,
  decision_note text,
  from_status text,
  to_status text NOT NULL,
  destination_room text,
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT blackbox_actor_type_ck CHECK (actor_type IN ('HUMAN', 'BOT', 'SYSTEM')),
  CONSTRAINT blackbox_decision_code_ck CHECK (decision_code IN (
    'ACKNOWLEDGE', 'HOLD_BEFORE_SEND', 'ROUTE_TO_ORDER_CONTROL',
    'ROUTE_TO_BLACKBOX_ROOM', 'ROUTE_TO_TELEGRAM_ROOM', 'MERGE_CASE',
    'SPLIT_CASE', 'ASK_CUSTOMER', 'MARK_NOT_DUPLICATE', 'RESOLVE', 'DISMISS'
  ))
);

-- --------------------------------------------------------------------------
-- 5) INDEXES · ให้ศูนย์ป้ายเตือนค้นเร็ว
-- --------------------------------------------------------------------------
CREATE INDEX IF NOT EXISTS idx_blackbox_alert_live
  ON public.blackbox_alert_events (severity, status, detected_at DESC);
CREATE INDEX IF NOT EXISTS idx_blackbox_alert_order
  ON public.blackbox_alert_events (upsert_key, order_number);
CREATE INDEX IF NOT EXISTS idx_blackbox_alert_destination
  ON public.blackbox_alert_events (destination_room, status, detected_at DESC);
CREATE INDEX IF NOT EXISTS idx_blackbox_alert_duplicate
  ON public.blackbox_alert_events (duplicate_group_id)
  WHERE duplicate_group_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_blackbox_evidence_alert
  ON public.blackbox_alert_evidence (alert_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_blackbox_decisions_alert
  ON public.blackbox_alert_decisions (alert_id, created_at DESC);

-- --------------------------------------------------------------------------
-- 6) UPDATED_AT · แตะเวลาแก้ไขอัตโนมัติ
-- --------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.blackbox_touch_updated_at()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  NEW.updated_at := now();
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_blackbox_rooms_updated_at ON public.blackbox_rooms;
CREATE TRIGGER trg_blackbox_rooms_updated_at
BEFORE UPDATE ON public.blackbox_rooms
FOR EACH ROW EXECUTE FUNCTION public.blackbox_touch_updated_at();

DROP TRIGGER IF EXISTS trg_blackbox_alert_events_updated_at ON public.blackbox_alert_events;
CREATE TRIGGER trg_blackbox_alert_events_updated_at
BEFORE UPDATE ON public.blackbox_alert_events
FOR EACH ROW EXECUTE FUNCTION public.blackbox_touch_updated_at();

-- --------------------------------------------------------------------------
-- 7) VIEW: ห้องสำหรับ dropdown · ใช้กับตัวเลือกห้องในหน้าเว็บ
-- --------------------------------------------------------------------------
CREATE VIEW public.vw_blackbox_room_dropdown AS
SELECT
  room_key,
  room_name,
  room_name_th,
  room_role,
  room_color,
  room_icon,
  sort_order
FROM public.blackbox_rooms
WHERE is_active = true
ORDER BY sort_order;

-- --------------------------------------------------------------------------
-- 8) VIEW: BLACKBOX ALERT CENTER · ตารางหลักหน้าเว็บ
-- --------------------------------------------------------------------------
CREATE VIEW public.vw_blackbox_alert_center AS
SELECT
  a.alert_id,
  a.source_event_id,
  a.source_system,
  a.alert_type,
  a.severity,
  a.headline,
  a.reason,
  a.required_action,
  a.status,
  a.order_id,
  a.upsert_key,
  a.order_number,
  a.page_name,
  a.customer_name,
  a.phone,
  a.thread_id,
  a.occurred_at,
  a.detected_at,
  a.order_date,
  a.cod_before,
  a.cod_after,
  a.product_before,
  a.product_after,
  a.quantity_before,
  a.quantity_after,
  a.change_decision_minutes,
  a.duplicate_group_id,
  a.duplicate_reason,
  a.evidence_summary,
  a.destination_room,
  r.room_name AS destination_room_name,
  r.room_name_th AS destination_room_th,
  r.room_color AS destination_room_color,
  r.room_icon AS destination_room_icon,
  a.destination_url,
  a.assigned_to,
  a.closed_at,
  a.closed_by,
  a.close_reason,
  a.created_at,
  a.updated_at,
  CASE a.severity
    WHEN 'CRITICAL' THEN 'กั้นก่อนส่ง'
    WHEN 'REVIEW' THEN 'รอตัดสินใจ'
    WHEN 'INCOMPLETE' THEN 'ข้อมูลพร่อง'
    ELSE 'แจ้งสถานะ'
  END AS severity_th,
  CASE a.alert_type
    WHEN 'DUPLICATE_FROM_FOUR' THEN 'ซ้ำจากโฟร์'
    WHEN 'QUESTION_NOT_ORDER' THEN 'ถามไม่ใช่สั่ง'
    WHEN 'CUSTOMER_CHANGED_PRODUCT' THEN 'ลูกค้าเปลี่ยนของ'
    WHEN 'MIDDLE_BUCKET_RISK' THEN 'ก้อนกลางมีรอย'
    WHEN 'INCOMPLETE_DATA' THEN 'เบอร์พร่อง / ข้อมูลไม่ครบ'
    WHEN 'PRODUCT_MISMATCH' THEN 'สินค้าไม่ตรง'
    WHEN 'COD_MISMATCH' THEN 'ยอดกำลังซ้อน'
    WHEN 'DELIVERY_FAILED' THEN 'ส่งไม่ออก'
    WHEN 'DELIVERY_SENT' THEN 'ส่งแล้ว'
    WHEN 'SYSTEM_SILENT' THEN 'ระบบเงียบผิดปกติ'
    ELSE 'เฝ้าดู'
  END AS alert_type_th,
  CASE WHEN a.product_before IS NOT NULL OR a.product_after IS NOT NULL THEN
    concat_ws(' → ', COALESCE(a.product_before, 'รอบแรกไม่ระบุ'), COALESCE(a.product_after, 'รายการล่าสุดไม่ระบุ'))
  END AS change_route_text,
  CASE WHEN a.cod_before IS NOT NULL OR a.cod_after IS NOT NULL THEN
    concat_ws(' → ', COALESCE(a.cod_before::text, '—'), COALESCE(a.cod_after::text, '—'))
  END AS cod_route_text,
  COALESCE(ev.evidence_count, 0)::integer AS evidence_count,
  COALESCE(dec.decision_count, 0)::integer AS decision_count,
  dec.last_decision_code,
  dec.last_decision_at
FROM public.blackbox_alert_events a
LEFT JOIN public.blackbox_rooms r
  ON r.room_key = a.destination_room
LEFT JOIN LATERAL (
  SELECT count(*)::integer AS evidence_count
  FROM public.blackbox_alert_evidence e
  WHERE e.alert_id = a.alert_id
) ev ON true
LEFT JOIN LATERAL (
  SELECT
    count(*)::integer AS decision_count,
    (array_agg(d.decision_code ORDER BY d.created_at DESC))[1] AS last_decision_code,
    max(d.created_at) AS last_decision_at
  FROM public.blackbox_alert_decisions d
  WHERE d.alert_id = a.alert_id
) dec ON true;

-- --------------------------------------------------------------------------
-- 9) VIEW: HOT FEED · ฝั่งนาฟิกา/ป้ายไฟ
-- --------------------------------------------------------------------------
CREATE VIEW public.vw_blackbox_hot_feed AS
SELECT
  alert_id,
  severity,
  severity_th,
  alert_type,
  alert_type_th,
  headline,
  page_name,
  order_number,
  destination_room,
  destination_room_name,
  detected_at,
  status,
  evidence_count,
  CASE severity WHEN 'CRITICAL' THEN 1 WHEN 'REVIEW' THEN 2 WHEN 'INCOMPLETE' THEN 3 ELSE 4 END AS heat_rank
FROM public.vw_blackbox_alert_center
WHERE status IN ('NEW', 'ACKNOWLEDGED', 'IN_REVIEW', 'ROUTED')
ORDER BY heat_rank, detected_at DESC;

-- --------------------------------------------------------------------------
-- 10) COMMENTS · เปิดอ่านใน SQL catalog ก็รู้ว่าใช้ทำอะไร
-- --------------------------------------------------------------------------
COMMENT ON TABLE public.blackbox_rooms IS
  'BLACKBOX ROOM CATALOG: รายชื่อ 4 ห้องและปลายทางของป้ายเตือน';
COMMENT ON TABLE public.blackbox_alert_events IS
  'BLACKBOX ALERT CENTER: ป้ายเตือนทุกใบ ห้ามลบหลักฐานต้นทาง';
COMMENT ON TABLE public.blackbox_alert_evidence IS
  'BLACKBOX ALERT EVIDENCE: หลักฐานประกอบป้ายเตือน';
COMMENT ON TABLE public.blackbox_alert_decisions IS
  'BLACKBOX ALERT DECISIONS: รอยมือคน/บอท/ระบบในการตัดสินใจ';
COMMENT ON VIEW public.vw_blackbox_alert_center IS
  'BLACKBOX ALERT CENTER main board: one row per alert with destination room and change route';
COMMENT ON VIEW public.vw_blackbox_room_dropdown IS
  'Dropdown source for the four BLACKBOX rooms';
COMMENT ON VIEW public.vw_blackbox_hot_feed IS
  'Hot feed for the right-side signal console';

COMMIT;

-- ============================================================================
-- ตัวอย่างใช้งาน
-- ============================================================================
-- ดูห้องสำหรับ dropdown:
-- SELECT * FROM public.vw_blackbox_room_dropdown;
--
-- ดูป้ายที่ต้องจัดการ:
-- SELECT * FROM public.vw_blackbox_alert_center
-- WHERE status IN ('NEW','ACKNOWLEDGED','IN_REVIEW','ROUTED')
-- ORDER BY CASE severity WHEN 'CRITICAL' THEN 1 WHEN 'REVIEW' THEN 2 ELSE 3 END,
--          detected_at DESC;
--
-- สร้างป้าย “ลูกค้าเปลี่ยนของ”:
-- INSERT INTO public.blackbox_alert_events (
--   source_system, alert_type, severity, headline, reason, required_action,
--   status, order_number, page_name, customer_name, product_before, product_after,
--   cod_before, cod_after, change_decision_minutes, destination_room
-- ) VALUES (
--   'n8n', 'CUSTOMER_CHANGED_PRODUCT', 'REVIEW',
--   'ลูกค้าเปลี่ยนของ · รอบแรก → รอบล่าสุด',
--   'พบการเปลี่ยนสินค้าในบทสนทนาเดิม ไม่ใช่ออเดอร์ใหม่โดยอัตโนมัติ',
--   'เปิดเส้นทางและเทียบแชท', 'NEW', 'ORD-EXAMPLE', 'BB STORE', 'ลูกค้าทดลอง',
--   'สินค้า A x2', 'สินค้า B x1 + สินค้า C x1',
--   390, 450, 16, 'BLACKBOX_ROOM'
-- );
--
-- ปิดป้ายโดยไม่ลบ:
-- UPDATE public.blackbox_alert_events
-- SET status = 'RESOLVED', closed_at = now(), closed_by = 'operator',
--     close_reason = 'ยืนยันว่าเป็นการเปลี่ยนสินค้า'
-- WHERE alert_id = 1;
--
-- บันทึกรอยมือพร้อมการปิดป้าย:
-- INSERT INTO public.blackbox_alert_decisions (
--   alert_id, actor_type, actor_name, decision_code, decision_note,
--   from_status, to_status, destination_room
-- ) VALUES (
--   1, 'HUMAN', 'operator', 'RESOLVE', 'ลูกค้ายืนยันรายการล่าสุด',
--   'IN_REVIEW', 'RESOLVED', 'BLACKBOX_ROOM'
-- );
