-- FIX ST TELEGRAM HISTORY ROOM
-- รันใน Supabase ของ ST เท่านั้น
-- สำหรับกรณี st_orders_sent_history มีอยู่แล้ว แต่คอลัมน์ห้องเว็บยังไม่ครบ

CREATE TABLE IF NOT EXISTS public.st_orders_sent_history (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_key text,
  order_number text,
  sent_at timestamptz NOT NULL DEFAULT now(),
  recalled_at timestamptz,
  recall_count integer NOT NULL DEFAULT 0,
  delivery_status text NOT NULL DEFAULT 'SENT',
  snapshot jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.st_orders_sent_history
  ADD COLUMN IF NOT EXISTS order_key text,
  ADD COLUMN IF NOT EXISTS order_number text,
  ADD COLUMN IF NOT EXISTS sent_at timestamptz DEFAULT now(),
  ADD COLUMN IF NOT EXISTS recalled_at timestamptz,
  ADD COLUMN IF NOT EXISTS recall_count integer DEFAULT 0,
  ADD COLUMN IF NOT EXISTS delivery_status text DEFAULT 'SENT',
  ADD COLUMN IF NOT EXISTS snapshot jsonb DEFAULT '{}'::jsonb,
  ADD COLUMN IF NOT EXISTS telegram_chat_id text,
  ADD COLUMN IF NOT EXISTS telegram_message_id text,
  ADD COLUMN IF NOT EXISTS telegram_message_text text,
  ADD COLUMN IF NOT EXISTS telegram_room text DEFAULT 'ST_SENT_HISTORY',
  ADD COLUMN IF NOT EXISTS queue_status text DEFAULT 'SENT',
  ADD COLUMN IF NOT EXISTS order_day_color_emoji text,
  ADD COLUMN IF NOT EXISTS time_slot_label text,
  ADD COLUMN IF NOT EXISTS ghost_column text,
  ADD COLUMN IF NOT EXISTS status_color text,
  ADD COLUMN IF NOT EXISTS routing_tag text,
  ADD COLUMN IF NOT EXISTS created_at timestamptz DEFAULT now();

CREATE INDEX IF NOT EXISTS idx_st_sent_history_key
  ON public.st_orders_sent_history (order_key, sent_at DESC);

CREATE OR REPLACE VIEW public.vw_st_telegram_web_history AS
SELECT
  h.id AS history_id,
  h.order_key AS upsert_key,
  h.order_number,
  h.sent_at,
  h.recalled_at,
  h.recall_count,
  h.delivery_status,
  h.telegram_chat_id,
  h.telegram_message_id,
  h.telegram_message_text,
  h.telegram_room,
  h.queue_status,
  h.order_day_color_emoji,
  h.time_slot_label,
  h.ghost_column,
  h.status_color,
  h.routing_tag,
  h.snapshot,
  h.created_at
FROM public.st_orders_sent_history h;

SELECT 'ST_SENT_HISTORY' AS room, COUNT(*) AS rows
FROM public.vw_st_telegram_web_history;
