-- FIX product_aliases table first
alter table public.product_aliases add column if not exists status text not null default 'ACTIVE';
alter table public.product_aliases add column if not exists alias_norm text;
alter table public.product_aliases add column if not exists brand_hint text default '';
alter table public.product_aliases add column if not exists category_hint text default '';
alter table public.product_aliases add column if not exists variant_hint text default '';
alter table public.product_aliases add column if not exists language_code text default 'th';
alter table public.product_aliases add column if not exists usage_count integer default 0;

-- ensure unique index is on alias_norm only
drop index if exists public.uq_alias_product_norm;
create unique index if not exists uq_product_aliases_norm on public.product_aliases (alias_norm);

-- clean old bad data if any
-- delete from public.product_aliases where alias_norm is null or alias_norm = '';


-- INSERT 932 aliases
INSERT INTO public.product_aliases (product_id, alias_text, alias_norm, alias_type, language_code, brand_hint, category_hint, variant_hint, status, usage_count)
VALUES
(1, 'เวสมิ้นคูล', 'เวสมิ้นคูล', 'ADMIN_ALIAS', 'th', 'VESS', 'COOL', 'MINT', 'ACTIVE', 0),
(1, 'เวสมิ้นคูล1', 'เวสมิ้นคูล1', 'ADMIN_ALIAS', 'th', 'VESS', 'COOL', 'MINT', 'ACTIVE', 0),
(1, 'เวสมิ้นคูล 1', 'เวสมิ้นคูล 1', 'SHORT_FORM', 'th', 'VESS', 'COOL', 'MINT', 'ACTIVE', 0),
(1, 'เวสมิ้นคูล2', 'เวสมิ้นคูล2', 'ADMIN_ALIAS', 'th', 'VESS', 'COOL', 'MINT', 'ACTIVE', 0),
(1, 'เวสมิ้นคูล 2', 'เวสมิ้นคูล 2', 'SHORT_FORM', 'th', 'VESS', 'COOL', 'MINT', 'ACTIVE', 0),
(1, 'เวสมิ้นคูล3', 'เวสมิ้นคูล3', 'ADMIN_ALIAS', 'th', 'VESS', 'COOL', 'MINT', 'ACTIVE', 0),
(1, 'เวสมิ้นคูล 3', 'เวสมิ้นคูล 3', 'SHORT_FORM', 'th', 'VESS', 'COOL', 'MINT', 'ACTIVE', 0),
(1, 'เวสมิ้นคูล4', 'เวสมิ้นคูล4', 'ADMIN_ALIAS', 'th', 'VESS', 'COOL', 'MINT', 'ACTIVE', 0),
(1, 'เวสมิ้นคูล 4', 'เวสมิ้นคูล 4', 'SHORT_FORM', 'th', 'VESS', 'COOL', 'MINT', 'ACTIVE', 0),
(1, 'เวสมิ้นคูล5', 'เวสมิ้นคูล5', 'ADMIN_ALIAS', 'th', 'VESS', 'COOL', 'MINT', 'ACTIVE', 0),
(1, 'เวสมิ้นคูล 5', 'เวสมิ้นคูล 5', 'SHORT_FORM', 'th', 'VESS', 'COOL', 'MINT', 'ACTIVE', 0),
(2, 'เวสมิ้นเมนทอล', 'เวสมิ้นเมนทอล', 'ADMIN_ALIAS', 'th', 'VESS', 'MINT', 'MENTHOL', 'ACTIVE', 0),
(2, 'เวสมิ้นเมนทอล1', 'เวสมิ้นเมนทอล1', 'ADMIN_ALIAS', 'th', 'VESS', 'MINT', 'MENTHOL', 'ACTIVE', 0),
(2, 'เวสมิ้นเมนทอล 1', 'เวสมิ้นเมนทอล 1', 'SHORT_FORM', 'th', 'VESS', 'MINT', 'MENTHOL', 'ACTIVE', 0),
(2, 'เวสมิ้นเมนทอล2', 'เวสมิ้นเมนทอล2', 'ADMIN_ALIAS', 'th', 'VESS', 'MINT', 'MENTHOL', 'ACTIVE', 0),
(2, 'เวสมิ้นเมนทอล 2', 'เวสมิ้นเมนทอล 2', 'SHORT_FORM', 'th', 'VESS', 'MINT', 'MENTHOL', 'ACTIVE', 0),
(2, 'เวสมิ้นเมนทอล3', 'เวสมิ้นเมนทอล3', 'ADMIN_ALIAS', 'th', 'VESS', 'MINT', 'MENTHOL', 'ACTIVE', 0),
(2, 'เวสมิ้นเมนทอล 3', 'เวสมิ้นเมนทอล 3', 'SHORT_FORM', 'th', 'VESS', 'MINT', 'MENTHOL', 'ACTIVE', 0),
(2, 'เวสมิ้นเมนทอล4', 'เวสมิ้นเมนทอล4', 'ADMIN_ALIAS', 'th', 'VESS', 'MINT', 'MENTHOL', 'ACTIVE', 0),
(2, 'เวสมิ้นเมนทอล 4', 'เวสมิ้นเมนทอล 4', 'SHORT_FORM', 'th', 'VESS', 'MINT', 'MENTHOL', 'ACTIVE', 0),
(2, 'เวสมิ้นเมนทอล5', 'เวสมิ้นเมนทอล5', 'ADMIN_ALIAS', 'th', 'VESS', 'MINT', 'MENTHOL', 'ACTIVE', 0),
(2, 'เวสมิ้นเมนทอล 5', 'เวสมิ้นเมนทอล 5', 'SHORT_FORM', 'th', 'VESS', 'MINT', 'MENTHOL', 'ACTIVE', 0),
(3, 'โกเขียวขาว', 'โกเขียวขาว', 'ADMIN_ALIAS', 'th', 'GOLD MOUNT', 'MOUNT', 'GREEN_WHITE', 'ACTIVE', 0),
(3, 'โกเขียวขาว1', 'โกเขียวขาว1', 'ADMIN_ALIAS', 'th', 'GOLD MOUNT', 'MOUNT', 'GREEN_WHITE', 'ACTIVE', 0),
(3, 'โกเขียวขาว 1', 'โกเขียวขาว 1', 'SHORT_FORM', 'th', 'GOLD MOUNT', 'MOUNT', 'GREEN_WHITE', 'ACTIVE', 0),
(3, 'โกเขียวขาว2', 'โกเขียวขาว2', 'ADMIN_ALIAS', 'th', 'GOLD MOUNT', 'MOUNT', 'GREEN_WHITE', 'ACTIVE', 0),
(3, 'โกเขียวขาว 2', 'โกเขียวขาว 2', 'SHORT_FORM', 'th', 'GOLD MOUNT', 'MOUNT', 'GREEN_WHITE', 'ACTIVE', 0),
(3, 'โกเขียวขาว3', 'โกเขียวขาว3', 'ADMIN_ALIAS', 'th', 'GOLD MOUNT', 'MOUNT', 'GREEN_WHITE', 'ACTIVE', 0),
(3, 'โกเขียวขาว 3', 'โกเขียวขาว 3', 'SHORT_FORM', 'th', 'GOLD MOUNT', 'MOUNT', 'GREEN_WHITE', 'ACTIVE', 0),
(3, 'โกเขียวขาว4', 'โกเขียวขาว4', 'ADMIN_ALIAS', 'th', 'GOLD MOUNT', 'MOUNT', 'GREEN_WHITE', 'ACTIVE', 0),
(3, 'โกเขียวขาว 4', 'โกเขียวขาว 4', 'SHORT_FORM', 'th', 'GOLD MOUNT', 'MOUNT', 'GREEN_WHITE', 'ACTIVE', 0),
(3, 'โกเขียวขาว5', 'โกเขียวขาว5', 'ADMIN_ALIAS', 'th', 'GOLD MOUNT', 'MOUNT', 'GREEN_WHITE', 'ACTIVE', 0),
(3, 'โกเขียวขาว 5', 'โกเขียวขาว 5', 'SHORT_FORM', 'th', 'GOLD MOUNT', 'MOUNT', 'GREEN_WHITE', 'ACTIVE', 0),
(4, 'มิลาโน่เมนทอล', 'มิลาโน่เมนทอล', 'ADMIN_ALIAS', 'th', 'MILANO', 'MENTHOL', 'MENTHOL', 'ACTIVE', 0),
(4, 'มิลาโน่เมนทอล1', 'มิลาโน่เมนทอล1', 'ADMIN_ALIAS', 'th', 'MILANO', 'MENTHOL', 'MENTHOL', 'ACTIVE', 0),
(4, 'มิลาโน่เมนทอล 1', 'มิลาโน่เมนทอล 1', 'SHORT_FORM', 'th', 'MILANO', 'MENTHOL', 'MENTHOL', 'ACTIVE', 0),
(4, 'มิลาโน่เมนทอล2', 'มิลาโน่เมนทอล2', 'ADMIN_ALIAS', 'th', 'MILANO', 'MENTHOL', 'MENTHOL', 'ACTIVE', 0),
(4, 'มิลาโน่เมนทอล 2', 'มิลาโน่เมนทอล 2', 'SHORT_FORM', 'th', 'MILANO', 'MENTHOL', 'MENTHOL', 'ACTIVE', 0),
(4, 'มิลาโน่เมนทอล3', 'มิลาโน่เมนทอล3', 'ADMIN_ALIAS', 'th', 'MILANO', 'MENTHOL', 'MENTHOL', 'ACTIVE', 0),
(4, 'มิลาโน่เมนทอล 3', 'มิลาโน่เมนทอล 3', 'SHORT_FORM', 'th', 'MILANO', 'MENTHOL', 'MENTHOL', 'ACTIVE', 0),
(4, 'มิลาโน่เมนทอล4', 'มิลาโน่เมนทอล4', 'ADMIN_ALIAS', 'th', 'MILANO', 'MENTHOL', 'MENTHOL', 'ACTIVE', 0),
(4, 'มิลาโน่เมนทอล 4', 'มิลาโน่เมนทอล 4', 'SHORT_FORM', 'th', 'MILANO', 'MENTHOL', 'MENTHOL', 'ACTIVE', 0),
(4, 'มิลาโน่เมนทอล5', 'มิลาโน่เมนทอล5', 'ADMIN_ALIAS', 'th', 'MILANO', 'MENTHOL', 'MENTHOL', 'ACTIVE', 0),
(4, 'มิลาโน่เมนทอล 5', 'มิลาโน่เมนทอล 5', 'SHORT_FORM', 'th', 'MILANO', 'MENTHOL', 'MENTHOL', 'ACTIVE', 0),
(5, '🟢 MOND_GREEN  1 คอต', '🟢 mond_green 1 คอต', 'SHORT_FORM', 'th', 'MOND', 'GREEN', 'GREEN', 'ACTIVE', 0),
(5, 'MOND_GREEN ม่อนเขียว', 'mond_green ม่อนเขียว', 'SHORT_FORM', 'th', 'MOND', 'GREEN', 'GREEN', 'ACTIVE', 0),
(5, 'ม่อนเขียว1', 'ม่อนเขียว1', 'ADMIN_ALIAS', 'th', 'MOND', 'GREEN', 'GREEN', 'ACTIVE', 0),
(5, 'ม่อนเขียว 1', 'ม่อนเขียว 1', 'SHORT_FORM', 'th', 'MOND', 'GREEN', 'GREEN', 'ACTIVE', 0),
(5, 'ม่อนเขียว2', 'ม่อนเขียว2', 'ADMIN_ALIAS', 'th', 'MOND', 'GREEN', 'GREEN', 'ACTIVE', 0),
(5, 'ม่อนเขียว 2', 'ม่อนเขียว 2', 'SHORT_FORM', 'th', 'MOND', 'GREEN', 'GREEN', 'ACTIVE', 0),
(5, 'ม่อนเขียว3', 'ม่อนเขียว3', 'ADMIN_ALIAS', 'th', 'MOND', 'GREEN', 'GREEN', 'ACTIVE', 0),
(5, 'ม่อนเขียว 3', 'ม่อนเขียว 3', 'SHORT_FORM', 'th', 'MOND', 'GREEN', 'GREEN', 'ACTIVE', 0),
(5, 'ม่อนเขียว4', 'ม่อนเขียว4', 'ADMIN_ALIAS', 'th', 'MOND', 'GREEN', 'GREEN', 'ACTIVE', 0),
(5, 'ม่อนเขียว 4', 'ม่อนเขียว 4', 'SHORT_FORM', 'th', 'MOND', 'GREEN', 'GREEN', 'ACTIVE', 0),
(5, 'ม่อนเขียว5', 'ม่อนเขียว5', 'ADMIN_ALIAS', 'th', 'MOND', 'GREEN', 'GREEN', 'ACTIVE', 0),
(5, 'ม่อนเขียว 5', 'ม่อนเขียว 5', 'SHORT_FORM', 'th', 'MOND', 'GREEN', 'GREEN', 'ACTIVE', 0),
(5, '🟢MOND Signature Green', '🟢mond signature green', 'SHORT_FORM', 'th', 'MOND', 'GREEN', 'GREEN', 'ACTIVE', 0),
(6, 'แพตตินั่มเขียว', 'แพตตินั่มเขียว', 'ADMIN_ALIAS', 'th', 'PLATINUM', 'GREEN', 'GREEN', 'ACTIVE', 0),
(6, 'แพตตินั่มเขียว1', 'แพตตินั่มเขียว1', 'ADMIN_ALIAS', 'th', 'PLATINUM', 'GREEN', 'GREEN', 'ACTIVE', 0),
(6, 'แพตตินั่มเขียว 1', 'แพตตินั่มเขียว 1', 'SHORT_FORM', 'th', 'PLATINUM', 'GREEN', 'GREEN', 'ACTIVE', 0),
(6, 'แพตตินั่มเขียว2', 'แพตตินั่มเขียว2', 'ADMIN_ALIAS', 'th', 'PLATINUM', 'GREEN', 'GREEN', 'ACTIVE', 0),
(6, 'แพตตินั่มเขียว 2', 'แพตตินั่มเขียว 2', 'SHORT_FORM', 'th', 'PLATINUM', 'GREEN', 'GREEN', 'ACTIVE', 0),
(6, 'แพตตินั่มเขียว3', 'แพตตินั่มเขียว3', 'ADMIN_ALIAS', 'th', 'PLATINUM', 'GREEN', 'GREEN', 'ACTIVE', 0),
(6, 'แพตตินั่มเขียว 3', 'แพตตินั่มเขียว 3', 'SHORT_FORM', 'th', 'PLATINUM', 'GREEN', 'GREEN', 'ACTIVE', 0),
(6, 'แพตตินั่มเขียว4', 'แพตตินั่มเขียว4', 'ADMIN_ALIAS', 'th', 'PLATINUM', 'GREEN', 'GREEN', 'ACTIVE', 0),
(6, 'แพตตินั่มเขียว 4', 'แพตตินั่มเขียว 4', 'SHORT_FORM', 'th', 'PLATINUM', 'GREEN', 'GREEN', 'ACTIVE', 0),
(6, 'แพตตินั่มเขียว5', 'แพตตินั่มเขียว5', 'ADMIN_ALIAS', 'th', 'PLATINUM', 'GREEN', 'GREEN', 'ACTIVE', 0),
(6, 'แพตตินั่มเขียว 5', 'แพตตินั่มเขียว 5', 'SHORT_FORM', 'th', 'PLATINUM', 'GREEN', 'GREEN', 'ACTIVE', 0),
(7, 'ซีวอสเขียว', 'ซีวอสเขียว', 'ADMIN_ALIAS', 'th', 'SEVIOS', 'GREEN', 'GREEN', 'ACTIVE', 0),
(7, 'ซีวอสเขียว1', 'ซีวอสเขียว1', 'ADMIN_ALIAS', 'th', 'SEVIOS', 'GREEN', 'GREEN', 'ACTIVE', 0),
(7, 'ซีวอสเขียว 1', 'ซีวอสเขียว 1', 'SHORT_FORM', 'th', 'SEVIOS', 'GREEN', 'GREEN', 'ACTIVE', 0),
(7, 'ซีวอสเขียว2', 'ซีวอสเขียว2', 'ADMIN_ALIAS', 'th', 'SEVIOS', 'GREEN', 'GREEN', 'ACTIVE', 0),
(7, 'ซีวอสเขียว 2', 'ซีวอสเขียว 2', 'SHORT_FORM', 'th', 'SEVIOS', 'GREEN', 'GREEN', 'ACTIVE', 0),
(7, 'ซีวอสเขียว3', 'ซีวอสเขียว3', 'ADMIN_ALIAS', 'th', 'SEVIOS', 'GREEN', 'GREEN', 'ACTIVE', 0),
(7, 'ซีวอสเขียว 3', 'ซีวอสเขียว 3', 'SHORT_FORM', 'th', 'SEVIOS', 'GREEN', 'GREEN', 'ACTIVE', 0),
(7, 'ซีวอสเขียว4', 'ซีวอสเขียว4', 'ADMIN_ALIAS', 'th', 'SEVIOS', 'GREEN', 'GREEN', 'ACTIVE', 0),
(7, 'ซีวอสเขียว 4', 'ซีวอสเขียว 4', 'SHORT_FORM', 'th', 'SEVIOS', 'GREEN', 'GREEN', 'ACTIVE', 0),
(7, 'ซีวอสเขียว5', 'ซีวอสเขียว5', 'ADMIN_ALIAS', 'th', 'SEVIOS', 'GREEN', 'GREEN', 'ACTIVE', 0),
(7, 'ซีวอสเขียว 5', 'ซีวอสเขียว 5', 'SHORT_FORM', 'th', 'SEVIOS', 'GREEN', 'GREEN', 'ACTIVE', 0),
(8, 'เอสเอ็มเอสเขียว', 'เอสเอ็มเอสเขียว', 'ADMIN_ALIAS', 'th', 'SMS', 'GREEN', 'GREEN', 'ACTIVE', 0),
(8, 'เอสเอ็มเอสเขียว1', 'เอสเอ็มเอสเขียว1', 'ADMIN_ALIAS', 'th', 'SMS', 'GREEN', 'GREEN', 'ACTIVE', 0),
(8, 'เอสเอ็มเอสเขียว 1', 'เอสเอ็มเอสเขียว 1', 'SHORT_FORM', 'th', 'SMS', 'GREEN', 'GREEN', 'ACTIVE', 0),
(8, 'เอสเอ็มเอสเขียว2', 'เอสเอ็มเอสเขียว2', 'ADMIN_ALIAS', 'th', 'SMS', 'GREEN', 'GREEN', 'ACTIVE', 0),
(8, 'เอสเอ็มเอสเขียว 2', 'เอสเอ็มเอสเขียว 2', 'SHORT_FORM', 'th', 'SMS', 'GREEN', 'GREEN', 'ACTIVE', 0),
(8, 'เอสเอ็มเอสเขียว3', 'เอสเอ็มเอสเขียว3', 'ADMIN_ALIAS', 'th', 'SMS', 'GREEN', 'GREEN', 'ACTIVE', 0),
(8, 'เอสเอ็มเอสเขียว 3', 'เอสเอ็มเอสเขียว 3', 'SHORT_FORM', 'th', 'SMS', 'GREEN', 'GREEN', 'ACTIVE', 0),
(8, 'เอสเอ็มเอสเขียว4', 'เอสเอ็มเอสเขียว4', 'ADMIN_ALIAS', 'th', 'SMS', 'GREEN', 'GREEN', 'ACTIVE', 0),
(8, 'เอสเอ็มเอสเขียว 4', 'เอสเอ็มเอสเขียว 4', 'SHORT_FORM', 'th', 'SMS', 'GREEN', 'GREEN', 'ACTIVE', 0),
(8, 'เอสเอ็มเอสเขียว5', 'เอสเอ็มเอสเขียว5', 'ADMIN_ALIAS', 'th', 'SMS', 'GREEN', 'GREEN', 'ACTIVE', 0),
(8, 'เอสเอ็มเอสเขียว 5', 'เอสเอ็มเอสเขียว 5', 'SHORT_FORM', 'th', 'SMS', 'GREEN', 'GREEN', 'ACTIVE', 0),
(9, 'เท็กซัสเขียว', 'เท็กซัสเขียว', 'ADMIN_ALIAS', 'th', 'TEXAS', 'GREEN', 'GREEN', 'ACTIVE', 0),
(9, 'เท็กซัสเขียว1', 'เท็กซัสเขียว1', 'ADMIN_ALIAS', 'th', 'TEXAS', 'GREEN', 'GREEN', 'ACTIVE', 0),
(9, 'เท็กซัสเขียว 1', 'เท็กซัสเขียว 1', 'SHORT_FORM', 'th', 'TEXAS', 'GREEN', 'GREEN', 'ACTIVE', 0),
(9, 'เท็กซัสเขียว2', 'เท็กซัสเขียว2', 'ADMIN_ALIAS', 'th', 'TEXAS', 'GREEN', 'GREEN', 'ACTIVE', 0),
(9, 'เท็กซัสเขียว 2', 'เท็กซัสเขียว 2', 'SHORT_FORM', 'th', 'TEXAS', 'GREEN', 'GREEN', 'ACTIVE', 0),
(9, 'เท็กซัสเขียว3', 'เท็กซัสเขียว3', 'ADMIN_ALIAS', 'th', 'TEXAS', 'GREEN', 'GREEN', 'ACTIVE', 0),
(9, 'เท็กซัสเขียว 3', 'เท็กซัสเขียว 3', 'SHORT_FORM', 'th', 'TEXAS', 'GREEN', 'GREEN', 'ACTIVE', 0),
(9, 'เท็กซัสเขียว4', 'เท็กซัสเขียว4', 'ADMIN_ALIAS', 'th', 'TEXAS', 'GREEN', 'GREEN', 'ACTIVE', 0),
(9, 'เท็กซัสเขียว 4', 'เท็กซัสเขียว 4', 'SHORT_FORM', 'th', 'TEXAS', 'GREEN', 'GREEN', 'ACTIVE', 0),
(9, 'เท็กซัสเขียว5', 'เท็กซัสเขียว5', 'ADMIN_ALIAS', 'th', 'TEXAS', 'GREEN', 'GREEN', 'ACTIVE', 0),
(9, 'เท็กซัสเขียว 5', 'เท็กซัสเขียว 5', 'SHORT_FORM', 'th', 'TEXAS', 'GREEN', 'GREEN', 'ACTIVE', 0),
(10, 'เวสเขียว', 'เวสเขียว', 'ADMIN_ALIAS', 'th', 'VESS', 'GREEN', 'GREEN', 'ACTIVE', 0),
(10, 'เวสเขียว1', 'เวสเขียว1', 'ADMIN_ALIAS', 'th', 'VESS', 'GREEN', 'GREEN', 'ACTIVE', 0),
(10, 'เวสเขียว 1', 'เวสเขียว 1', 'SHORT_FORM', 'th', 'VESS', 'GREEN', 'GREEN', 'ACTIVE', 0),
(10, 'เวสเขียว2', 'เวสเขียว2', 'ADMIN_ALIAS', 'th', 'VESS', 'GREEN', 'GREEN', 'ACTIVE', 0),
(10, 'เวสเขียว 2', 'เวสเขียว 2', 'SHORT_FORM', 'th', 'VESS', 'GREEN', 'GREEN', 'ACTIVE', 0),
(10, 'เวสเขียว3', 'เวสเขียว3', 'ADMIN_ALIAS', 'th', 'VESS', 'GREEN', 'GREEN', 'ACTIVE', 0),
(10, 'เวสเขียว 3', 'เวสเขียว 3', 'SHORT_FORM', 'th', 'VESS', 'GREEN', 'GREEN', 'ACTIVE', 0),
(10, 'เวสเขียว4', 'เวสเขียว4', 'ADMIN_ALIAS', 'th', 'VESS', 'GREEN', 'GREEN', 'ACTIVE', 0),
(10, 'เวสเขียว 4', 'เวสเขียว 4', 'SHORT_FORM', 'th', 'VESS', 'GREEN', 'GREEN', 'ACTIVE', 0),
(10, 'เวสเขียว5', 'เวสเขียว5', 'ADMIN_ALIAS', 'th', 'VESS', 'GREEN', 'GREEN', 'ACTIVE', 0),
(10, 'เวสเขียว 5', 'เวสเขียว 5', 'SHORT_FORM', 'th', 'VESS', 'GREEN', 'GREEN', 'ACTIVE', 0),
(11, 'เวสเขียวเล็ก', 'เวสเขียวเล็ก', 'ADMIN_ALIAS', 'th', 'VESS', 'GREEN', 'SLIMS', 'ACTIVE', 0),
(11, 'เวสเขียวเล็ก1', 'เวสเขียวเล็ก1', 'ADMIN_ALIAS', 'th', 'VESS', 'GREEN', 'SLIMS', 'ACTIVE', 0),
(11, 'เวสเขียวเล็ก 1', 'เวสเขียวเล็ก 1', 'SHORT_FORM', 'th', 'VESS', 'GREEN', 'SLIMS', 'ACTIVE', 0),
(11, 'เวสเขียวเล็ก2', 'เวสเขียวเล็ก2', 'ADMIN_ALIAS', 'th', 'VESS', 'GREEN', 'SLIMS', 'ACTIVE', 0),
(11, 'เวสเขียวเล็ก 2', 'เวสเขียวเล็ก 2', 'SHORT_FORM', 'th', 'VESS', 'GREEN', 'SLIMS', 'ACTIVE', 0),
(11, 'เวสเขียวเล็ก3', 'เวสเขียวเล็ก3', 'ADMIN_ALIAS', 'th', 'VESS', 'GREEN', 'SLIMS', 'ACTIVE', 0),
(11, 'เวสเขียวเล็ก 3', 'เวสเขียวเล็ก 3', 'SHORT_FORM', 'th', 'VESS', 'GREEN', 'SLIMS', 'ACTIVE', 0),
(11, 'เวสเขียวเล็ก4', 'เวสเขียวเล็ก4', 'ADMIN_ALIAS', 'th', 'VESS', 'GREEN', 'SLIMS', 'ACTIVE', 0),
(11, 'เวสเขียวเล็ก 4', 'เวสเขียวเล็ก 4', 'SHORT_FORM', 'th', 'VESS', 'GREEN', 'SLIMS', 'ACTIVE', 0),
(11, 'เวสเขียวเล็ก5', 'เวสเขียวเล็ก5', 'ADMIN_ALIAS', 'th', 'VESS', 'GREEN', 'SLIMS', 'ACTIVE', 0),
(11, 'เวสเขียวเล็ก 5', 'เวสเขียวเล็ก 5', 'SHORT_FORM', 'th', 'VESS', 'GREEN', 'SLIMS', 'ACTIVE', 0),
(12, 'เวสมิ้น', 'เวสมิ้น', 'ADMIN_ALIAS', 'th', 'VESS', 'MINT', 'MINT', 'ACTIVE', 0),
(12, 'เวสมิ้น1', 'เวสมิ้น1', 'ADMIN_ALIAS', 'th', 'VESS', 'MINT', 'MINT', 'ACTIVE', 0),
(12, 'เวสมิ้น 1', 'เวสมิ้น 1', 'SHORT_FORM', 'th', 'VESS', 'MINT', 'MINT', 'ACTIVE', 0),
(12, 'เวสมิ้น2', 'เวสมิ้น2', 'ADMIN_ALIAS', 'th', 'VESS', 'MINT', 'MINT', 'ACTIVE', 0),
(12, 'เวสมิ้น 2', 'เวสมิ้น 2', 'SHORT_FORM', 'th', 'VESS', 'MINT', 'MINT', 'ACTIVE', 0),
(12, 'เวสมิ้น3', 'เวสมิ้น3', 'ADMIN_ALIAS', 'th', 'VESS', 'MINT', 'MINT', 'ACTIVE', 0),
(12, 'เวสมิ้น 3', 'เวสมิ้น 3', 'SHORT_FORM', 'th', 'VESS', 'MINT', 'MINT', 'ACTIVE', 0),
(12, 'เวสมิ้น4', 'เวสมิ้น4', 'ADMIN_ALIAS', 'th', 'VESS', 'MINT', 'MINT', 'ACTIVE', 0),
(12, 'เวสมิ้น 4', 'เวสมิ้น 4', 'SHORT_FORM', 'th', 'VESS', 'MINT', 'MINT', 'ACTIVE', 0),
(12, 'เวสมิ้น5', 'เวสมิ้น5', 'ADMIN_ALIAS', 'th', 'VESS', 'MINT', 'MINT', 'ACTIVE', 0),
(12, 'เวสมิ้น 5', 'เวสมิ้น 5', 'SHORT_FORM', 'th', 'VESS', 'MINT', 'MINT', 'ACTIVE', 0),
(13, 'วอคเขียว', 'วอคเขียว', 'ADMIN_ALIAS', 'th', 'VOXX', 'GREEN', 'GREEN', 'ACTIVE', 0),
(13, 'วอคเขียว1', 'วอคเขียว1', 'ADMIN_ALIAS', 'th', 'VOXX', 'GREEN', 'GREEN', 'ACTIVE', 0),
(13, 'วอคเขียว 1', 'วอคเขียว 1', 'SHORT_FORM', 'th', 'VOXX', 'GREEN', 'GREEN', 'ACTIVE', 0),
(13, 'วอคเขียว2', 'วอคเขียว2', 'ADMIN_ALIAS', 'th', 'VOXX', 'GREEN', 'GREEN', 'ACTIVE', 0),
(13, 'วอคเขียว 2', 'วอคเขียว 2', 'SHORT_FORM', 'th', 'VOXX', 'GREEN', 'GREEN', 'ACTIVE', 0),
(13, 'วอคเขียว3', 'วอคเขียว3', 'ADMIN_ALIAS', 'th', 'VOXX', 'GREEN', 'GREEN', 'ACTIVE', 0),
(13, 'วอคเขียว 3', 'วอคเขียว 3', 'SHORT_FORM', 'th', 'VOXX', 'GREEN', 'GREEN', 'ACTIVE', 0),
(13, 'วอคเขียว4', 'วอคเขียว4', 'ADMIN_ALIAS', 'th', 'VOXX', 'GREEN', 'GREEN', 'ACTIVE', 0),
(13, 'วอคเขียว 4', 'วอคเขียว 4', 'SHORT_FORM', 'th', 'VOXX', 'GREEN', 'GREEN', 'ACTIVE', 0),
(13, 'วอคเขียว5', 'วอคเขียว5', 'ADMIN_ALIAS', 'th', 'VOXX', 'GREEN', 'GREEN', 'ACTIVE', 0),
(13, 'วอคเขียว 5', 'วอคเขียว 5', 'SHORT_FORM', 'th', 'VOXX', 'GREEN', 'GREEN', 'ACTIVE', 0),
(14, 'เท็กซัสฟ้า', 'เท็กซัสฟ้า', 'ADMIN_ALIAS', 'th', 'TEXAS', 'BLUE', 'BLUE', 'ACTIVE', 0),
(14, 'เท็กซัสฟ้า1', 'เท็กซัสฟ้า1', 'ADMIN_ALIAS', 'th', 'TEXAS', 'BLUE', 'BLUE', 'ACTIVE', 0),
(14, 'เท็กซัสฟ้า 1', 'เท็กซัสฟ้า 1', 'SHORT_FORM', 'th', 'TEXAS', 'BLUE', 'BLUE', 'ACTIVE', 0),
(14, 'เท็กซัสฟ้า2', 'เท็กซัสฟ้า2', 'ADMIN_ALIAS', 'th', 'TEXAS', 'BLUE', 'BLUE', 'ACTIVE', 0),
(14, 'เท็กซัสฟ้า 2', 'เท็กซัสฟ้า 2', 'SHORT_FORM', 'th', 'TEXAS', 'BLUE', 'BLUE', 'ACTIVE', 0),
(14, 'เท็กซัสฟ้า3', 'เท็กซัสฟ้า3', 'ADMIN_ALIAS', 'th', 'TEXAS', 'BLUE', 'BLUE', 'ACTIVE', 0),
(14, 'เท็กซัสฟ้า 3', 'เท็กซัสฟ้า 3', 'SHORT_FORM', 'th', 'TEXAS', 'BLUE', 'BLUE', 'ACTIVE', 0),
(14, 'เท็กซัสฟ้า4', 'เท็กซัสฟ้า4', 'ADMIN_ALIAS', 'th', 'TEXAS', 'BLUE', 'BLUE', 'ACTIVE', 0),
(14, 'เท็กซัสฟ้า 4', 'เท็กซัสฟ้า 4', 'SHORT_FORM', 'th', 'TEXAS', 'BLUE', 'BLUE', 'ACTIVE', 0),
(14, 'เท็กซัสฟ้า5', 'เท็กซัสฟ้า5', 'ADMIN_ALIAS', 'th', 'TEXAS', 'BLUE', 'BLUE', 'ACTIVE', 0),
(14, 'เท็กซัสฟ้า 5', 'เท็กซัสฟ้า 5', 'SHORT_FORM', 'th', 'TEXAS', 'BLUE', 'BLUE', 'ACTIVE', 0),
(15, 'เวสเขียวดำ', 'เวสเขียวดำ', 'ADMIN_ALIAS', 'th', 'VESS', 'GREEN', 'BLACK', 'ACTIVE', 0),
(15, 'เวสเขียวดำ1', 'เวสเขียวดำ1', 'ADMIN_ALIAS', 'th', 'VESS', 'GREEN', 'BLACK', 'ACTIVE', 0),
(15, 'เวสเขียวดำ 1', 'เวสเขียวดำ 1', 'SHORT_FORM', 'th', 'VESS', 'GREEN', 'BLACK', 'ACTIVE', 0),
(15, 'เวสเขียวดำ2', 'เวสเขียวดำ2', 'ADMIN_ALIAS', 'th', 'VESS', 'GREEN', 'BLACK', 'ACTIVE', 0),
(15, 'เวสเขียวดำ 2', 'เวสเขียวดำ 2', 'SHORT_FORM', 'th', 'VESS', 'GREEN', 'BLACK', 'ACTIVE', 0),
(15, 'เวสเขียวดำ3', 'เวสเขียวดำ3', 'ADMIN_ALIAS', 'th', 'VESS', 'GREEN', 'BLACK', 'ACTIVE', 0),
(15, 'เวสเขียวดำ 3', 'เวสเขียวดำ 3', 'SHORT_FORM', 'th', 'VESS', 'GREEN', 'BLACK', 'ACTIVE', 0),
(15, 'เวสเขียวดำ4', 'เวสเขียวดำ4', 'ADMIN_ALIAS', 'th', 'VESS', 'GREEN', 'BLACK', 'ACTIVE', 0),
(15, 'เวสเขียวดำ 4', 'เวสเขียวดำ 4', 'SHORT_FORM', 'th', 'VESS', 'GREEN', 'BLACK', 'ACTIVE', 0),
(15, 'เวสเขียวดำ5', 'เวสเขียวดำ5', 'ADMIN_ALIAS', 'th', 'VESS', 'GREEN', 'BLACK', 'ACTIVE', 0),
(15, 'เวสเขียวดำ 5', 'เวสเขียวดำ 5', 'SHORT_FORM', 'th', 'VESS', 'GREEN', 'BLACK', 'ACTIVE', 0),
(16, 'เซียร่าเขียว', 'เซียร่าเขียว', 'ADMIN_ALIAS', 'th', 'SIERRA', 'GREEN', 'GREEN', 'ACTIVE', 0),
(16, 'เซียร่าเขียว1', 'เซียร่าเขียว1', 'ADMIN_ALIAS', 'th', 'SIERRA', 'GREEN', 'GREEN', 'ACTIVE', 0),
(16, 'เซียร่าเขียว2', 'เซียร่าเขียว2', 'ADMIN_ALIAS', 'th', 'SIERRA', 'GREEN', 'GREEN', 'ACTIVE', 0),
(16, 'เซียร่าเขียว3', 'เซียร่าเขียว3', 'ADMIN_ALIAS', 'th', 'SIERRA', 'GREEN', 'GREEN', 'ACTIVE', 0),
(16, 'เซียร่าเขียว4', 'เซียร่าเขียว4', 'ADMIN_ALIAS', 'th', 'SIERRA', 'GREEN', 'GREEN', 'ACTIVE', 0),
(16, 'เซียร่าเขียว5', 'เซียร่าเขียว5', 'ADMIN_ALIAS', 'th', 'SIERRA', 'GREEN', 'GREEN', 'ACTIVE', 0),
(16, 'เซียร่าเขียว 1', 'เซียร่าเขียว 1', 'SHORT_FORM', 'th', 'SIERRA', 'GREEN', 'GREEN', 'ACTIVE', 0),
(16, 'เซียร่าเขียว 2', 'เซียร่าเขียว 2', 'SHORT_FORM', 'th', 'SIERRA', 'GREEN', 'GREEN', 'ACTIVE', 0),
(16, 'เซียร่าเขียว 3', 'เซียร่าเขียว 3', 'SHORT_FORM', 'th', 'SIERRA', 'GREEN', 'GREEN', 'ACTIVE', 0),
(16, 'เซียร่าเขียว 4', 'เซียร่าเขียว 4', 'SHORT_FORM', 'th', 'SIERRA', 'GREEN', 'GREEN', 'ACTIVE', 0),
(16, 'เซียร่าเขียว 5', 'เซียร่าเขียว 5', 'SHORT_FORM', 'th', 'SIERRA', 'GREEN', 'GREEN', 'ACTIVE', 0),
(16, 'เซียร์ร่าเขียว', 'เซียร์ร่าเขียว', 'ADMIN_ALIAS', 'th', 'SIERRA', 'GREEN', 'GREEN', 'ACTIVE', 0),
(16, 'เซียร์ร่าเขียว1', 'เซียร์ร่าเขียว1', 'ADMIN_ALIAS', 'th', 'SIERRA', 'GREEN', 'GREEN', 'ACTIVE', 0),
(16, 'เซียร์ร่าเขียว2', 'เซียร์ร่าเขียว2', 'ADMIN_ALIAS', 'th', 'SIERRA', 'GREEN', 'GREEN', 'ACTIVE', 0),
(16, 'เซียร์ร่าเขียว3', 'เซียร์ร่าเขียว3', 'ADMIN_ALIAS', 'th', 'SIERRA', 'GREEN', 'GREEN', 'ACTIVE', 0),
(16, 'เซียร์ร่าเขียว4', 'เซียร์ร่าเขียว4', 'ADMIN_ALIAS', 'th', 'SIERRA', 'GREEN', 'GREEN', 'ACTIVE', 0),
(16, 'เซียร์ร่าเขียว5', 'เซียร์ร่าเขียว5', 'ADMIN_ALIAS', 'th', 'SIERRA', 'GREEN', 'GREEN', 'ACTIVE', 0),
(16, 'เซียร์ร่าเขียว 1', 'เซียร์ร่าเขียว 1', 'SHORT_FORM', 'th', 'SIERRA', 'GREEN', 'GREEN', 'ACTIVE', 0),
(16, 'เซียร์ร่าเขียว 2', 'เซียร์ร่าเขียว 2', 'SHORT_FORM', 'th', 'SIERRA', 'GREEN', 'GREEN', 'ACTIVE', 0),
(16, 'เซียร์ร่าเขียว 3', 'เซียร์ร่าเขียว 3', 'SHORT_FORM', 'th', 'SIERRA', 'GREEN', 'GREEN', 'ACTIVE', 0),
(16, 'เซียร์ร่าเขียว 4', 'เซียร์ร่าเขียว 4', 'SHORT_FORM', 'th', 'SIERRA', 'GREEN', 'GREEN', 'ACTIVE', 0),
(16, 'เซียร์ร่าเขียว 5', 'เซียร์ร่าเขียว 5', 'SHORT_FORM', 'th', 'SIERRA', 'GREEN', 'GREEN', 'ACTIVE', 0),
(17, 'OS บลูเบอร์รี่', 'os บลูเบอร์รี่', 'SHORT_FORM', 'th', 'OS', 'BLUEBERRY', 'BLUEBERRY', 'ACTIVE', 0),
(17, 'OS บลูเบอร์รี่1', 'os บลูเบอร์รี่1', 'SHORT_FORM', 'th', 'OS', 'BLUEBERRY', 'BLUEBERRY', 'ACTIVE', 0),
(17, 'OS บลูเบอร์รี่ 1', 'os บลูเบอร์รี่ 1', 'SHORT_FORM', 'th', 'OS', 'BLUEBERRY', 'BLUEBERRY', 'ACTIVE', 0),
(17, 'OS บลูเบอร์รี่2', 'os บลูเบอร์รี่2', 'SHORT_FORM', 'th', 'OS', 'BLUEBERRY', 'BLUEBERRY', 'ACTIVE', 0),
(17, 'OS บลูเบอร์รี่ 2', 'os บลูเบอร์รี่ 2', 'SHORT_FORM', 'th', 'OS', 'BLUEBERRY', 'BLUEBERRY', 'ACTIVE', 0),
(17, 'OS บลูเบอร์รี่3', 'os บลูเบอร์รี่3', 'SHORT_FORM', 'th', 'OS', 'BLUEBERRY', 'BLUEBERRY', 'ACTIVE', 0),
(17, 'OS บลูเบอร์รี่ 3', 'os บลูเบอร์รี่ 3', 'SHORT_FORM', 'th', 'OS', 'BLUEBERRY', 'BLUEBERRY', 'ACTIVE', 0),
(17, 'OS บลูเบอร์รี่4', 'os บลูเบอร์รี่4', 'SHORT_FORM', 'th', 'OS', 'BLUEBERRY', 'BLUEBERRY', 'ACTIVE', 0),
(17, 'OS บลูเบอร์รี่ 4', 'os บลูเบอร์รี่ 4', 'SHORT_FORM', 'th', 'OS', 'BLUEBERRY', 'BLUEBERRY', 'ACTIVE', 0),
(17, 'OS บลูเบอร์รี่5', 'os บลูเบอร์รี่5', 'SHORT_FORM', 'th', 'OS', 'BLUEBERRY', 'BLUEBERRY', 'ACTIVE', 0),
(17, 'OS บลูเบอร์รี่ 5', 'os บลูเบอร์รี่ 5', 'SHORT_FORM', 'th', 'OS', 'BLUEBERRY', 'BLUEBERRY', 'ACTIVE', 0)
ON CONFLICT (alias_norm) DO UPDATE SET
  alias_text = EXCLUDED.alias_text,
  product_id = EXCLUDED.product_id,
  alias_type = EXCLUDED.alias_type,
  brand_hint = EXCLUDED.brand_hint,
  category_hint = EXCLUDED.category_hint,
  variant_hint = EXCLUDED.variant_hint,
  status = EXCLUDED.status,
  updated_at = now();

INSERT INTO public.product_aliases (product_id, alias_text, alias_norm, alias_type, language_code, brand_hint, category_hint, variant_hint, status, usage_count)
VALUES
(17, 'OS บลู 1', 'os บลู 1', 'SHORT_FORM', 'th', 'OS', 'BLUEBERRY', 'BLUEBERRY', 'ACTIVE', 0),
(18, 'OS มะม่วง', 'os มะม่วง', 'SHORT_FORM', 'th', 'OS', 'MANGO', 'MANGO', 'ACTIVE', 0),
(18, 'OS มะม่วง1', 'os มะม่วง1', 'SHORT_FORM', 'th', 'OS', 'MANGO', 'MANGO', 'ACTIVE', 0),
(18, 'OS มะม่วง 1', 'os มะม่วง 1', 'SHORT_FORM', 'th', 'OS', 'MANGO', 'MANGO', 'ACTIVE', 0),
(18, 'OS มะม่วง2', 'os มะม่วง2', 'SHORT_FORM', 'th', 'OS', 'MANGO', 'MANGO', 'ACTIVE', 0),
(18, 'OS มะม่วง 2', 'os มะม่วง 2', 'SHORT_FORM', 'th', 'OS', 'MANGO', 'MANGO', 'ACTIVE', 0),
(18, 'OS มะม่วง3', 'os มะม่วง3', 'SHORT_FORM', 'th', 'OS', 'MANGO', 'MANGO', 'ACTIVE', 0),
(18, 'OS มะม่วง 3', 'os มะม่วง 3', 'SHORT_FORM', 'th', 'OS', 'MANGO', 'MANGO', 'ACTIVE', 0),
(18, 'OS มะม่วง4', 'os มะม่วง4', 'SHORT_FORM', 'th', 'OS', 'MANGO', 'MANGO', 'ACTIVE', 0),
(18, 'OS มะม่วง 4', 'os มะม่วง 4', 'SHORT_FORM', 'th', 'OS', 'MANGO', 'MANGO', 'ACTIVE', 0),
(18, 'OS มะม่วง5', 'os มะม่วง5', 'SHORT_FORM', 'th', 'OS', 'MANGO', 'MANGO', 'ACTIVE', 0),
(18, 'OS มะม่วง 5', 'os มะม่วง 5', 'SHORT_FORM', 'th', 'OS', 'MANGO', 'MANGO', 'ACTIVE', 0),
(19, 'เวสมะม่วง', 'เวสมะม่วง', 'ADMIN_ALIAS', 'th', 'VESS', 'CRUSH', 'MINT.X.MANGO', 'ACTIVE', 0),
(19, 'เวสมะม่วง1', 'เวสมะม่วง1', 'ADMIN_ALIAS', 'th', 'VESS', 'CRUSH', 'MINT.X.MANGO', 'ACTIVE', 0),
(19, 'เวสมะม่วง 1', 'เวสมะม่วง 1', 'SHORT_FORM', 'th', 'VESS', 'CRUSH', 'MINT.X.MANGO', 'ACTIVE', 0),
(19, 'เวสมะม่วง2', 'เวสมะม่วง2', 'ADMIN_ALIAS', 'th', 'VESS', 'CRUSH', 'MINT.X.MANGO', 'ACTIVE', 0),
(19, 'เวสมะม่วง 2', 'เวสมะม่วง 2', 'SHORT_FORM', 'th', 'VESS', 'CRUSH', 'MINT.X.MANGO', 'ACTIVE', 0),
(19, 'เวสมะม่วง3', 'เวสมะม่วง3', 'ADMIN_ALIAS', 'th', 'VESS', 'CRUSH', 'MINT.X.MANGO', 'ACTIVE', 0),
(19, 'เวสมะม่วง 3', 'เวสมะม่วง 3', 'SHORT_FORM', 'th', 'VESS', 'CRUSH', 'MINT.X.MANGO', 'ACTIVE', 0),
(19, 'เวสมะม่วง4', 'เวสมะม่วง4', 'ADMIN_ALIAS', 'th', 'VESS', 'CRUSH', 'MINT.X.MANGO', 'ACTIVE', 0),
(19, 'เวสมะม่วง 4', 'เวสมะม่วง 4', 'SHORT_FORM', 'th', 'VESS', 'CRUSH', 'MINT.X.MANGO', 'ACTIVE', 0),
(19, 'เวสมะม่วง5', 'เวสมะม่วง5', 'ADMIN_ALIAS', 'th', 'VESS', 'CRUSH', 'MINT.X.MANGO', 'ACTIVE', 0),
(19, 'เวสมะม่วง 5', 'เวสมะม่วง 5', 'SHORT_FORM', 'th', 'VESS', 'CRUSH', 'MINT.X.MANGO', 'ACTIVE', 0),
(20, 'OS สตอเบอร์รี่', 'os สตอเบอร์รี่', 'SHORT_FORM', 'th', 'OS', 'STRAWBERRY', 'STRAWBERRY', 'ACTIVE', 0),
(20, 'OS สตอเบอร์รี่1', 'os สตอเบอร์รี่1', 'SHORT_FORM', 'th', 'OS', 'STRAWBERRY', 'STRAWBERRY', 'ACTIVE', 0),
(20, 'OS สตอเบอร์รี่ 1', 'os สตอเบอร์รี่ 1', 'SHORT_FORM', 'th', 'OS', 'STRAWBERRY', 'STRAWBERRY', 'ACTIVE', 0),
(20, 'OS สตอเบอร์รี่2', 'os สตอเบอร์รี่2', 'SHORT_FORM', 'th', 'OS', 'STRAWBERRY', 'STRAWBERRY', 'ACTIVE', 0),
(20, 'OS สตอเบอร์รี่ 2', 'os สตอเบอร์รี่ 2', 'SHORT_FORM', 'th', 'OS', 'STRAWBERRY', 'STRAWBERRY', 'ACTIVE', 0),
(20, 'OS สตอเบอร์รี่3', 'os สตอเบอร์รี่3', 'SHORT_FORM', 'th', 'OS', 'STRAWBERRY', 'STRAWBERRY', 'ACTIVE', 0),
(20, 'OS สตอเบอร์รี่ 3', 'os สตอเบอร์รี่ 3', 'SHORT_FORM', 'th', 'OS', 'STRAWBERRY', 'STRAWBERRY', 'ACTIVE', 0),
(20, 'OS สตอเบอร์รี่4', 'os สตอเบอร์รี่4', 'SHORT_FORM', 'th', 'OS', 'STRAWBERRY', 'STRAWBERRY', 'ACTIVE', 0),
(20, 'OS สตอเบอร์รี่ 4', 'os สตอเบอร์รี่ 4', 'SHORT_FORM', 'th', 'OS', 'STRAWBERRY', 'STRAWBERRY', 'ACTIVE', 0),
(20, 'OS สตอเบอร์รี่5', 'os สตอเบอร์รี่5', 'SHORT_FORM', 'th', 'OS', 'STRAWBERRY', 'STRAWBERRY', 'ACTIVE', 0),
(20, 'OS สตอเบอร์รี่ 5', 'os สตอเบอร์รี่ 5', 'SHORT_FORM', 'th', 'OS', 'STRAWBERRY', 'STRAWBERRY', 'ACTIVE', 0),
(21, 'มิลาโน่ญี่ปุ่น', 'มิลาโน่ญี่ปุ่น', 'ADMIN_ALIAS', 'th', 'MILANO', 'JAPAN', 'JAPAN', 'ACTIVE', 0),
(21, 'มิลาโน่ญี่ปุ่น1', 'มิลาโน่ญี่ปุ่น1', 'ADMIN_ALIAS', 'th', 'MILANO', 'JAPAN', 'JAPAN', 'ACTIVE', 0),
(21, 'มิลาโน่ญี่ปุ่น 1', 'มิลาโน่ญี่ปุ่น 1', 'SHORT_FORM', 'th', 'MILANO', 'JAPAN', 'JAPAN', 'ACTIVE', 0),
(21, 'มิลาโน่ญี่ปุ่น2', 'มิลาโน่ญี่ปุ่น2', 'ADMIN_ALIAS', 'th', 'MILANO', 'JAPAN', 'JAPAN', 'ACTIVE', 0),
(21, 'มิลาโน่ญี่ปุ่น 2', 'มิลาโน่ญี่ปุ่น 2', 'SHORT_FORM', 'th', 'MILANO', 'JAPAN', 'JAPAN', 'ACTIVE', 0),
(21, 'มิลาโน่ญี่ปุ่น3', 'มิลาโน่ญี่ปุ่น3', 'ADMIN_ALIAS', 'th', 'MILANO', 'JAPAN', 'JAPAN', 'ACTIVE', 0),
(21, 'มิลาโน่ญี่ปุ่น 3', 'มิลาโน่ญี่ปุ่น 3', 'SHORT_FORM', 'th', 'MILANO', 'JAPAN', 'JAPAN', 'ACTIVE', 0),
(21, 'มิลาโน่ญี่ปุ่น4', 'มิลาโน่ญี่ปุ่น4', 'ADMIN_ALIAS', 'th', 'MILANO', 'JAPAN', 'JAPAN', 'ACTIVE', 0),
(21, 'มิลาโน่ญี่ปุ่น 4', 'มิลาโน่ญี่ปุ่น 4', 'SHORT_FORM', 'th', 'MILANO', 'JAPAN', 'JAPAN', 'ACTIVE', 0),
(21, 'มิลาโน่ญี่ปุ่น5', 'มิลาโน่ญี่ปุ่น5', 'ADMIN_ALIAS', 'th', 'MILANO', 'JAPAN', 'JAPAN', 'ACTIVE', 0),
(21, 'มิลาโน่ญี่ปุ่น 5', 'มิลาโน่ญี่ปุ่น 5', 'SHORT_FORM', 'th', 'MILANO', 'JAPAN', 'JAPAN', 'ACTIVE', 0),
(22, 'OS สับปะรด', 'os สับปะรด', 'SHORT_FORM', 'th', 'OS', 'PINEAPPLE', 'PINEAPPLE', 'ACTIVE', 0),
(22, 'OS สับปะรด1', 'os สับปะรด1', 'SHORT_FORM', 'th', 'OS', 'PINEAPPLE', 'PINEAPPLE', 'ACTIVE', 0),
(22, 'OS สับปะรด 1', 'os สับปะรด 1', 'SHORT_FORM', 'th', 'OS', 'PINEAPPLE', 'PINEAPPLE', 'ACTIVE', 0),
(22, 'OS สับปะรด2', 'os สับปะรด2', 'SHORT_FORM', 'th', 'OS', 'PINEAPPLE', 'PINEAPPLE', 'ACTIVE', 0),
(22, 'OS สับปะรด 2', 'os สับปะรด 2', 'SHORT_FORM', 'th', 'OS', 'PINEAPPLE', 'PINEAPPLE', 'ACTIVE', 0),
(22, 'OS สับปะรด3', 'os สับปะรด3', 'SHORT_FORM', 'th', 'OS', 'PINEAPPLE', 'PINEAPPLE', 'ACTIVE', 0),
(22, 'OS สับปะรด 3', 'os สับปะรด 3', 'SHORT_FORM', 'th', 'OS', 'PINEAPPLE', 'PINEAPPLE', 'ACTIVE', 0),
(22, 'OS สับปะรด4', 'os สับปะรด4', 'SHORT_FORM', 'th', 'OS', 'PINEAPPLE', 'PINEAPPLE', 'ACTIVE', 0),
(22, 'OS สับปะรด 4', 'os สับปะรด 4', 'SHORT_FORM', 'th', 'OS', 'PINEAPPLE', 'PINEAPPLE', 'ACTIVE', 0),
(22, 'OS สับปะรด5', 'os สับปะรด5', 'SHORT_FORM', 'th', 'OS', 'PINEAPPLE', 'PINEAPPLE', 'ACTIVE', 0),
(22, 'OS สับปะรด 5', 'os สับปะรด 5', 'SHORT_FORM', 'th', 'OS', 'PINEAPPLE', 'PINEAPPLE', 'ACTIVE', 0),
(23, 'เวสแอปเปิ้ล', 'เวสแอปเปิ้ล', 'ADMIN_ALIAS', 'th', 'VESS', 'CRUSH', 'MINT.X.APPLE', 'ACTIVE', 0),
(23, 'เวสแอปเปิ้ล1', 'เวสแอปเปิ้ล1', 'ADMIN_ALIAS', 'th', 'VESS', 'CRUSH', 'MINT.X.APPLE', 'ACTIVE', 0),
(23, 'เวสแอปเปิ้ล 1', 'เวสแอปเปิ้ล 1', 'SHORT_FORM', 'th', 'VESS', 'CRUSH', 'MINT.X.APPLE', 'ACTIVE', 0),
(23, 'เวสแอปเปิ้ล2', 'เวสแอปเปิ้ล2', 'ADMIN_ALIAS', 'th', 'VESS', 'CRUSH', 'MINT.X.APPLE', 'ACTIVE', 0),
(23, 'เวสแอปเปิ้ล 2', 'เวสแอปเปิ้ล 2', 'SHORT_FORM', 'th', 'VESS', 'CRUSH', 'MINT.X.APPLE', 'ACTIVE', 0),
(23, 'เวสแอปเปิ้ล3', 'เวสแอปเปิ้ล3', 'ADMIN_ALIAS', 'th', 'VESS', 'CRUSH', 'MINT.X.APPLE', 'ACTIVE', 0),
(23, 'เวสแอปเปิ้ล 3', 'เวสแอปเปิ้ล 3', 'SHORT_FORM', 'th', 'VESS', 'CRUSH', 'MINT.X.APPLE', 'ACTIVE', 0),
(23, 'เวสแอปเปิ้ล4', 'เวสแอปเปิ้ล4', 'ADMIN_ALIAS', 'th', 'VESS', 'CRUSH', 'MINT.X.APPLE', 'ACTIVE', 0),
(23, 'เวสแอปเปิ้ล 4', 'เวสแอปเปิ้ล 4', 'SHORT_FORM', 'th', 'VESS', 'CRUSH', 'MINT.X.APPLE', 'ACTIVE', 0),
(23, 'เวสแอปเปิ้ล5', 'เวสแอปเปิ้ล5', 'ADMIN_ALIAS', 'th', 'VESS', 'CRUSH', 'MINT.X.APPLE', 'ACTIVE', 0),
(23, 'เวสแอปเปิ้ล 5', 'เวสแอปเปิ้ล 5', 'SHORT_FORM', 'th', 'VESS', 'CRUSH', 'MINT.X.APPLE', 'ACTIVE', 0),
(24, 'OS แตงโม', 'os แตงโม', 'SHORT_FORM', 'th', 'OS', 'WATERMELON', 'WATERMELON', 'ACTIVE', 0),
(24, 'OS แตงโม1', 'os แตงโม1', 'SHORT_FORM', 'th', 'OS', 'WATERMELON', 'WATERMELON', 'ACTIVE', 0),
(24, 'OS แตงโม 1', 'os แตงโม 1', 'SHORT_FORM', 'th', 'OS', 'WATERMELON', 'WATERMELON', 'ACTIVE', 0),
(24, 'OS แตงโม2', 'os แตงโม2', 'SHORT_FORM', 'th', 'OS', 'WATERMELON', 'WATERMELON', 'ACTIVE', 0),
(24, 'OS แตงโม 2', 'os แตงโม 2', 'SHORT_FORM', 'th', 'OS', 'WATERMELON', 'WATERMELON', 'ACTIVE', 0),
(24, 'OS แตงโม3', 'os แตงโม3', 'SHORT_FORM', 'th', 'OS', 'WATERMELON', 'WATERMELON', 'ACTIVE', 0),
(24, 'OS แตงโม 3', 'os แตงโม 3', 'SHORT_FORM', 'th', 'OS', 'WATERMELON', 'WATERMELON', 'ACTIVE', 0),
(24, 'OS แตงโม4', 'os แตงโม4', 'SHORT_FORM', 'th', 'OS', 'WATERMELON', 'WATERMELON', 'ACTIVE', 0),
(24, 'OS แตงโม 4', 'os แตงโม 4', 'SHORT_FORM', 'th', 'OS', 'WATERMELON', 'WATERMELON', 'ACTIVE', 0),
(24, 'OS แตงโม5', 'os แตงโม5', 'SHORT_FORM', 'th', 'OS', 'WATERMELON', 'WATERMELON', 'ACTIVE', 0),
(24, 'OS แตงโม 5', 'os แตงโม 5', 'SHORT_FORM', 'th', 'OS', 'WATERMELON', 'WATERMELON', 'ACTIVE', 0),
(25, 'เวสองุ่นใหญ่', 'เวสองุ่นใหญ่', 'ADMIN_ALIAS', 'th', 'VESS', 'CRUSH', 'MINT.X.GRAPE', 'ACTIVE', 0),
(25, 'เวสองุ่นใหญ่1', 'เวสองุ่นใหญ่1', 'ADMIN_ALIAS', 'th', 'VESS', 'CRUSH', 'MINT.X.GRAPE', 'ACTIVE', 0),
(25, 'เวสองุ่นใหญ่ 1', 'เวสองุ่นใหญ่ 1', 'SHORT_FORM', 'th', 'VESS', 'CRUSH', 'MINT.X.GRAPE', 'ACTIVE', 0),
(25, 'เวสองุ่นใหญ่2', 'เวสองุ่นใหญ่2', 'ADMIN_ALIAS', 'th', 'VESS', 'CRUSH', 'MINT.X.GRAPE', 'ACTIVE', 0),
(25, 'เวสองุ่นใหญ่ 2', 'เวสองุ่นใหญ่ 2', 'SHORT_FORM', 'th', 'VESS', 'CRUSH', 'MINT.X.GRAPE', 'ACTIVE', 0),
(25, 'เวสองุ่นใหญ่3', 'เวสองุ่นใหญ่3', 'ADMIN_ALIAS', 'th', 'VESS', 'CRUSH', 'MINT.X.GRAPE', 'ACTIVE', 0),
(25, 'เวสองุ่นใหญ่ 3', 'เวสองุ่นใหญ่ 3', 'SHORT_FORM', 'th', 'VESS', 'CRUSH', 'MINT.X.GRAPE', 'ACTIVE', 0),
(25, 'เวสองุ่นใหญ่4', 'เวสองุ่นใหญ่4', 'ADMIN_ALIAS', 'th', 'VESS', 'CRUSH', 'MINT.X.GRAPE', 'ACTIVE', 0),
(25, 'เวสองุ่นใหญ่ 4', 'เวสองุ่นใหญ่ 4', 'SHORT_FORM', 'th', 'VESS', 'CRUSH', 'MINT.X.GRAPE', 'ACTIVE', 0),
(25, 'เวสองุ่นใหญ่5', 'เวสองุ่นใหญ่5', 'ADMIN_ALIAS', 'th', 'VESS', 'CRUSH', 'MINT.X.GRAPE', 'ACTIVE', 0),
(25, 'เวสองุ่นใหญ่ 5', 'เวสองุ่นใหญ่ 5', 'SHORT_FORM', 'th', 'VESS', 'CRUSH', 'MINT.X.GRAPE', 'ACTIVE', 0),
(26, 'เวสองุ่นสลิม', 'เวสองุ่นสลิม', 'ADMIN_ALIAS', 'th', 'VESS', 'GRAPE', 'SLIMS', 'ACTIVE', 0),
(26, 'เวสองุ่นสลิม1', 'เวสองุ่นสลิม1', 'ADMIN_ALIAS', 'th', 'VESS', 'GRAPE', 'SLIMS', 'ACTIVE', 0),
(26, 'เวสองุ่นสลิม 1', 'เวสองุ่นสลิม 1', 'SHORT_FORM', 'th', 'VESS', 'GRAPE', 'SLIMS', 'ACTIVE', 0),
(26, 'เวสองุ่นสลิม2', 'เวสองุ่นสลิม2', 'ADMIN_ALIAS', 'th', 'VESS', 'GRAPE', 'SLIMS', 'ACTIVE', 0),
(26, 'เวสองุ่นสลิม 2', 'เวสองุ่นสลิม 2', 'SHORT_FORM', 'th', 'VESS', 'GRAPE', 'SLIMS', 'ACTIVE', 0),
(26, 'เวสองุ่นสลิม3', 'เวสองุ่นสลิม3', 'ADMIN_ALIAS', 'th', 'VESS', 'GRAPE', 'SLIMS', 'ACTIVE', 0),
(26, 'เวสองุ่นสลิม 3', 'เวสองุ่นสลิม 3', 'SHORT_FORM', 'th', 'VESS', 'GRAPE', 'SLIMS', 'ACTIVE', 0),
(26, 'เวสองุ่นสลิม4', 'เวสองุ่นสลิม4', 'ADMIN_ALIAS', 'th', 'VESS', 'GRAPE', 'SLIMS', 'ACTIVE', 0),
(26, 'เวสองุ่นสลิม 4', 'เวสองุ่นสลิม 4', 'SHORT_FORM', 'th', 'VESS', 'GRAPE', 'SLIMS', 'ACTIVE', 0),
(26, 'เวสองุ่นสลิม5', 'เวสองุ่นสลิม5', 'ADMIN_ALIAS', 'th', 'VESS', 'GRAPE', 'SLIMS', 'ACTIVE', 0),
(26, 'เวสองุ่นสลิม 5', 'เวสองุ่นสลิม 5', 'SHORT_FORM', 'th', 'VESS', 'GRAPE', 'SLIMS', 'ACTIVE', 0),
(27, 'ม่อนรุ้ง', 'ม่อนรุ้ง', 'ADMIN_ALIAS', 'th', 'MOND', 'RAINBOW', 'RAINBOW', 'ACTIVE', 0),
(27, 'ม่อนรุ้ง1', 'ม่อนรุ้ง1', 'ADMIN_ALIAS', 'th', 'MOND', 'RAINBOW', 'RAINBOW', 'ACTIVE', 0),
(27, 'ม่อนรุ้ง 1', 'ม่อนรุ้ง 1', 'SHORT_FORM', 'th', 'MOND', 'RAINBOW', 'RAINBOW', 'ACTIVE', 0),
(27, 'ม่อนรุ้ง2', 'ม่อนรุ้ง2', 'ADMIN_ALIAS', 'th', 'MOND', 'RAINBOW', 'RAINBOW', 'ACTIVE', 0),
(27, 'ม่อนรุ้ง 2', 'ม่อนรุ้ง 2', 'SHORT_FORM', 'th', 'MOND', 'RAINBOW', 'RAINBOW', 'ACTIVE', 0),
(27, 'ม่อนรุ้ง3', 'ม่อนรุ้ง3', 'ADMIN_ALIAS', 'th', 'MOND', 'RAINBOW', 'RAINBOW', 'ACTIVE', 0),
(27, 'ม่อนรุ้ง 3', 'ม่อนรุ้ง 3', 'SHORT_FORM', 'th', 'MOND', 'RAINBOW', 'RAINBOW', 'ACTIVE', 0),
(27, 'ม่อนรุ้ง4', 'ม่อนรุ้ง4', 'ADMIN_ALIAS', 'th', 'MOND', 'RAINBOW', 'RAINBOW', 'ACTIVE', 0),
(27, 'ม่อนรุ้ง 4', 'ม่อนรุ้ง 4', 'SHORT_FORM', 'th', 'MOND', 'RAINBOW', 'RAINBOW', 'ACTIVE', 0),
(27, 'ม่อนรุ้ง5', 'ม่อนรุ้ง5', 'ADMIN_ALIAS', 'th', 'MOND', 'RAINBOW', 'RAINBOW', 'ACTIVE', 0),
(27, 'ม่อนรุ้ง 5', 'ม่อนรุ้ง 5', 'SHORT_FORM', 'th', 'MOND', 'RAINBOW', 'RAINBOW', 'ACTIVE', 0),
(28, 'SEVIOS_RED', 'sevios_red', 'SHORT_FORM', 'th', 'SEVIOS', 'RED', 'RED', 'ACTIVE', 0),
(28, 'ซีวอสแดง', 'ซีวอสแดง', 'ADMIN_ALIAS', 'th', 'SEVIOS', 'RED', 'RED', 'ACTIVE', 0),
(28, 'ซีวอสแดง1', 'ซีวอสแดง1', 'ADMIN_ALIAS', 'th', 'SEVIOS', 'RED', 'RED', 'ACTIVE', 0),
(28, 'ซีวอสแดง 1', 'ซีวอสแดง 1', 'SHORT_FORM', 'th', 'SEVIOS', 'RED', 'RED', 'ACTIVE', 0),
(28, 'ซีวอสแดง2', 'ซีวอสแดง2', 'ADMIN_ALIAS', 'th', 'SEVIOS', 'RED', 'RED', 'ACTIVE', 0),
(28, 'ซีวอสแดง 2', 'ซีวอสแดง 2', 'SHORT_FORM', 'th', 'SEVIOS', 'RED', 'RED', 'ACTIVE', 0),
(28, 'ซีวอสแดง3', 'ซีวอสแดง3', 'ADMIN_ALIAS', 'th', 'SEVIOS', 'RED', 'RED', 'ACTIVE', 0),
(28, 'ซีวอสแดง 3', 'ซีวอสแดง 3', 'SHORT_FORM', 'th', 'SEVIOS', 'RED', 'RED', 'ACTIVE', 0),
(28, 'ซีวอสแดง4', 'ซีวอสแดง4', 'ADMIN_ALIAS', 'th', 'SEVIOS', 'RED', 'RED', 'ACTIVE', 0),
(28, 'ซีวอสแดง 4', 'ซีวอสแดง 4', 'SHORT_FORM', 'th', 'SEVIOS', 'RED', 'RED', 'ACTIVE', 0),
(28, 'ซีวอสแดง5', 'ซีวอสแดง5', 'ADMIN_ALIAS', 'th', 'SEVIOS', 'RED', 'RED', 'ACTIVE', 0),
(28, 'ซีวอสแดง 5', 'ซีวอสแดง 5', 'SHORT_FORM', 'th', 'SEVIOS', 'RED', 'RED', 'ACTIVE', 0),
(29, 'เซียร่า', 'เซียร่า', 'ADMIN_ALIAS', 'th', 'SIERRA', 'RED', 'RED', 'ACTIVE', 0),
(29, 'เซียร่า1', 'เซียร่า1', 'ADMIN_ALIAS', 'th', 'SIERRA', 'RED', 'RED', 'ACTIVE', 0),
(29, 'เซียร่า 1', 'เซียร่า 1', 'SHORT_FORM', 'th', 'SIERRA', 'RED', 'RED', 'ACTIVE', 0),
(29, 'เซียร่า2', 'เซียร่า2', 'ADMIN_ALIAS', 'th', 'SIERRA', 'RED', 'RED', 'ACTIVE', 0),
(29, 'เซียร่า 2', 'เซียร่า 2', 'SHORT_FORM', 'th', 'SIERRA', 'RED', 'RED', 'ACTIVE', 0),
(29, 'เซียร่า3', 'เซียร่า3', 'ADMIN_ALIAS', 'th', 'SIERRA', 'RED', 'RED', 'ACTIVE', 0),
(29, 'เซียร่า 3', 'เซียร่า 3', 'SHORT_FORM', 'th', 'SIERRA', 'RED', 'RED', 'ACTIVE', 0),
(29, 'เซียร่า4', 'เซียร่า4', 'ADMIN_ALIAS', 'th', 'SIERRA', 'RED', 'RED', 'ACTIVE', 0),
(29, 'เซียร่า 4', 'เซียร่า 4', 'SHORT_FORM', 'th', 'SIERRA', 'RED', 'RED', 'ACTIVE', 0),
(29, 'เซียร่า5', 'เซียร่า5', 'ADMIN_ALIAS', 'th', 'SIERRA', 'RED', 'RED', 'ACTIVE', 0),
(29, 'เซียร่า 5', 'เซียร่า 5', 'SHORT_FORM', 'th', 'SIERRA', 'RED', 'RED', 'ACTIVE', 0),
(30, 'ม่อนทอง', 'ม่อนทอง', 'ADMIN_ALIAS', 'th', 'MOND', 'GOLD', 'GOLD', 'ACTIVE', 0),
(30, 'ม่อนทอง1', 'ม่อนทอง1', 'ADMIN_ALIAS', 'th', 'MOND', 'GOLD', 'GOLD', 'ACTIVE', 0),
(30, 'ม่อนทอง 1', 'ม่อนทอง 1', 'SHORT_FORM', 'th', 'MOND', 'GOLD', 'GOLD', 'ACTIVE', 0),
(30, 'ม่อนทอง2', 'ม่อนทอง2', 'ADMIN_ALIAS', 'th', 'MOND', 'GOLD', 'GOLD', 'ACTIVE', 0),
(30, 'ม่อนทอง 2', 'ม่อนทอง 2', 'SHORT_FORM', 'th', 'MOND', 'GOLD', 'GOLD', 'ACTIVE', 0),
(30, 'ม่อนทอง3', 'ม่อนทอง3', 'ADMIN_ALIAS', 'th', 'MOND', 'GOLD', 'GOLD', 'ACTIVE', 0),
(30, 'ม่อนทอง 3', 'ม่อนทอง 3', 'SHORT_FORM', 'th', 'MOND', 'GOLD', 'GOLD', 'ACTIVE', 0),
(30, 'ม่อนทอง4', 'ม่อนทอง4', 'ADMIN_ALIAS', 'th', 'MOND', 'GOLD', 'GOLD', 'ACTIVE', 0),
(30, 'ม่อนทอง 4', 'ม่อนทอง 4', 'SHORT_FORM', 'th', 'MOND', 'GOLD', 'GOLD', 'ACTIVE', 0),
(30, 'ม่อนทอง5', 'ม่อนทอง5', 'ADMIN_ALIAS', 'th', 'MOND', 'GOLD', 'GOLD', 'ACTIVE', 0),
(30, 'ม่อนทอง 5', 'ม่อนทอง 5', 'SHORT_FORM', 'th', 'MOND', 'GOLD', 'GOLD', 'ACTIVE', 0),
(30, 'MOND Signature Gold', 'mond signature gold', 'SHORT_FORM', 'th', 'MOND', 'GOLD', 'GOLD', 'ACTIVE', 0),
(30, '🔴 MOND Signature Gold', '🔴 mond signature gold', 'SHORT_FORM', 'th', 'MOND', 'GOLD', 'GOLD', 'ACTIVE', 0),
(31, 'เวสทอง', 'เวสทอง', 'ADMIN_ALIAS', 'th', 'VESS', 'GOLD', 'GOLD', 'ACTIVE', 0),
(31, 'เวสทอง1', 'เวสทอง1', 'ADMIN_ALIAS', 'th', 'VESS', 'GOLD', 'GOLD', 'ACTIVE', 0),
(31, 'เวสทอง 1', 'เวสทอง 1', 'SHORT_FORM', 'th', 'VESS', 'GOLD', 'GOLD', 'ACTIVE', 0),
(31, 'เวสทอง2', 'เวสทอง2', 'ADMIN_ALIAS', 'th', 'VESS', 'GOLD', 'GOLD', 'ACTIVE', 0),
(31, 'เวสทอง 2', 'เวสทอง 2', 'SHORT_FORM', 'th', 'VESS', 'GOLD', 'GOLD', 'ACTIVE', 0),
(31, 'เวสทอง3', 'เวสทอง3', 'ADMIN_ALIAS', 'th', 'VESS', 'GOLD', 'GOLD', 'ACTIVE', 0),
(31, 'เวสทอง 3', 'เวสทอง 3', 'SHORT_FORM', 'th', 'VESS', 'GOLD', 'GOLD', 'ACTIVE', 0),
(31, 'เวสทอง4', 'เวสทอง4', 'ADMIN_ALIAS', 'th', 'VESS', 'GOLD', 'GOLD', 'ACTIVE', 0),
(31, 'เวสทอง 4', 'เวสทอง 4', 'SHORT_FORM', 'th', 'VESS', 'GOLD', 'GOLD', 'ACTIVE', 0),
(31, 'เวสทอง5', 'เวสทอง5', 'ADMIN_ALIAS', 'th', 'VESS', 'GOLD', 'GOLD', 'ACTIVE', 0),
(31, 'เวสทอง 5', 'เวสทอง 5', 'SHORT_FORM', 'th', 'VESS', 'GOLD', 'GOLD', 'ACTIVE', 0),
(32, 'มิลาโน่ทอง', 'มิลาโน่ทอง', 'ADMIN_ALIAS', 'th', 'MILANO', 'GOLD', 'GOLD', 'ACTIVE', 0),
(32, 'มิลาโน่ทอง1', 'มิลาโน่ทอง1', 'ADMIN_ALIAS', 'th', 'MILANO', 'GOLD', 'GOLD', 'ACTIVE', 0),
(32, 'มิลาโน่ทอง 1', 'มิลาโน่ทอง 1', 'SHORT_FORM', 'th', 'MILANO', 'GOLD', 'GOLD', 'ACTIVE', 0),
(32, 'มิลาโน่ทอง2', 'มิลาโน่ทอง2', 'ADMIN_ALIAS', 'th', 'MILANO', 'GOLD', 'GOLD', 'ACTIVE', 0),
(32, 'มิลาโน่ทอง 2', 'มิลาโน่ทอง 2', 'SHORT_FORM', 'th', 'MILANO', 'GOLD', 'GOLD', 'ACTIVE', 0),
(32, 'มิลาโน่ทอง3', 'มิลาโน่ทอง3', 'ADMIN_ALIAS', 'th', 'MILANO', 'GOLD', 'GOLD', 'ACTIVE', 0),
(32, 'มิลาโน่ทอง 3', 'มิลาโน่ทอง 3', 'SHORT_FORM', 'th', 'MILANO', 'GOLD', 'GOLD', 'ACTIVE', 0),
(32, 'มิลาโน่ทอง4', 'มิลาโน่ทอง4', 'ADMIN_ALIAS', 'th', 'MILANO', 'GOLD', 'GOLD', 'ACTIVE', 0),
(32, 'มิลาโน่ทอง 4', 'มิลาโน่ทอง 4', 'SHORT_FORM', 'th', 'MILANO', 'GOLD', 'GOLD', 'ACTIVE', 0),
(32, 'มิลาโน่ทอง5', 'มิลาโน่ทอง5', 'ADMIN_ALIAS', 'th', 'MILANO', 'GOLD', 'GOLD', 'ACTIVE', 0),
(32, 'มิลาโน่ทอง 5', 'มิลาโน่ทอง 5', 'SHORT_FORM', 'th', 'MILANO', 'GOLD', 'GOLD', 'ACTIVE', 0),
(33, 'คาแดง', 'คาแดง', 'ADMIN_ALIAS', 'th', 'CAVALLO', 'RED', 'RED', 'ACTIVE', 0),
(33, 'CAVALLO_RED', 'cavallo_red', 'SHORT_FORM', 'th', 'CAVALLO', 'RED', 'RED', 'ACTIVE', 0),
(34, 'มิลาโน่คิง', 'มิลาโน่คิง', 'ADMIN_ALIAS', 'th', 'MILANO', 'KINGS', 'KINGS', 'ACTIVE', 0),
(34, 'มิลาโน่คิง1', 'มิลาโน่คิง1', 'ADMIN_ALIAS', 'th', 'MILANO', 'KINGS', 'KINGS', 'ACTIVE', 0),
(34, 'มิลาโน่คิง 1', 'มิลาโน่คิง 1', 'SHORT_FORM', 'th', 'MILANO', 'KINGS', 'KINGS', 'ACTIVE', 0),
(34, 'มิลาโน่คิง2', 'มิลาโน่คิง2', 'ADMIN_ALIAS', 'th', 'MILANO', 'KINGS', 'KINGS', 'ACTIVE', 0),
(34, 'มิลาโน่คิง 2', 'มิลาโน่คิง 2', 'SHORT_FORM', 'th', 'MILANO', 'KINGS', 'KINGS', 'ACTIVE', 0),
(34, 'มิลาโน่คิง3', 'มิลาโน่คิง3', 'ADMIN_ALIAS', 'th', 'MILANO', 'KINGS', 'KINGS', 'ACTIVE', 0),
(34, 'มิลาโน่คิง 3', 'มิลาโน่คิง 3', 'SHORT_FORM', 'th', 'MILANO', 'KINGS', 'KINGS', 'ACTIVE', 0),
(34, 'มิลาโน่คิง4', 'มิลาโน่คิง4', 'ADMIN_ALIAS', 'th', 'MILANO', 'KINGS', 'KINGS', 'ACTIVE', 0),
(34, 'มิลาโน่คิง 4', 'มิลาโน่คิง 4', 'SHORT_FORM', 'th', 'MILANO', 'KINGS', 'KINGS', 'ACTIVE', 0),
(34, 'มิลาโน่คิง5', 'มิลาโน่คิง5', 'ADMIN_ALIAS', 'th', 'MILANO', 'KINGS', 'KINGS', 'ACTIVE', 0),
(34, 'มิลาโน่คิง 5', 'มิลาโน่คิง 5', 'SHORT_FORM', 'th', 'MILANO', 'KINGS', 'KINGS', 'ACTIVE', 0),
(35, 'แพตตินั่มดำ', 'แพตตินั่มดำ', 'ADMIN_ALIAS', 'th', 'PLATINUM', 'BLACK', 'BLACK', 'ACTIVE', 0),
(35, 'แพตตินั่มดำ1', 'แพตตินั่มดำ1', 'ADMIN_ALIAS', 'th', 'PLATINUM', 'BLACK', 'BLACK', 'ACTIVE', 0),
(35, 'แพตตินั่มดำ 1', 'แพตตินั่มดำ 1', 'SHORT_FORM', 'th', 'PLATINUM', 'BLACK', 'BLACK', 'ACTIVE', 0),
(35, 'แพตตินั่มดำ2', 'แพตตินั่มดำ2', 'ADMIN_ALIAS', 'th', 'PLATINUM', 'BLACK', 'BLACK', 'ACTIVE', 0),
(35, 'แพตตินั่มดำ 2', 'แพตตินั่มดำ 2', 'SHORT_FORM', 'th', 'PLATINUM', 'BLACK', 'BLACK', 'ACTIVE', 0),
(35, 'แพตตินั่มดำ3', 'แพตตินั่มดำ3', 'ADMIN_ALIAS', 'th', 'PLATINUM', 'BLACK', 'BLACK', 'ACTIVE', 0),
(35, 'แพตตินั่มดำ 3', 'แพตตินั่มดำ 3', 'SHORT_FORM', 'th', 'PLATINUM', 'BLACK', 'BLACK', 'ACTIVE', 0),
(35, 'แพตตินั่มดำ4', 'แพตตินั่มดำ4', 'ADMIN_ALIAS', 'th', 'PLATINUM', 'BLACK', 'BLACK', 'ACTIVE', 0),
(35, 'แพตตินั่มดำ 4', 'แพตตินั่มดำ 4', 'SHORT_FORM', 'th', 'PLATINUM', 'BLACK', 'BLACK', 'ACTIVE', 0),
(35, 'แพตตินั่มดำ5', 'แพตตินั่มดำ5', 'ADMIN_ALIAS', 'th', 'PLATINUM', 'BLACK', 'BLACK', 'ACTIVE', 0),
(35, 'แพตตินั่มดำ 5', 'แพตตินั่มดำ 5', 'SHORT_FORM', 'th', 'PLATINUM', 'BLACK', 'BLACK', 'ACTIVE', 0),
(36, 'โกเม้าแดงขาว', 'โกเม้าแดงขาว', 'ADMIN_ALIAS', 'th', 'GOLD MOUNT', 'MOUNT', 'RED_WHITE', 'ACTIVE', 0),
(36, 'โกเม้าแดงขาว1', 'โกเม้าแดงขาว1', 'ADMIN_ALIAS', 'th', 'GOLD MOUNT', 'MOUNT', 'RED_WHITE', 'ACTIVE', 0),
(36, 'โกเม้าแดงขาว 1', 'โกเม้าแดงขาว 1', 'SHORT_FORM', 'th', 'GOLD MOUNT', 'MOUNT', 'RED_WHITE', 'ACTIVE', 0),
(36, 'โกเม้าแดงขาว2', 'โกเม้าแดงขาว2', 'ADMIN_ALIAS', 'th', 'GOLD MOUNT', 'MOUNT', 'RED_WHITE', 'ACTIVE', 0),
(36, 'โกเม้าแดงขาว 2', 'โกเม้าแดงขาว 2', 'SHORT_FORM', 'th', 'GOLD MOUNT', 'MOUNT', 'RED_WHITE', 'ACTIVE', 0),
(36, 'โกเม้าแดงขาว3', 'โกเม้าแดงขาว3', 'ADMIN_ALIAS', 'th', 'GOLD MOUNT', 'MOUNT', 'RED_WHITE', 'ACTIVE', 0),
(36, 'โกเม้าแดงขาว 3', 'โกเม้าแดงขาว 3', 'SHORT_FORM', 'th', 'GOLD MOUNT', 'MOUNT', 'RED_WHITE', 'ACTIVE', 0)
ON CONFLICT (alias_norm) DO UPDATE SET
  alias_text = EXCLUDED.alias_text,
  product_id = EXCLUDED.product_id,
  alias_type = EXCLUDED.alias_type,
  brand_hint = EXCLUDED.brand_hint,
  category_hint = EXCLUDED.category_hint,
  variant_hint = EXCLUDED.variant_hint,
  status = EXCLUDED.status,
  updated_at = now();

INSERT INTO public.product_aliases (product_id, alias_text, alias_norm, alias_type, language_code, brand_hint, category_hint, variant_hint, status, usage_count)
VALUES
(36, 'โกเม้าแดงขาว4', 'โกเม้าแดงขาว4', 'ADMIN_ALIAS', 'th', 'GOLD MOUNT', 'MOUNT', 'RED_WHITE', 'ACTIVE', 0),
(36, 'โกเม้าแดงขาว 4', 'โกเม้าแดงขาว 4', 'SHORT_FORM', 'th', 'GOLD MOUNT', 'MOUNT', 'RED_WHITE', 'ACTIVE', 0),
(36, 'โกเม้าแดงขาว5', 'โกเม้าแดงขาว5', 'ADMIN_ALIAS', 'th', 'GOLD MOUNT', 'MOUNT', 'RED_WHITE', 'ACTIVE', 0),
(36, 'โกเม้าแดงขาว 5', 'โกเม้าแดงขาว 5', 'SHORT_FORM', 'th', 'GOLD MOUNT', 'MOUNT', 'RED_WHITE', 'ACTIVE', 0),
(37, 'วอลตันแดง', 'วอลตันแดง', 'ADMIN_ALIAS', 'th', 'WALTON', 'RED', 'RED', 'ACTIVE', 0),
(37, 'วอลตันแดง1', 'วอลตันแดง1', 'ADMIN_ALIAS', 'th', 'WALTON', 'RED', 'RED', 'ACTIVE', 0),
(37, 'วอลตันแดง 1', 'วอลตันแดง 1', 'SHORT_FORM', 'th', 'WALTON', 'RED', 'RED', 'ACTIVE', 0),
(37, 'วอลตันแดง2', 'วอลตันแดง2', 'ADMIN_ALIAS', 'th', 'WALTON', 'RED', 'RED', 'ACTIVE', 0),
(37, 'วอลตันแดง 2', 'วอลตันแดง 2', 'SHORT_FORM', 'th', 'WALTON', 'RED', 'RED', 'ACTIVE', 0),
(37, 'วอลตันแดง3', 'วอลตันแดง3', 'ADMIN_ALIAS', 'th', 'WALTON', 'RED', 'RED', 'ACTIVE', 0),
(37, 'วอลตันแดง 3', 'วอลตันแดง 3', 'SHORT_FORM', 'th', 'WALTON', 'RED', 'RED', 'ACTIVE', 0),
(37, 'วอลตันแดง4', 'วอลตันแดง4', 'ADMIN_ALIAS', 'th', 'WALTON', 'RED', 'RED', 'ACTIVE', 0),
(37, 'วอลตันแดง 4', 'วอลตันแดง 4', 'SHORT_FORM', 'th', 'WALTON', 'RED', 'RED', 'ACTIVE', 0),
(37, 'วอลตันแดง5', 'วอลตันแดง5', 'ADMIN_ALIAS', 'th', 'WALTON', 'RED', 'RED', 'ACTIVE', 0),
(37, 'วอลตันแดง 5', 'วอลตันแดง 5', 'SHORT_FORM', 'th', 'WALTON', 'RED', 'RED', 'ACTIVE', 0),
(38, 'วอคดำ', 'วอคดำ', 'ADMIN_ALIAS', 'th', 'VOXX', 'BLACK', 'BLACK', 'ACTIVE', 0),
(38, 'วอคดำ1', 'วอคดำ1', 'ADMIN_ALIAS', 'th', 'VOXX', 'BLACK', 'BLACK', 'ACTIVE', 0),
(38, 'วอคดำ 1', 'วอคดำ 1', 'SHORT_FORM', 'th', 'VOXX', 'BLACK', 'BLACK', 'ACTIVE', 0),
(38, 'วอคดำ2', 'วอคดำ2', 'ADMIN_ALIAS', 'th', 'VOXX', 'BLACK', 'BLACK', 'ACTIVE', 0),
(38, 'วอคดำ 2', 'วอคดำ 2', 'SHORT_FORM', 'th', 'VOXX', 'BLACK', 'BLACK', 'ACTIVE', 0),
(38, 'วอคดำ3', 'วอคดำ3', 'ADMIN_ALIAS', 'th', 'VOXX', 'BLACK', 'BLACK', 'ACTIVE', 0),
(38, 'วอคดำ 3', 'วอคดำ 3', 'SHORT_FORM', 'th', 'VOXX', 'BLACK', 'BLACK', 'ACTIVE', 0),
(38, 'วอคดำ4', 'วอคดำ4', 'ADMIN_ALIAS', 'th', 'VOXX', 'BLACK', 'BLACK', 'ACTIVE', 0),
(38, 'วอคดำ 4', 'วอคดำ 4', 'SHORT_FORM', 'th', 'VOXX', 'BLACK', 'BLACK', 'ACTIVE', 0),
(38, 'วอคดำ5', 'วอคดำ5', 'ADMIN_ALIAS', 'th', 'VOXX', 'BLACK', 'BLACK', 'ACTIVE', 0),
(38, 'วอคดำ 5', 'วอคดำ 5', 'SHORT_FORM', 'th', 'VOXX', 'BLACK', 'BLACK', 'ACTIVE', 0),
(39, 'เท็กซัสทอง', 'เท็กซัสทอง', 'ADMIN_ALIAS', 'th', 'TEXAS', 'GOLD', 'GOLD', 'ACTIVE', 0),
(39, 'เท็กซัสทอง1', 'เท็กซัสทอง1', 'ADMIN_ALIAS', 'th', 'TEXAS', 'GOLD', 'GOLD', 'ACTIVE', 0),
(39, 'เท็กซัสทอง 1', 'เท็กซัสทอง 1', 'SHORT_FORM', 'th', 'TEXAS', 'GOLD', 'GOLD', 'ACTIVE', 0),
(39, 'เท็กซัสทอง2', 'เท็กซัสทอง2', 'ADMIN_ALIAS', 'th', 'TEXAS', 'GOLD', 'GOLD', 'ACTIVE', 0),
(39, 'เท็กซัสทอง 2', 'เท็กซัสทอง 2', 'SHORT_FORM', 'th', 'TEXAS', 'GOLD', 'GOLD', 'ACTIVE', 0),
(39, 'เท็กซัสทอง3', 'เท็กซัสทอง3', 'ADMIN_ALIAS', 'th', 'TEXAS', 'GOLD', 'GOLD', 'ACTIVE', 0),
(39, 'เท็กซัสทอง 3', 'เท็กซัสทอง 3', 'SHORT_FORM', 'th', 'TEXAS', 'GOLD', 'GOLD', 'ACTIVE', 0),
(39, 'เท็กซัสทอง4', 'เท็กซัสทอง4', 'ADMIN_ALIAS', 'th', 'TEXAS', 'GOLD', 'GOLD', 'ACTIVE', 0),
(39, 'เท็กซัสทอง 4', 'เท็กซัสทอง 4', 'SHORT_FORM', 'th', 'TEXAS', 'GOLD', 'GOLD', 'ACTIVE', 0),
(39, 'เท็กซัสทอง5', 'เท็กซัสทอง5', 'ADMIN_ALIAS', 'th', 'TEXAS', 'GOLD', 'GOLD', 'ACTIVE', 0),
(39, 'เท็กซัสทอง 5', 'เท็กซัสทอง 5', 'SHORT_FORM', 'th', 'TEXAS', 'GOLD', 'GOLD', 'ACTIVE', 0),
(40, 'จอนแข็ง', 'จอนแข็ง', 'ADMIN_ALIAS', 'th', 'JOHN', 'RED', 'RED', 'ACTIVE', 0),
(40, 'จอนแข็ง1', 'จอนแข็ง1', 'ADMIN_ALIAS', 'th', 'JOHN', 'RED', 'RED', 'ACTIVE', 0),
(40, 'จอนแข็ง 1', 'จอนแข็ง 1', 'SHORT_FORM', 'th', 'JOHN', 'RED', 'RED', 'ACTIVE', 0),
(40, 'จอนแข็ง2', 'จอนแข็ง2', 'ADMIN_ALIAS', 'th', 'JOHN', 'RED', 'RED', 'ACTIVE', 0),
(40, 'จอนแข็ง 2', 'จอนแข็ง 2', 'SHORT_FORM', 'th', 'JOHN', 'RED', 'RED', 'ACTIVE', 0),
(40, 'จอนแข็ง3', 'จอนแข็ง3', 'ADMIN_ALIAS', 'th', 'JOHN', 'RED', 'RED', 'ACTIVE', 0),
(40, 'จอนแข็ง 3', 'จอนแข็ง 3', 'SHORT_FORM', 'th', 'JOHN', 'RED', 'RED', 'ACTIVE', 0),
(40, 'จอนแข็ง4', 'จอนแข็ง4', 'ADMIN_ALIAS', 'th', 'JOHN', 'RED', 'RED', 'ACTIVE', 0),
(40, 'จอนแข็ง 4', 'จอนแข็ง 4', 'SHORT_FORM', 'th', 'JOHN', 'RED', 'RED', 'ACTIVE', 0),
(40, 'จอนแข็ง5', 'จอนแข็ง5', 'ADMIN_ALIAS', 'th', 'JOHN', 'RED', 'RED', 'ACTIVE', 0),
(40, 'จอนแข็ง 5', 'จอนแข็ง 5', 'SHORT_FORM', 'th', 'JOHN', 'RED', 'RED', 'ACTIVE', 0),
(41, 'เท็กซัสแดง', 'เท็กซัสแดง', 'ADMIN_ALIAS', 'th', 'TEXAS', 'RED', 'RED', 'ACTIVE', 0),
(41, 'เท็กซัสแดง1', 'เท็กซัสแดง1', 'ADMIN_ALIAS', 'th', 'TEXAS', 'RED', 'RED', 'ACTIVE', 0),
(41, 'เท็กซัสแดง 1', 'เท็กซัสแดง 1', 'SHORT_FORM', 'th', 'TEXAS', 'RED', 'RED', 'ACTIVE', 0),
(41, 'เท็กซัสแดง2', 'เท็กซัสแดง2', 'ADMIN_ALIAS', 'th', 'TEXAS', 'RED', 'RED', 'ACTIVE', 0),
(41, 'เท็กซัสแดง 2', 'เท็กซัสแดง 2', 'SHORT_FORM', 'th', 'TEXAS', 'RED', 'RED', 'ACTIVE', 0),
(41, 'เท็กซัสแดง3', 'เท็กซัสแดง3', 'ADMIN_ALIAS', 'th', 'TEXAS', 'RED', 'RED', 'ACTIVE', 0),
(41, 'เท็กซัสแดง 3', 'เท็กซัสแดง 3', 'SHORT_FORM', 'th', 'TEXAS', 'RED', 'RED', 'ACTIVE', 0),
(41, 'เท็กซัสแดง4', 'เท็กซัสแดง4', 'ADMIN_ALIAS', 'th', 'TEXAS', 'RED', 'RED', 'ACTIVE', 0),
(41, 'เท็กซัสแดง 4', 'เท็กซัสแดง 4', 'SHORT_FORM', 'th', 'TEXAS', 'RED', 'RED', 'ACTIVE', 0),
(41, 'เท็กซัสแดง5', 'เท็กซัสแดง5', 'ADMIN_ALIAS', 'th', 'TEXAS', 'RED', 'RED', 'ACTIVE', 0),
(41, 'เท็กซัสแดง 5', 'เท็กซัสแดง 5', 'SHORT_FORM', 'th', 'TEXAS', 'RED', 'RED', 'ACTIVE', 0),
(42, 'มิลาโน่ม่วง', 'มิลาโน่ม่วง', 'ADMIN_ALIAS', 'th', 'MILANO', 'PURPLE', 'PURPLE', 'ACTIVE', 0),
(42, 'มิลาโน่ม่วง1', 'มิลาโน่ม่วง1', 'ADMIN_ALIAS', 'th', 'MILANO', 'PURPLE', 'PURPLE', 'ACTIVE', 0),
(42, 'มิลาโน่ม่วง 1', 'มิลาโน่ม่วง 1', 'SHORT_FORM', 'th', 'MILANO', 'PURPLE', 'PURPLE', 'ACTIVE', 0),
(42, 'มิลาโน่ม่วง2', 'มิลาโน่ม่วง2', 'ADMIN_ALIAS', 'th', 'MILANO', 'PURPLE', 'PURPLE', 'ACTIVE', 0),
(42, 'มิลาโน่ม่วง 2', 'มิลาโน่ม่วง 2', 'SHORT_FORM', 'th', 'MILANO', 'PURPLE', 'PURPLE', 'ACTIVE', 0),
(42, 'มิลาโน่ม่วง3', 'มิลาโน่ม่วง3', 'ADMIN_ALIAS', 'th', 'MILANO', 'PURPLE', 'PURPLE', 'ACTIVE', 0),
(42, 'มิลาโน่ม่วง 3', 'มิลาโน่ม่วง 3', 'SHORT_FORM', 'th', 'MILANO', 'PURPLE', 'PURPLE', 'ACTIVE', 0),
(42, 'มิลาโน่ม่วง4', 'มิลาโน่ม่วง4', 'ADMIN_ALIAS', 'th', 'MILANO', 'PURPLE', 'PURPLE', 'ACTIVE', 0),
(42, 'มิลาโน่ม่วง 4', 'มิลาโน่ม่วง 4', 'SHORT_FORM', 'th', 'MILANO', 'PURPLE', 'PURPLE', 'ACTIVE', 0),
(42, 'มิลาโน่ม่วง5', 'มิลาโน่ม่วง5', 'ADMIN_ALIAS', 'th', 'MILANO', 'PURPLE', 'PURPLE', 'ACTIVE', 0),
(42, 'มิลาโน่ม่วง 5', 'มิลาโน่ม่วง 5', 'SHORT_FORM', 'th', 'MILANO', 'PURPLE', 'PURPLE', 'ACTIVE', 0),
(43, 'คาวาโล่ม่วงเม็ดบีบ', 'คาวาโล่ม่วงเม็ดบีบ', 'ADMIN_ALIAS', 'th', 'CAVALLO', 'TWIN', 'X_BALL', 'ACTIVE', 0),
(43, 'คาวาโล่ม่วงเม็ดบีบ1', 'คาวาโล่ม่วงเม็ดบีบ1', 'ADMIN_ALIAS', 'th', 'CAVALLO', 'TWIN', 'X_BALL', 'ACTIVE', 0),
(43, 'คาวาโล่ม่วงเม็ดบีบ 1', 'คาวาโล่ม่วงเม็ดบีบ 1', 'SHORT_FORM', 'th', 'CAVALLO', 'TWIN', 'X_BALL', 'ACTIVE', 0),
(43, 'คาวาโล่ม่วงเม็ดบีบ2', 'คาวาโล่ม่วงเม็ดบีบ2', 'ADMIN_ALIAS', 'th', 'CAVALLO', 'TWIN', 'X_BALL', 'ACTIVE', 0),
(43, 'คาวาโล่ม่วงเม็ดบีบ 2', 'คาวาโล่ม่วงเม็ดบีบ 2', 'SHORT_FORM', 'th', 'CAVALLO', 'TWIN', 'X_BALL', 'ACTIVE', 0),
(43, 'คาวาโล่ม่วงเม็ดบีบ3', 'คาวาโล่ม่วงเม็ดบีบ3', 'ADMIN_ALIAS', 'th', 'CAVALLO', 'TWIN', 'X_BALL', 'ACTIVE', 0),
(43, 'คาวาโล่ม่วงเม็ดบีบ 3', 'คาวาโล่ม่วงเม็ดบีบ 3', 'SHORT_FORM', 'th', 'CAVALLO', 'TWIN', 'X_BALL', 'ACTIVE', 0),
(43, 'คาวาโล่ม่วงเม็ดบีบ4', 'คาวาโล่ม่วงเม็ดบีบ4', 'ADMIN_ALIAS', 'th', 'CAVALLO', 'TWIN', 'X_BALL', 'ACTIVE', 0),
(43, 'คาวาโล่ม่วงเม็ดบีบ 4', 'คาวาโล่ม่วงเม็ดบีบ 4', 'SHORT_FORM', 'th', 'CAVALLO', 'TWIN', 'X_BALL', 'ACTIVE', 0),
(43, 'คาวาโล่ม่วงเม็ดบีบ5', 'คาวาโล่ม่วงเม็ดบีบ5', 'ADMIN_ALIAS', 'th', 'CAVALLO', 'TWIN', 'X_BALL', 'ACTIVE', 0),
(43, 'คาวาโล่ม่วงเม็ดบีบ 5', 'คาวาโล่ม่วงเม็ดบีบ 5', 'SHORT_FORM', 'th', 'CAVALLO', 'TWIN', 'X_BALL', 'ACTIVE', 0),
(44, 'บารูอิซัน', 'บารูอิซัน', 'ADMIN_ALIAS', 'th', 'BAROESAN', 'BAROESAN', 'BAROESAN', 'ACTIVE', 0),
(44, 'บารูอิซัน1', 'บารูอิซัน1', 'ADMIN_ALIAS', 'th', 'BAROESAN', 'BAROESAN', 'BAROESAN', 'ACTIVE', 0),
(44, 'บารูอิซัน 1', 'บารูอิซัน 1', 'SHORT_FORM', 'th', 'BAROESAN', 'BAROESAN', 'BAROESAN', 'ACTIVE', 0),
(44, 'บารูอิซัน2', 'บารูอิซัน2', 'ADMIN_ALIAS', 'th', 'BAROESAN', 'BAROESAN', 'BAROESAN', 'ACTIVE', 0),
(44, 'บารูอิซัน 2', 'บารูอิซัน 2', 'SHORT_FORM', 'th', 'BAROESAN', 'BAROESAN', 'BAROESAN', 'ACTIVE', 0),
(44, 'บารูอิซัน3', 'บารูอิซัน3', 'ADMIN_ALIAS', 'th', 'BAROESAN', 'BAROESAN', 'BAROESAN', 'ACTIVE', 0),
(44, 'บารูอิซัน 3', 'บารูอิซัน 3', 'SHORT_FORM', 'th', 'BAROESAN', 'BAROESAN', 'BAROESAN', 'ACTIVE', 0),
(44, 'บารูอิซัน4', 'บารูอิซัน4', 'ADMIN_ALIAS', 'th', 'BAROESAN', 'BAROESAN', 'BAROESAN', 'ACTIVE', 0),
(44, 'บารูอิซัน 4', 'บารูอิซัน 4', 'SHORT_FORM', 'th', 'BAROESAN', 'BAROESAN', 'BAROESAN', 'ACTIVE', 0),
(44, 'บารูอิซัน5', 'บารูอิซัน5', 'ADMIN_ALIAS', 'th', 'BAROESAN', 'BAROESAN', 'BAROESAN', 'ACTIVE', 0),
(44, 'บารูอิซัน 5', 'บารูอิซัน 5', 'SHORT_FORM', 'th', 'BAROESAN', 'BAROESAN', 'BAROESAN', 'ACTIVE', 0),
(45, 'คาเขียว', 'คาเขียว', 'ADMIN_ALIAS', 'th', 'CAVALLO', 'GREEN', 'GREEN', 'ACTIVE', 0),
(45, 'คาวาโร่เขียว', 'คาวาโร่เขียว', 'ADMIN_ALIAS', 'th', 'CAVALLO', 'GREEN', 'GREEN', 'ACTIVE', 0),
(45, 'CAVALLO_GREEN', 'cavallo_green', 'SHORT_FORM', 'th', 'CAVALLO', 'GREEN', 'GREEN', 'ACTIVE', 0),
(45, 'CAVALLO GREEN', 'cavallo green', 'SHORT_FORM', 'th', 'CAVALLO', 'GREEN', 'GREEN', 'ACTIVE', 0),
(45, 'คาเขียว 1 คอต', 'คาเขียว 1 คอต', 'SHORT_FORM', 'th', 'CAVALLO', 'GREEN', 'GREEN', 'ACTIVE', 0),
(46, 'รอยัลเขียว', 'รอยัลเขียว', 'ADMIN_ALIAS', 'th', 'ROYAL', 'GREEN', 'GREEN', 'ACTIVE', 0),
(46, 'ROYAL ASCOT GREEN', 'royal ascot green', 'SHORT_FORM', 'th', 'ROYAL', 'GREEN', 'GREEN', 'ACTIVE', 0),
(46, 'ROYAL ASCOT GREEN MENTHOL', 'royal ascot green menthol', 'SHORT_FORM', 'th', 'ROYAL', 'GREEN', 'GREEN', 'ACTIVE', 0),
(47, '235 เขียว', '235 เขียว', 'SHORT_FORM', 'th', '235', 'GREEN', 'GREEN', 'ACTIVE', 0),
(47, '235 เขียว1', '235 เขียว1', 'SHORT_FORM', 'th', '235', 'GREEN', 'GREEN', 'ACTIVE', 0),
(47, '235 เขียว 1', '235 เขียว 1', 'SHORT_FORM', 'th', '235', 'GREEN', 'GREEN', 'ACTIVE', 0),
(47, '235 เขียว2', '235 เขียว2', 'SHORT_FORM', 'th', '235', 'GREEN', 'GREEN', 'ACTIVE', 0),
(47, '235 เขียว 2', '235 เขียว 2', 'SHORT_FORM', 'th', '235', 'GREEN', 'GREEN', 'ACTIVE', 0),
(47, '235 เขียว3', '235 เขียว3', 'SHORT_FORM', 'th', '235', 'GREEN', 'GREEN', 'ACTIVE', 0),
(47, '235 เขียว 3', '235 เขียว 3', 'SHORT_FORM', 'th', '235', 'GREEN', 'GREEN', 'ACTIVE', 0),
(47, '235 เขียว4', '235 เขียว4', 'SHORT_FORM', 'th', '235', 'GREEN', 'GREEN', 'ACTIVE', 0),
(47, '235 เขียว 4', '235 เขียว 4', 'SHORT_FORM', 'th', '235', 'GREEN', 'GREEN', 'ACTIVE', 0),
(47, '235 เขียว5', '235 เขียว5', 'SHORT_FORM', 'th', '235', 'GREEN', 'GREEN', 'ACTIVE', 0),
(47, '235 เขียว 5', '235 เขียว 5', 'SHORT_FORM', 'th', '235', 'GREEN', 'GREEN', 'ACTIVE', 0),
(48, 'แคนยอนเขียว', 'แคนยอนเขียว', 'ADMIN_ALIAS', 'th', 'CANYON', 'GREEN', 'GREEN', 'ACTIVE', 0),
(48, 'แคนยอนเขียว1', 'แคนยอนเขียว1', 'ADMIN_ALIAS', 'th', 'CANYON', 'GREEN', 'GREEN', 'ACTIVE', 0),
(48, 'แคนยอนเขียว 1', 'แคนยอนเขียว 1', 'SHORT_FORM', 'th', 'CANYON', 'GREEN', 'GREEN', 'ACTIVE', 0),
(48, 'แคนยอนเขียว2', 'แคนยอนเขียว2', 'ADMIN_ALIAS', 'th', 'CANYON', 'GREEN', 'GREEN', 'ACTIVE', 0),
(48, 'แคนยอนเขียว 2', 'แคนยอนเขียว 2', 'SHORT_FORM', 'th', 'CANYON', 'GREEN', 'GREEN', 'ACTIVE', 0),
(48, 'แคนยอนเขียว3', 'แคนยอนเขียว3', 'ADMIN_ALIAS', 'th', 'CANYON', 'GREEN', 'GREEN', 'ACTIVE', 0),
(48, 'แคนยอนเขียว 3', 'แคนยอนเขียว 3', 'SHORT_FORM', 'th', 'CANYON', 'GREEN', 'GREEN', 'ACTIVE', 0),
(48, 'แคนยอนเขียว4', 'แคนยอนเขียว4', 'ADMIN_ALIAS', 'th', 'CANYON', 'GREEN', 'GREEN', 'ACTIVE', 0),
(48, 'แคนยอนเขียว 4', 'แคนยอนเขียว 4', 'SHORT_FORM', 'th', 'CANYON', 'GREEN', 'GREEN', 'ACTIVE', 0),
(48, 'แคนยอนเขียว5', 'แคนยอนเขียว5', 'ADMIN_ALIAS', 'th', 'CANYON', 'GREEN', 'GREEN', 'ACTIVE', 0),
(48, 'แคนยอนเขียว 5', 'แคนยอนเขียว 5', 'SHORT_FORM', 'th', 'CANYON', 'GREEN', 'GREEN', 'ACTIVE', 0),
(49, 'โกเม้าเขียวล้วน', 'โกเม้าเขียวล้วน', 'ADMIN_ALIAS', 'th', 'GOLD MOUNT', 'MOUNT', 'FULL_GREEN', 'ACTIVE', 0),
(49, 'โกเม้าเขียวล้วน1', 'โกเม้าเขียวล้วน1', 'ADMIN_ALIAS', 'th', 'GOLD MOUNT', 'MOUNT', 'FULL_GREEN', 'ACTIVE', 0),
(49, 'โกเม้าเขียวล้วน 1', 'โกเม้าเขียวล้วน 1', 'SHORT_FORM', 'th', 'GOLD MOUNT', 'MOUNT', 'FULL_GREEN', 'ACTIVE', 0),
(49, 'โกเม้าเขียวล้วน2', 'โกเม้าเขียวล้วน2', 'ADMIN_ALIAS', 'th', 'GOLD MOUNT', 'MOUNT', 'FULL_GREEN', 'ACTIVE', 0),
(49, 'โกเม้าเขียวล้วน 2', 'โกเม้าเขียวล้วน 2', 'SHORT_FORM', 'th', 'GOLD MOUNT', 'MOUNT', 'FULL_GREEN', 'ACTIVE', 0),
(49, 'โกเม้าเขียวล้วน3', 'โกเม้าเขียวล้วน3', 'ADMIN_ALIAS', 'th', 'GOLD MOUNT', 'MOUNT', 'FULL_GREEN', 'ACTIVE', 0),
(49, 'โกเม้าเขียวล้วน 3', 'โกเม้าเขียวล้วน 3', 'SHORT_FORM', 'th', 'GOLD MOUNT', 'MOUNT', 'FULL_GREEN', 'ACTIVE', 0),
(49, 'โกเม้าเขียวล้วน4', 'โกเม้าเขียวล้วน4', 'ADMIN_ALIAS', 'th', 'GOLD MOUNT', 'MOUNT', 'FULL_GREEN', 'ACTIVE', 0),
(49, 'โกเม้าเขียวล้วน 4', 'โกเม้าเขียวล้วน 4', 'SHORT_FORM', 'th', 'GOLD MOUNT', 'MOUNT', 'FULL_GREEN', 'ACTIVE', 0),
(49, 'โกเม้าเขียวล้วน5', 'โกเม้าเขียวล้วน5', 'ADMIN_ALIAS', 'th', 'GOLD MOUNT', 'MOUNT', 'FULL_GREEN', 'ACTIVE', 0),
(49, 'โกเม้าเขียวล้วน 5', 'โกเม้าเขียวล้วน 5', 'SHORT_FORM', 'th', 'GOLD MOUNT', 'MOUNT', 'FULL_GREEN', 'ACTIVE', 0),
(50, 'แอลเอ็มเขียว', 'แอลเอ็มเขียว', 'ADMIN_ALIAS', 'th', 'L&M', 'GREEN', 'GREEN', 'ACTIVE', 0),
(50, 'LM เขียว', 'lm เขียว', 'SHORT_FORM', 'th', 'L&M', 'GREEN', 'GREEN', 'ACTIVE', 0),
(50, 'L&M_GREEN', 'l&m_green', 'SHORT_FORM', 'th', 'L&M', 'GREEN', 'GREEN', 'ACTIVE', 0),
(51, 'มาโบโร่เขียว', 'มาโบโร่เขียว', 'ADMIN_ALIAS', 'th', 'MARLBORO', 'MENTHOL', 'MENTHOL', 'ACTIVE', 0),
(51, 'มาโบโร่เขียว1', 'มาโบโร่เขียว1', 'ADMIN_ALIAS', 'th', 'MARLBORO', 'MENTHOL', 'MENTHOL', 'ACTIVE', 0),
(51, 'มาโบโร่เขียว 1', 'มาโบโร่เขียว 1', 'SHORT_FORM', 'th', 'MARLBORO', 'MENTHOL', 'MENTHOL', 'ACTIVE', 0),
(51, 'มาโบโร่เขียว2', 'มาโบโร่เขียว2', 'ADMIN_ALIAS', 'th', 'MARLBORO', 'MENTHOL', 'MENTHOL', 'ACTIVE', 0),
(51, 'มาโบโร่เขียว 2', 'มาโบโร่เขียว 2', 'SHORT_FORM', 'th', 'MARLBORO', 'MENTHOL', 'MENTHOL', 'ACTIVE', 0),
(51, 'มาโบโร่เขียว3', 'มาโบโร่เขียว3', 'ADMIN_ALIAS', 'th', 'MARLBORO', 'MENTHOL', 'MENTHOL', 'ACTIVE', 0),
(51, 'มาโบโร่เขียว 3', 'มาโบโร่เขียว 3', 'SHORT_FORM', 'th', 'MARLBORO', 'MENTHOL', 'MENTHOL', 'ACTIVE', 0),
(51, 'มาโบโร่เขียว4', 'มาโบโร่เขียว4', 'ADMIN_ALIAS', 'th', 'MARLBORO', 'MENTHOL', 'MENTHOL', 'ACTIVE', 0),
(51, 'มาโบโร่เขียว 4', 'มาโบโร่เขียว 4', 'SHORT_FORM', 'th', 'MARLBORO', 'MENTHOL', 'MENTHOL', 'ACTIVE', 0),
(51, 'มาโบโร่เขียว5', 'มาโบโร่เขียว5', 'ADMIN_ALIAS', 'th', 'MARLBORO', 'MENTHOL', 'MENTHOL', 'ACTIVE', 0),
(51, 'มาโบโร่เขียว 5', 'มาโบโร่เขียว 5', 'SHORT_FORM', 'th', 'MARLBORO', 'MENTHOL', 'MENTHOL', 'ACTIVE', 0),
(52, 'วอลตันเขียว', 'วอลตันเขียว', 'ADMIN_ALIAS', 'th', 'WALTON', 'GREEN', 'GREEN', 'ACTIVE', 0),
(52, 'วอลตันเขียว1', 'วอลตันเขียว1', 'ADMIN_ALIAS', 'th', 'WALTON', 'GREEN', 'GREEN', 'ACTIVE', 0),
(52, 'วอลตันเขียว 1', 'วอลตันเขียว 1', 'SHORT_FORM', 'th', 'WALTON', 'GREEN', 'GREEN', 'ACTIVE', 0),
(52, 'วอลตันเขียว2', 'วอลตันเขียว2', 'ADMIN_ALIAS', 'th', 'WALTON', 'GREEN', 'GREEN', 'ACTIVE', 0),
(52, 'วอลตันเขียว 2', 'วอลตันเขียว 2', 'SHORT_FORM', 'th', 'WALTON', 'GREEN', 'GREEN', 'ACTIVE', 0),
(52, 'วอลตันเขียว3', 'วอลตันเขียว3', 'ADMIN_ALIAS', 'th', 'WALTON', 'GREEN', 'GREEN', 'ACTIVE', 0),
(52, 'วอลตันเขียว 3', 'วอลตันเขียว 3', 'SHORT_FORM', 'th', 'WALTON', 'GREEN', 'GREEN', 'ACTIVE', 0),
(52, 'วอลตันเขียว4', 'วอลตันเขียว4', 'ADMIN_ALIAS', 'th', 'WALTON', 'GREEN', 'GREEN', 'ACTIVE', 0),
(52, 'วอลตันเขียว 4', 'วอลตันเขียว 4', 'SHORT_FORM', 'th', 'WALTON', 'GREEN', 'GREEN', 'ACTIVE', 0),
(52, 'วอลตันเขียว5', 'วอลตันเขียว5', 'ADMIN_ALIAS', 'th', 'WALTON', 'GREEN', 'GREEN', 'ACTIVE', 0),
(52, 'วอลตันเขียว 5', 'วอลตันเขียว 5', 'SHORT_FORM', 'th', 'WALTON', 'GREEN', 'GREEN', 'ACTIVE', 0),
(53, 'แคปปิตอลฟ้า', 'แคปปิตอลฟ้า', 'ADMIN_ALIAS', 'th', 'CAPITAL', 'BLUE', 'BLUE', 'ACTIVE', 0),
(53, 'แคปปิตอลฟ้า1', 'แคปปิตอลฟ้า1', 'ADMIN_ALIAS', 'th', 'CAPITAL', 'BLUE', 'BLUE', 'ACTIVE', 0),
(53, 'แคปปิตอลฟ้า 1', 'แคปปิตอลฟ้า 1', 'SHORT_FORM', 'th', 'CAPITAL', 'BLUE', 'BLUE', 'ACTIVE', 0),
(53, 'แคปปิตอลฟ้า2', 'แคปปิตอลฟ้า2', 'ADMIN_ALIAS', 'th', 'CAPITAL', 'BLUE', 'BLUE', 'ACTIVE', 0),
(53, 'แคปปิตอลฟ้า 2', 'แคปปิตอลฟ้า 2', 'SHORT_FORM', 'th', 'CAPITAL', 'BLUE', 'BLUE', 'ACTIVE', 0),
(53, 'แคปปิตอลฟ้า3', 'แคปปิตอลฟ้า3', 'ADMIN_ALIAS', 'th', 'CAPITAL', 'BLUE', 'BLUE', 'ACTIVE', 0),
(53, 'แคปปิตอลฟ้า 3', 'แคปปิตอลฟ้า 3', 'SHORT_FORM', 'th', 'CAPITAL', 'BLUE', 'BLUE', 'ACTIVE', 0),
(53, 'แคปปิตอลฟ้า4', 'แคปปิตอลฟ้า4', 'ADMIN_ALIAS', 'th', 'CAPITAL', 'BLUE', 'BLUE', 'ACTIVE', 0),
(53, 'แคปปิตอลฟ้า 4', 'แคปปิตอลฟ้า 4', 'SHORT_FORM', 'th', 'CAPITAL', 'BLUE', 'BLUE', 'ACTIVE', 0),
(53, 'แคปปิตอลฟ้า5', 'แคปปิตอลฟ้า5', 'ADMIN_ALIAS', 'th', 'CAPITAL', 'BLUE', 'BLUE', 'ACTIVE', 0),
(53, 'แคปปิตอลฟ้า 5', 'แคปปิตอลฟ้า 5', 'SHORT_FORM', 'th', 'CAPITAL', 'BLUE', 'BLUE', 'ACTIVE', 0),
(54, 'โอริสสตรอว์เบอร์รี่', 'โอริสสตรอว์เบอร์รี่', 'ADMIN_ALIAS', 'th', 'ORIS', 'STRAWBERRY', 'STRAWBERRY', 'ACTIVE', 0),
(54, 'โอริสสตรอว์เบอร์รี่1', 'โอริสสตรอว์เบอร์รี่1', 'ADMIN_ALIAS', 'th', 'ORIS', 'STRAWBERRY', 'STRAWBERRY', 'ACTIVE', 0),
(54, 'โอริสสตรอว์เบอร์รี่ 1', 'โอริสสตรอว์เบอร์รี่ 1', 'SHORT_FORM', 'th', 'ORIS', 'STRAWBERRY', 'STRAWBERRY', 'ACTIVE', 0),
(54, 'โอริสสตรอว์เบอร์รี่2', 'โอริสสตรอว์เบอร์รี่2', 'ADMIN_ALIAS', 'th', 'ORIS', 'STRAWBERRY', 'STRAWBERRY', 'ACTIVE', 0),
(54, 'โอริสสตรอว์เบอร์รี่ 2', 'โอริสสตรอว์เบอร์รี่ 2', 'SHORT_FORM', 'th', 'ORIS', 'STRAWBERRY', 'STRAWBERRY', 'ACTIVE', 0),
(54, 'โอริสสตรอว์เบอร์รี่3', 'โอริสสตรอว์เบอร์รี่3', 'ADMIN_ALIAS', 'th', 'ORIS', 'STRAWBERRY', 'STRAWBERRY', 'ACTIVE', 0),
(54, 'โอริสสตรอว์เบอร์รี่ 3', 'โอริสสตรอว์เบอร์รี่ 3', 'SHORT_FORM', 'th', 'ORIS', 'STRAWBERRY', 'STRAWBERRY', 'ACTIVE', 0),
(54, 'โอริสสตรอว์เบอร์รี่4', 'โอริสสตรอว์เบอร์รี่4', 'ADMIN_ALIAS', 'th', 'ORIS', 'STRAWBERRY', 'STRAWBERRY', 'ACTIVE', 0),
(54, 'โอริสสตรอว์เบอร์รี่ 4', 'โอริสสตรอว์เบอร์รี่ 4', 'SHORT_FORM', 'th', 'ORIS', 'STRAWBERRY', 'STRAWBERRY', 'ACTIVE', 0),
(54, 'โอริสสตรอว์เบอร์รี่5', 'โอริสสตรอว์เบอร์รี่5', 'ADMIN_ALIAS', 'th', 'ORIS', 'STRAWBERRY', 'STRAWBERRY', 'ACTIVE', 0),
(54, 'โอริสสตรอว์เบอร์รี่ 5', 'โอริสสตรอว์เบอร์รี่ 5', 'SHORT_FORM', 'th', 'ORIS', 'STRAWBERRY', 'STRAWBERRY', 'ACTIVE', 0),
(56, 'แพลตตินั่มสตรอว์เบอร์รี่', 'แพลตตินั่มสตรอว์เบอร์รี่', 'ADMIN_ALIAS', 'th', 'PLATINUM', 'STRAWBERRY', 'STRAWBERRY', 'ACTIVE', 0),
(56, 'แพลตตินั่มสตรอว์เบอร์รี่1', 'แพลตตินั่มสตรอว์เบอร์รี่1', 'ADMIN_ALIAS', 'th', 'PLATINUM', 'STRAWBERRY', 'STRAWBERRY', 'ACTIVE', 0),
(56, 'แพลตตินั่มสตรอว์เบอร์รี่ 1', 'แพลตตินั่มสตรอว์เบอร์รี่ 1', 'SHORT_FORM', 'th', 'PLATINUM', 'STRAWBERRY', 'STRAWBERRY', 'ACTIVE', 0),
(56, 'แพลตตินั่มสตรอว์เบอร์รี่2', 'แพลตตินั่มสตรอว์เบอร์รี่2', 'ADMIN_ALIAS', 'th', 'PLATINUM', 'STRAWBERRY', 'STRAWBERRY', 'ACTIVE', 0),
(56, 'แพลตตินั่มสตรอว์เบอร์รี่ 2', 'แพลตตินั่มสตรอว์เบอร์รี่ 2', 'SHORT_FORM', 'th', 'PLATINUM', 'STRAWBERRY', 'STRAWBERRY', 'ACTIVE', 0),
(56, 'แพลตตินั่มสตรอว์เบอร์รี่3', 'แพลตตินั่มสตรอว์เบอร์รี่3', 'ADMIN_ALIAS', 'th', 'PLATINUM', 'STRAWBERRY', 'STRAWBERRY', 'ACTIVE', 0),
(56, 'แพลตตินั่มสตรอว์เบอร์รี่ 3', 'แพลตตินั่มสตรอว์เบอร์รี่ 3', 'SHORT_FORM', 'th', 'PLATINUM', 'STRAWBERRY', 'STRAWBERRY', 'ACTIVE', 0),
(56, 'แพลตตินั่มสตรอว์เบอร์รี่4', 'แพลตตินั่มสตรอว์เบอร์รี่4', 'ADMIN_ALIAS', 'th', 'PLATINUM', 'STRAWBERRY', 'STRAWBERRY', 'ACTIVE', 0),
(56, 'แพลตตินั่มสตรอว์เบอร์รี่ 4', 'แพลตตินั่มสตรอว์เบอร์รี่ 4', 'SHORT_FORM', 'th', 'PLATINUM', 'STRAWBERRY', 'STRAWBERRY', 'ACTIVE', 0),
(56, 'แพลตตินั่มสตรอว์เบอร์รี่5', 'แพลตตินั่มสตรอว์เบอร์รี่5', 'ADMIN_ALIAS', 'th', 'PLATINUM', 'STRAWBERRY', 'STRAWBERRY', 'ACTIVE', 0),
(56, 'แพลตตินั่มสตรอว์เบอร์รี่ 5', 'แพลตตินั่มสตรอว์เบอร์รี่ 5', 'SHORT_FORM', 'th', 'PLATINUM', 'STRAWBERRY', 'STRAWBERRY', 'ACTIVE', 0),
(57, 'โอริสเชอร์รี่', 'โอริสเชอร์รี่', 'ADMIN_ALIAS', 'th', 'ORIS', 'CHERRY', 'CHERRY', 'ACTIVE', 0),
(57, 'โอริสเชอร์รี่1', 'โอริสเชอร์รี่1', 'ADMIN_ALIAS', 'th', 'ORIS', 'CHERRY', 'CHERRY', 'ACTIVE', 0),
(57, 'โอริสเชอร์รี่ 1', 'โอริสเชอร์รี่ 1', 'SHORT_FORM', 'th', 'ORIS', 'CHERRY', 'CHERRY', 'ACTIVE', 0),
(57, 'โอริสเชอร์รี่2', 'โอริสเชอร์รี่2', 'ADMIN_ALIAS', 'th', 'ORIS', 'CHERRY', 'CHERRY', 'ACTIVE', 0),
(57, 'โอริสเชอร์รี่ 2', 'โอริสเชอร์รี่ 2', 'SHORT_FORM', 'th', 'ORIS', 'CHERRY', 'CHERRY', 'ACTIVE', 0),
(57, 'โอริสเชอร์รี่3', 'โอริสเชอร์รี่3', 'ADMIN_ALIAS', 'th', 'ORIS', 'CHERRY', 'CHERRY', 'ACTIVE', 0),
(57, 'โอริสเชอร์รี่ 3', 'โอริสเชอร์รี่ 3', 'SHORT_FORM', 'th', 'ORIS', 'CHERRY', 'CHERRY', 'ACTIVE', 0),
(57, 'โอริสเชอร์รี่4', 'โอริสเชอร์รี่4', 'ADMIN_ALIAS', 'th', 'ORIS', 'CHERRY', 'CHERRY', 'ACTIVE', 0),
(57, 'โอริสเชอร์รี่ 4', 'โอริสเชอร์รี่ 4', 'SHORT_FORM', 'th', 'ORIS', 'CHERRY', 'CHERRY', 'ACTIVE', 0)
ON CONFLICT (alias_norm) DO UPDATE SET
  alias_text = EXCLUDED.alias_text,
  product_id = EXCLUDED.product_id,
  alias_type = EXCLUDED.alias_type,
  brand_hint = EXCLUDED.brand_hint,
  category_hint = EXCLUDED.category_hint,
  variant_hint = EXCLUDED.variant_hint,
  status = EXCLUDED.status,
  updated_at = now();

INSERT INTO public.product_aliases (product_id, alias_text, alias_norm, alias_type, language_code, brand_hint, category_hint, variant_hint, status, usage_count)
VALUES
(57, 'โอริสเชอร์รี่5', 'โอริสเชอร์รี่5', 'ADMIN_ALIAS', 'th', 'ORIS', 'CHERRY', 'CHERRY', 'ACTIVE', 0),
(57, 'โอริสเชอร์รี่ 5', 'โอริสเชอร์รี่ 5', 'SHORT_FORM', 'th', 'ORIS', 'CHERRY', 'CHERRY', 'ACTIVE', 0),
(58, 'จอนแอปเปิ้ล 2 เม็ดบีบ', 'จอนแอปเปิ้ล 2 เม็ดบีบ', 'SHORT_FORM', 'th', 'JOHN', 'APPLE', '2CAPS', 'ACTIVE', 0),
(58, 'จอนแอปเปิ้ล 2 เม็ดบีบ1', 'จอนแอปเปิ้ล 2 เม็ดบีบ1', 'SHORT_FORM', 'th', 'JOHN', 'APPLE', '2CAPS', 'ACTIVE', 0),
(58, 'จอนแอปเปิ้ล 2 เม็ดบีบ 1', 'จอนแอปเปิ้ล 2 เม็ดบีบ 1', 'SHORT_FORM', 'th', 'JOHN', 'APPLE', '2CAPS', 'ACTIVE', 0),
(58, 'จอนแอปเปิ้ล 2 เม็ดบีบ2', 'จอนแอปเปิ้ล 2 เม็ดบีบ2', 'SHORT_FORM', 'th', 'JOHN', 'APPLE', '2CAPS', 'ACTIVE', 0),
(58, 'จอนแอปเปิ้ล 2 เม็ดบีบ 2', 'จอนแอปเปิ้ล 2 เม็ดบีบ 2', 'SHORT_FORM', 'th', 'JOHN', 'APPLE', '2CAPS', 'ACTIVE', 0),
(58, 'จอนแอปเปิ้ล 2 เม็ดบีบ3', 'จอนแอปเปิ้ล 2 เม็ดบีบ3', 'SHORT_FORM', 'th', 'JOHN', 'APPLE', '2CAPS', 'ACTIVE', 0),
(58, 'จอนแอปเปิ้ล 2 เม็ดบีบ 3', 'จอนแอปเปิ้ล 2 เม็ดบีบ 3', 'SHORT_FORM', 'th', 'JOHN', 'APPLE', '2CAPS', 'ACTIVE', 0),
(58, 'จอนแอปเปิ้ล 2 เม็ดบีบ4', 'จอนแอปเปิ้ล 2 เม็ดบีบ4', 'SHORT_FORM', 'th', 'JOHN', 'APPLE', '2CAPS', 'ACTIVE', 0),
(58, 'จอนแอปเปิ้ล 2 เม็ดบีบ 4', 'จอนแอปเปิ้ล 2 เม็ดบีบ 4', 'SHORT_FORM', 'th', 'JOHN', 'APPLE', '2CAPS', 'ACTIVE', 0),
(58, 'จอนแอปเปิ้ล 2 เม็ดบีบ5', 'จอนแอปเปิ้ล 2 เม็ดบีบ5', 'SHORT_FORM', 'th', 'JOHN', 'APPLE', '2CAPS', 'ACTIVE', 0),
(58, 'จอนแอปเปิ้ล 2 เม็ดบีบ 5', 'จอนแอปเปิ้ล 2 เม็ดบีบ 5', 'SHORT_FORM', 'th', 'JOHN', 'APPLE', '2CAPS', 'ACTIVE', 0),
(59, 'ม่อนแอปเปิ้ล', 'ม่อนแอปเปิ้ล', 'ADMIN_ALIAS', 'th', 'MOND', 'APPLE', 'FRUIT', 'ACTIVE', 0),
(59, 'ม่อนแอปเปิ้ล1', 'ม่อนแอปเปิ้ล1', 'ADMIN_ALIAS', 'th', 'MOND', 'APPLE', 'FRUIT', 'ACTIVE', 0),
(59, 'ม่อนแอปเปิ้ล 1', 'ม่อนแอปเปิ้ล 1', 'SHORT_FORM', 'th', 'MOND', 'APPLE', 'FRUIT', 'ACTIVE', 0),
(59, 'ม่อนแอปเปิ้ล2', 'ม่อนแอปเปิ้ล2', 'ADMIN_ALIAS', 'th', 'MOND', 'APPLE', 'FRUIT', 'ACTIVE', 0),
(59, 'ม่อนแอปเปิ้ล 2', 'ม่อนแอปเปิ้ล 2', 'SHORT_FORM', 'th', 'MOND', 'APPLE', 'FRUIT', 'ACTIVE', 0),
(59, 'ม่อนแอปเปิ้ล3', 'ม่อนแอปเปิ้ล3', 'ADMIN_ALIAS', 'th', 'MOND', 'APPLE', 'FRUIT', 'ACTIVE', 0),
(59, 'ม่อนแอปเปิ้ล 3', 'ม่อนแอปเปิ้ล 3', 'SHORT_FORM', 'th', 'MOND', 'APPLE', 'FRUIT', 'ACTIVE', 0),
(59, 'ม่อนแอปเปิ้ล4', 'ม่อนแอปเปิ้ล4', 'ADMIN_ALIAS', 'th', 'MOND', 'APPLE', 'FRUIT', 'ACTIVE', 0),
(59, 'ม่อนแอปเปิ้ล 4', 'ม่อนแอปเปิ้ล 4', 'SHORT_FORM', 'th', 'MOND', 'APPLE', 'FRUIT', 'ACTIVE', 0),
(59, 'ม่อนแอปเปิ้ล5', 'ม่อนแอปเปิ้ล5', 'ADMIN_ALIAS', 'th', 'MOND', 'APPLE', 'FRUIT', 'ACTIVE', 0),
(59, 'ม่อนแอปเปิ้ล 5', 'ม่อนแอปเปิ้ล 5', 'SHORT_FORM', 'th', 'MOND', 'APPLE', 'FRUIT', 'ACTIVE', 0),
(60, 'โอริสแอปเปิ้ล', 'โอริสแอปเปิ้ล', 'ADMIN_ALIAS', 'th', 'ORIS', 'APPLE', 'APPLE', 'ACTIVE', 0),
(60, 'โอริสแอปเปิ้ล1', 'โอริสแอปเปิ้ล1', 'ADMIN_ALIAS', 'th', 'ORIS', 'APPLE', 'APPLE', 'ACTIVE', 0),
(60, 'โอริสแอปเปิ้ล 1', 'โอริสแอปเปิ้ล 1', 'SHORT_FORM', 'th', 'ORIS', 'APPLE', 'APPLE', 'ACTIVE', 0),
(60, 'โอริสแอปเปิ้ล2', 'โอริสแอปเปิ้ล2', 'ADMIN_ALIAS', 'th', 'ORIS', 'APPLE', 'APPLE', 'ACTIVE', 0),
(60, 'โอริสแอปเปิ้ล 2', 'โอริสแอปเปิ้ล 2', 'SHORT_FORM', 'th', 'ORIS', 'APPLE', 'APPLE', 'ACTIVE', 0),
(60, 'โอริสแอปเปิ้ล3', 'โอริสแอปเปิ้ล3', 'ADMIN_ALIAS', 'th', 'ORIS', 'APPLE', 'APPLE', 'ACTIVE', 0),
(60, 'โอริสแอปเปิ้ล 3', 'โอริสแอปเปิ้ล 3', 'SHORT_FORM', 'th', 'ORIS', 'APPLE', 'APPLE', 'ACTIVE', 0),
(60, 'โอริสแอปเปิ้ล4', 'โอริสแอปเปิ้ล4', 'ADMIN_ALIAS', 'th', 'ORIS', 'APPLE', 'APPLE', 'ACTIVE', 0),
(60, 'โอริสแอปเปิ้ล 4', 'โอริสแอปเปิ้ล 4', 'SHORT_FORM', 'th', 'ORIS', 'APPLE', 'APPLE', 'ACTIVE', 0),
(60, 'โอริสแอปเปิ้ล5', 'โอริสแอปเปิ้ล5', 'ADMIN_ALIAS', 'th', 'ORIS', 'APPLE', 'APPLE', 'ACTIVE', 0),
(60, 'โอริสแอปเปิ้ล 5', 'โอริสแอปเปิ้ล 5', 'SHORT_FORM', 'th', 'ORIS', 'APPLE', 'APPLE', 'ACTIVE', 0),
(61, 'แพลตตินั่มแอปเปิ้ล', 'แพลตตินั่มแอปเปิ้ล', 'ADMIN_ALIAS', 'th', 'PLATINUM', 'APPLE', 'APPLE', 'ACTIVE', 0),
(61, 'แพลตตินั่มแอปเปิ้ล1', 'แพลตตินั่มแอปเปิ้ล1', 'ADMIN_ALIAS', 'th', 'PLATINUM', 'APPLE', 'APPLE', 'ACTIVE', 0),
(61, 'แพลตตินั่มแอปเปิ้ล 1', 'แพลตตินั่มแอปเปิ้ล 1', 'SHORT_FORM', 'th', 'PLATINUM', 'APPLE', 'APPLE', 'ACTIVE', 0),
(61, 'แพลตตินั่มแอปเปิ้ล2', 'แพลตตินั่มแอปเปิ้ล2', 'ADMIN_ALIAS', 'th', 'PLATINUM', 'APPLE', 'APPLE', 'ACTIVE', 0),
(61, 'แพลตตินั่มแอปเปิ้ล 2', 'แพลตตินั่มแอปเปิ้ล 2', 'SHORT_FORM', 'th', 'PLATINUM', 'APPLE', 'APPLE', 'ACTIVE', 0),
(61, 'แพลตตินั่มแอปเปิ้ล3', 'แพลตตินั่มแอปเปิ้ล3', 'ADMIN_ALIAS', 'th', 'PLATINUM', 'APPLE', 'APPLE', 'ACTIVE', 0),
(61, 'แพลตตินั่มแอปเปิ้ล 3', 'แพลตตินั่มแอปเปิ้ล 3', 'SHORT_FORM', 'th', 'PLATINUM', 'APPLE', 'APPLE', 'ACTIVE', 0),
(61, 'แพลตตินั่มแอปเปิ้ล4', 'แพลตตินั่มแอปเปิ้ล4', 'ADMIN_ALIAS', 'th', 'PLATINUM', 'APPLE', 'APPLE', 'ACTIVE', 0),
(61, 'แพลตตินั่มแอปเปิ้ล 4', 'แพลตตินั่มแอปเปิ้ล 4', 'SHORT_FORM', 'th', 'PLATINUM', 'APPLE', 'APPLE', 'ACTIVE', 0),
(61, 'แพลตตินั่มแอปเปิ้ล5', 'แพลตตินั่มแอปเปิ้ล5', 'ADMIN_ALIAS', 'th', 'PLATINUM', 'APPLE', 'APPLE', 'ACTIVE', 0),
(61, 'แพลตตินั่มแอปเปิ้ล 5', 'แพลตตินั่มแอปเปิ้ล 5', 'SHORT_FORM', 'th', 'PLATINUM', 'APPLE', 'APPLE', 'ACTIVE', 0),
(62, 'โอริสองุ่น', 'โอริสองุ่น', 'ADMIN_ALIAS', 'th', 'ORIS', 'GRAPE', 'GRAPE', 'ACTIVE', 0),
(62, 'โอริสองุ่น1', 'โอริสองุ่น1', 'ADMIN_ALIAS', 'th', 'ORIS', 'GRAPE', 'GRAPE', 'ACTIVE', 0),
(62, 'โอริสองุ่น 1', 'โอริสองุ่น 1', 'SHORT_FORM', 'th', 'ORIS', 'GRAPE', 'GRAPE', 'ACTIVE', 0),
(62, 'โอริสองุ่น2', 'โอริสองุ่น2', 'ADMIN_ALIAS', 'th', 'ORIS', 'GRAPE', 'GRAPE', 'ACTIVE', 0),
(62, 'โอริสองุ่น 2', 'โอริสองุ่น 2', 'SHORT_FORM', 'th', 'ORIS', 'GRAPE', 'GRAPE', 'ACTIVE', 0),
(62, 'โอริสองุ่น3', 'โอริสองุ่น3', 'ADMIN_ALIAS', 'th', 'ORIS', 'GRAPE', 'GRAPE', 'ACTIVE', 0),
(62, 'โอริสองุ่น 3', 'โอริสองุ่น 3', 'SHORT_FORM', 'th', 'ORIS', 'GRAPE', 'GRAPE', 'ACTIVE', 0),
(62, 'โอริสองุ่น4', 'โอริสองุ่น4', 'ADMIN_ALIAS', 'th', 'ORIS', 'GRAPE', 'GRAPE', 'ACTIVE', 0),
(62, 'โอริสองุ่น 4', 'โอริสองุ่น 4', 'SHORT_FORM', 'th', 'ORIS', 'GRAPE', 'GRAPE', 'ACTIVE', 0),
(62, 'โอริสองุ่น5', 'โอริสองุ่น5', 'ADMIN_ALIAS', 'th', 'ORIS', 'GRAPE', 'GRAPE', 'ACTIVE', 0),
(62, 'โอริสองุ่น 5', 'โอริสองุ่น 5', 'SHORT_FORM', 'th', 'ORIS', 'GRAPE', 'GRAPE', 'ACTIVE', 0),
(63, 'จอนสปา', 'จอนสปา', 'ADMIN_ALIAS', 'th', 'JOHN', 'SPA', 'SPA', 'ACTIVE', 0),
(63, 'จอนสปา1', 'จอนสปา1', 'ADMIN_ALIAS', 'th', 'JOHN', 'SPA', 'SPA', 'ACTIVE', 0),
(63, 'จอนสปา 1', 'จอนสปา 1', 'SHORT_FORM', 'th', 'JOHN', 'SPA', 'SPA', 'ACTIVE', 0),
(63, 'จอนสปา2', 'จอนสปา2', 'ADMIN_ALIAS', 'th', 'JOHN', 'SPA', 'SPA', 'ACTIVE', 0),
(63, 'จอนสปา 2', 'จอนสปา 2', 'SHORT_FORM', 'th', 'JOHN', 'SPA', 'SPA', 'ACTIVE', 0),
(63, 'จอนสปา3', 'จอนสปา3', 'ADMIN_ALIAS', 'th', 'JOHN', 'SPA', 'SPA', 'ACTIVE', 0),
(63, 'จอนสปา 3', 'จอนสปา 3', 'SHORT_FORM', 'th', 'JOHN', 'SPA', 'SPA', 'ACTIVE', 0),
(63, 'จอนสปา4', 'จอนสปา4', 'ADMIN_ALIAS', 'th', 'JOHN', 'SPA', 'SPA', 'ACTIVE', 0),
(63, 'จอนสปา 4', 'จอนสปา 4', 'SHORT_FORM', 'th', 'JOHN', 'SPA', 'SPA', 'ACTIVE', 0),
(63, 'จอนสปา5', 'จอนสปา5', 'ADMIN_ALIAS', 'th', 'JOHN', 'SPA', 'SPA', 'ACTIVE', 0),
(63, 'จอนสปา 5', 'จอนสปา 5', 'SHORT_FORM', 'th', 'JOHN', 'SPA', 'SPA', 'ACTIVE', 0),
(64, 'รอยัลแดง', 'รอยัลแดง', 'ADMIN_ALIAS', 'th', 'ROYAL', 'RED', 'RED', 'ACTIVE', 0),
(64, 'รอยัลแดง1', 'รอยัลแดง1', 'ADMIN_ALIAS', 'th', 'ROYAL', 'RED', 'RED', 'ACTIVE', 0),
(64, 'รอยัลแดง 1', 'รอยัลแดง 1', 'SHORT_FORM', 'th', 'ROYAL', 'RED', 'RED', 'ACTIVE', 0),
(64, 'รอยัลแดง2', 'รอยัลแดง2', 'ADMIN_ALIAS', 'th', 'ROYAL', 'RED', 'RED', 'ACTIVE', 0),
(64, 'รอยัลแดง 2', 'รอยัลแดง 2', 'SHORT_FORM', 'th', 'ROYAL', 'RED', 'RED', 'ACTIVE', 0),
(64, 'รอยัลแดง3', 'รอยัลแดง3', 'ADMIN_ALIAS', 'th', 'ROYAL', 'RED', 'RED', 'ACTIVE', 0),
(64, 'รอยัลแดง 3', 'รอยัลแดง 3', 'SHORT_FORM', 'th', 'ROYAL', 'RED', 'RED', 'ACTIVE', 0),
(64, 'รอยัลแดง4', 'รอยัลแดง4', 'ADMIN_ALIAS', 'th', 'ROYAL', 'RED', 'RED', 'ACTIVE', 0),
(64, 'รอยัลแดง 4', 'รอยัลแดง 4', 'SHORT_FORM', 'th', 'ROYAL', 'RED', 'RED', 'ACTIVE', 0),
(64, 'รอยัลแดง5', 'รอยัลแดง5', 'ADMIN_ALIAS', 'th', 'ROYAL', 'RED', 'RED', 'ACTIVE', 0),
(64, 'รอยัลแดง 5', 'รอยัลแดง 5', 'SHORT_FORM', 'th', 'ROYAL', 'RED', 'RED', 'ACTIVE', 0),
(65, 'จีเอ็ม', 'จีเอ็ม', 'ADMIN_ALIAS', 'th', 'GM', 'RED', 'RED', 'ACTIVE', 0),
(65, 'จีเอ็ม1', 'จีเอ็ม1', 'ADMIN_ALIAS', 'th', 'GM', 'RED', 'RED', 'ACTIVE', 0),
(65, 'จีเอ็ม 1', 'จีเอ็ม 1', 'SHORT_FORM', 'th', 'GM', 'RED', 'RED', 'ACTIVE', 0),
(65, 'จีเอ็ม2', 'จีเอ็ม2', 'ADMIN_ALIAS', 'th', 'GM', 'RED', 'RED', 'ACTIVE', 0),
(65, 'จีเอ็ม 2', 'จีเอ็ม 2', 'SHORT_FORM', 'th', 'GM', 'RED', 'RED', 'ACTIVE', 0),
(65, 'จีเอ็ม3', 'จีเอ็ม3', 'ADMIN_ALIAS', 'th', 'GM', 'RED', 'RED', 'ACTIVE', 0),
(65, 'จีเอ็ม 3', 'จีเอ็ม 3', 'SHORT_FORM', 'th', 'GM', 'RED', 'RED', 'ACTIVE', 0),
(65, 'จีเอ็ม4', 'จีเอ็ม4', 'ADMIN_ALIAS', 'th', 'GM', 'RED', 'RED', 'ACTIVE', 0),
(65, 'จีเอ็ม 4', 'จีเอ็ม 4', 'SHORT_FORM', 'th', 'GM', 'RED', 'RED', 'ACTIVE', 0),
(65, 'จีเอ็ม5', 'จีเอ็ม5', 'ADMIN_ALIAS', 'th', 'GM', 'RED', 'RED', 'ACTIVE', 0),
(65, 'จีเอ็ม 5', 'จีเอ็ม 5', 'SHORT_FORM', 'th', 'GM', 'RED', 'RED', 'ACTIVE', 0),
(66, 'กรองทิพย์', 'กรองทิพย์', 'ADMIN_ALIAS', 'th', 'KRONG THIP', 'THIP', 'RED', 'ACTIVE', 0),
(66, 'กรองทิพย์1', 'กรองทิพย์1', 'ADMIN_ALIAS', 'th', 'KRONG THIP', 'THIP', 'RED', 'ACTIVE', 0),
(66, 'กรองทิพย์ 1', 'กรองทิพย์ 1', 'SHORT_FORM', 'th', 'KRONG THIP', 'THIP', 'RED', 'ACTIVE', 0),
(66, 'กรองทิพย์2', 'กรองทิพย์2', 'ADMIN_ALIAS', 'th', 'KRONG THIP', 'THIP', 'RED', 'ACTIVE', 0),
(66, 'กรองทิพย์ 2', 'กรองทิพย์ 2', 'SHORT_FORM', 'th', 'KRONG THIP', 'THIP', 'RED', 'ACTIVE', 0),
(66, 'กรองทิพย์3', 'กรองทิพย์3', 'ADMIN_ALIAS', 'th', 'KRONG THIP', 'THIP', 'RED', 'ACTIVE', 0),
(66, 'กรองทิพย์ 3', 'กรองทิพย์ 3', 'SHORT_FORM', 'th', 'KRONG THIP', 'THIP', 'RED', 'ACTIVE', 0),
(66, 'กรองทิพย์4', 'กรองทิพย์4', 'ADMIN_ALIAS', 'th', 'KRONG THIP', 'THIP', 'RED', 'ACTIVE', 0),
(66, 'กรองทิพย์ 4', 'กรองทิพย์ 4', 'SHORT_FORM', 'th', 'KRONG THIP', 'THIP', 'RED', 'ACTIVE', 0),
(66, 'กรองทิพย์5', 'กรองทิพย์5', 'ADMIN_ALIAS', 'th', 'KRONG THIP', 'THIP', 'RED', 'ACTIVE', 0),
(66, 'กรองทิพย์ 5', 'กรองทิพย์ 5', 'SHORT_FORM', 'th', 'KRONG THIP', 'THIP', 'RED', 'ACTIVE', 0),
(67, 'เอสเอ็มเอสแดง', 'เอสเอ็มเอสแดง', 'ADMIN_ALIAS', 'th', 'SMS', 'RED', 'RED', 'ACTIVE', 0),
(67, 'เอสเอ็มเอสแดง1', 'เอสเอ็มเอสแดง1', 'ADMIN_ALIAS', 'th', 'SMS', 'RED', 'RED', 'ACTIVE', 0),
(67, 'เอสเอ็มเอสแดง 1', 'เอสเอ็มเอสแดง 1', 'SHORT_FORM', 'th', 'SMS', 'RED', 'RED', 'ACTIVE', 0),
(67, 'เอสเอ็มเอสแดง2', 'เอสเอ็มเอสแดง2', 'ADMIN_ALIAS', 'th', 'SMS', 'RED', 'RED', 'ACTIVE', 0),
(67, 'เอสเอ็มเอสแดง 2', 'เอสเอ็มเอสแดง 2', 'SHORT_FORM', 'th', 'SMS', 'RED', 'RED', 'ACTIVE', 0),
(67, 'เอสเอ็มเอสแดง3', 'เอสเอ็มเอสแดง3', 'ADMIN_ALIAS', 'th', 'SMS', 'RED', 'RED', 'ACTIVE', 0),
(67, 'เอสเอ็มเอสแดง 3', 'เอสเอ็มเอสแดง 3', 'SHORT_FORM', 'th', 'SMS', 'RED', 'RED', 'ACTIVE', 0),
(67, 'เอสเอ็มเอสแดง4', 'เอสเอ็มเอสแดง4', 'ADMIN_ALIAS', 'th', 'SMS', 'RED', 'RED', 'ACTIVE', 0),
(67, 'เอสเอ็มเอสแดง 4', 'เอสเอ็มเอสแดง 4', 'SHORT_FORM', 'th', 'SMS', 'RED', 'RED', 'ACTIVE', 0),
(67, 'เอสเอ็มเอสแดง5', 'เอสเอ็มเอสแดง5', 'ADMIN_ALIAS', 'th', 'SMS', 'RED', 'RED', 'ACTIVE', 0),
(67, 'เอสเอ็มเอสแดง 5', 'เอสเอ็มเอสแดง 5', 'SHORT_FORM', 'th', 'SMS', 'RED', 'RED', 'ACTIVE', 0),
(68, 'เวสแดง', 'เวสแดง', 'ADMIN_ALIAS', 'th', 'VESS', 'RED', 'RED', 'ACTIVE', 0),
(68, 'เวสแดง1', 'เวสแดง1', 'ADMIN_ALIAS', 'th', 'VESS', 'RED', 'RED', 'ACTIVE', 0),
(68, 'เวสแดง 1', 'เวสแดง 1', 'SHORT_FORM', 'th', 'VESS', 'RED', 'RED', 'ACTIVE', 0),
(68, 'เวสแดง2', 'เวสแดง2', 'ADMIN_ALIAS', 'th', 'VESS', 'RED', 'RED', 'ACTIVE', 0),
(68, 'เวสแดง 2', 'เวสแดง 2', 'SHORT_FORM', 'th', 'VESS', 'RED', 'RED', 'ACTIVE', 0),
(68, 'เวสแดง3', 'เวสแดง3', 'ADMIN_ALIAS', 'th', 'VESS', 'RED', 'RED', 'ACTIVE', 0),
(68, 'เวสแดง 3', 'เวสแดง 3', 'SHORT_FORM', 'th', 'VESS', 'RED', 'RED', 'ACTIVE', 0),
(68, 'เวสแดง4', 'เวสแดง4', 'ADMIN_ALIAS', 'th', 'VESS', 'RED', 'RED', 'ACTIVE', 0),
(68, 'เวสแดง 4', 'เวสแดง 4', 'SHORT_FORM', 'th', 'VESS', 'RED', 'RED', 'ACTIVE', 0),
(68, 'เวสแดง5', 'เวสแดง5', 'ADMIN_ALIAS', 'th', 'VESS', 'RED', 'RED', 'ACTIVE', 0),
(68, 'เวสแดง 5', 'เวสแดง 5', 'SHORT_FORM', 'th', 'VESS', 'RED', 'RED', 'ACTIVE', 0),
(69, 'เวสแดงอ่อน', 'เวสแดงอ่อน', 'ADMIN_ALIAS', 'th', 'VESS', 'RED', 'LIGHT', 'ACTIVE', 0),
(69, 'เวสแดงอ่อน1', 'เวสแดงอ่อน1', 'ADMIN_ALIAS', 'th', 'VESS', 'RED', 'LIGHT', 'ACTIVE', 0),
(69, 'เวสแดงอ่อน 1', 'เวสแดงอ่อน 1', 'SHORT_FORM', 'th', 'VESS', 'RED', 'LIGHT', 'ACTIVE', 0),
(69, 'เวสแดงอ่อน2', 'เวสแดงอ่อน2', 'ADMIN_ALIAS', 'th', 'VESS', 'RED', 'LIGHT', 'ACTIVE', 0),
(69, 'เวสแดงอ่อน 2', 'เวสแดงอ่อน 2', 'SHORT_FORM', 'th', 'VESS', 'RED', 'LIGHT', 'ACTIVE', 0),
(69, 'เวสแดงอ่อน3', 'เวสแดงอ่อน3', 'ADMIN_ALIAS', 'th', 'VESS', 'RED', 'LIGHT', 'ACTIVE', 0),
(69, 'เวสแดงอ่อน 3', 'เวสแดงอ่อน 3', 'SHORT_FORM', 'th', 'VESS', 'RED', 'LIGHT', 'ACTIVE', 0),
(69, 'เวสแดงอ่อน4', 'เวสแดงอ่อน4', 'ADMIN_ALIAS', 'th', 'VESS', 'RED', 'LIGHT', 'ACTIVE', 0),
(69, 'เวสแดงอ่อน 4', 'เวสแดงอ่อน 4', 'SHORT_FORM', 'th', 'VESS', 'RED', 'LIGHT', 'ACTIVE', 0),
(69, 'เวสแดงอ่อน5', 'เวสแดงอ่อน5', 'ADMIN_ALIAS', 'th', 'VESS', 'RED', 'LIGHT', 'ACTIVE', 0),
(69, 'เวสแดงอ่อน 5', 'เวสแดงอ่อน 5', 'SHORT_FORM', 'th', 'VESS', 'RED', 'LIGHT', 'ACTIVE', 0),
(70, 'มาโบโร่ขาว', 'มาโบโร่ขาว', 'ADMIN_ALIAS', 'th', 'MARLBORO', 'GOLD', 'GOLD', 'ACTIVE', 0),
(70, 'มาโบโร่ขาว1', 'มาโบโร่ขาว1', 'ADMIN_ALIAS', 'th', 'MARLBORO', 'GOLD', 'GOLD', 'ACTIVE', 0),
(70, 'มาโบโร่ขาว 1', 'มาโบโร่ขาว 1', 'SHORT_FORM', 'th', 'MARLBORO', 'GOLD', 'GOLD', 'ACTIVE', 0),
(70, 'มาโบโร่ขาว2', 'มาโบโร่ขาว2', 'ADMIN_ALIAS', 'th', 'MARLBORO', 'GOLD', 'GOLD', 'ACTIVE', 0),
(70, 'มาโบโร่ขาว 2', 'มาโบโร่ขาว 2', 'SHORT_FORM', 'th', 'MARLBORO', 'GOLD', 'GOLD', 'ACTIVE', 0),
(70, 'มาโบโร่ขาว3', 'มาโบโร่ขาว3', 'ADMIN_ALIAS', 'th', 'MARLBORO', 'GOLD', 'GOLD', 'ACTIVE', 0),
(70, 'มาโบโร่ขาว 3', 'มาโบโร่ขาว 3', 'SHORT_FORM', 'th', 'MARLBORO', 'GOLD', 'GOLD', 'ACTIVE', 0),
(70, 'มาโบโร่ขาว4', 'มาโบโร่ขาว4', 'ADMIN_ALIAS', 'th', 'MARLBORO', 'GOLD', 'GOLD', 'ACTIVE', 0),
(70, 'มาโบโร่ขาว 4', 'มาโบโร่ขาว 4', 'SHORT_FORM', 'th', 'MARLBORO', 'GOLD', 'GOLD', 'ACTIVE', 0),
(70, 'มาโบโร่ขาว5', 'มาโบโร่ขาว5', 'ADMIN_ALIAS', 'th', 'MARLBORO', 'GOLD', 'GOLD', 'ACTIVE', 0),
(70, 'มาโบโร่ขาว 5', 'มาโบโร่ขาว 5', 'SHORT_FORM', 'th', 'MARLBORO', 'GOLD', 'GOLD', 'ACTIVE', 0),
(71, '235 แดง', '235 แดง', 'SHORT_FORM', 'th', '235', 'RED', 'RED', 'ACTIVE', 0),
(71, '235 แดง1', '235 แดง1', 'SHORT_FORM', 'th', '235', 'RED', 'RED', 'ACTIVE', 0),
(71, '235 แดง 1', '235 แดง 1', 'SHORT_FORM', 'th', '235', 'RED', 'RED', 'ACTIVE', 0),
(71, '235 แดง2', '235 แดง2', 'SHORT_FORM', 'th', '235', 'RED', 'RED', 'ACTIVE', 0),
(71, '235 แดง 2', '235 แดง 2', 'SHORT_FORM', 'th', '235', 'RED', 'RED', 'ACTIVE', 0),
(71, '235 แดง3', '235 แดง3', 'SHORT_FORM', 'th', '235', 'RED', 'RED', 'ACTIVE', 0),
(71, '235 แดง 3', '235 แดง 3', 'SHORT_FORM', 'th', '235', 'RED', 'RED', 'ACTIVE', 0),
(71, '235 แดง4', '235 แดง4', 'SHORT_FORM', 'th', '235', 'RED', 'RED', 'ACTIVE', 0),
(71, '235 แดง 4', '235 แดง 4', 'SHORT_FORM', 'th', '235', 'RED', 'RED', 'ACTIVE', 0),
(71, '235 แดง5', '235 แดง5', 'SHORT_FORM', 'th', '235', 'RED', 'RED', 'ACTIVE', 0),
(71, '235 แดง 5', '235 แดง 5', 'SHORT_FORM', 'th', '235', 'RED', 'RED', 'ACTIVE', 0),
(72, 'โกเม้าแดงล้วน', 'โกเม้าแดงล้วน', 'ADMIN_ALIAS', 'th', 'GOLD MOUNT', 'MOUNT', 'FULL_RED', 'ACTIVE', 0),
(72, 'โกเม้าแดงล้วน1', 'โกเม้าแดงล้วน1', 'ADMIN_ALIAS', 'th', 'GOLD MOUNT', 'MOUNT', 'FULL_RED', 'ACTIVE', 0),
(72, 'โกเม้าแดงล้วน 1', 'โกเม้าแดงล้วน 1', 'SHORT_FORM', 'th', 'GOLD MOUNT', 'MOUNT', 'FULL_RED', 'ACTIVE', 0),
(72, 'โกเม้าแดงล้วน2', 'โกเม้าแดงล้วน2', 'ADMIN_ALIAS', 'th', 'GOLD MOUNT', 'MOUNT', 'FULL_RED', 'ACTIVE', 0),
(72, 'โกเม้าแดงล้วน 2', 'โกเม้าแดงล้วน 2', 'SHORT_FORM', 'th', 'GOLD MOUNT', 'MOUNT', 'FULL_RED', 'ACTIVE', 0),
(72, 'โกเม้าแดงล้วน3', 'โกเม้าแดงล้วน3', 'ADMIN_ALIAS', 'th', 'GOLD MOUNT', 'MOUNT', 'FULL_RED', 'ACTIVE', 0),
(72, 'โกเม้าแดงล้วน 3', 'โกเม้าแดงล้วน 3', 'SHORT_FORM', 'th', 'GOLD MOUNT', 'MOUNT', 'FULL_RED', 'ACTIVE', 0),
(72, 'โกเม้าแดงล้วน4', 'โกเม้าแดงล้วน4', 'ADMIN_ALIAS', 'th', 'GOLD MOUNT', 'MOUNT', 'FULL_RED', 'ACTIVE', 0),
(72, 'โกเม้าแดงล้วน 4', 'โกเม้าแดงล้วน 4', 'SHORT_FORM', 'th', 'GOLD MOUNT', 'MOUNT', 'FULL_RED', 'ACTIVE', 0),
(72, 'โกเม้าแดงล้วน5', 'โกเม้าแดงล้วน5', 'ADMIN_ALIAS', 'th', 'GOLD MOUNT', 'MOUNT', 'FULL_RED', 'ACTIVE', 0),
(72, 'โกเม้าแดงล้วน 5', 'โกเม้าแดงล้วน 5', 'SHORT_FORM', 'th', 'GOLD MOUNT', 'MOUNT', 'FULL_RED', 'ACTIVE', 0),
(73, 'จอนอ่อน', 'จอนอ่อน', 'ADMIN_ALIAS', 'th', 'JOHN', 'WHITE', 'WHITE', 'ACTIVE', 0),
(73, 'จอนอ่อน1', 'จอนอ่อน1', 'ADMIN_ALIAS', 'th', 'JOHN', 'WHITE', 'WHITE', 'ACTIVE', 0),
(73, 'จอนอ่อน 1', 'จอนอ่อน 1', 'SHORT_FORM', 'th', 'JOHN', 'WHITE', 'WHITE', 'ACTIVE', 0),
(73, 'จอนอ่อน2', 'จอนอ่อน2', 'ADMIN_ALIAS', 'th', 'JOHN', 'WHITE', 'WHITE', 'ACTIVE', 0),
(73, 'จอนอ่อน 2', 'จอนอ่อน 2', 'SHORT_FORM', 'th', 'JOHN', 'WHITE', 'WHITE', 'ACTIVE', 0),
(73, 'จอนอ่อน3', 'จอนอ่อน3', 'ADMIN_ALIAS', 'th', 'JOHN', 'WHITE', 'WHITE', 'ACTIVE', 0),
(73, 'จอนอ่อน 3', 'จอนอ่อน 3', 'SHORT_FORM', 'th', 'JOHN', 'WHITE', 'WHITE', 'ACTIVE', 0),
(73, 'จอนอ่อน4', 'จอนอ่อน4', 'ADMIN_ALIAS', 'th', 'JOHN', 'WHITE', 'WHITE', 'ACTIVE', 0),
(73, 'จอนอ่อน 4', 'จอนอ่อน 4', 'SHORT_FORM', 'th', 'JOHN', 'WHITE', 'WHITE', 'ACTIVE', 0),
(73, 'จอนอ่อน5', 'จอนอ่อน5', 'ADMIN_ALIAS', 'th', 'JOHN', 'WHITE', 'WHITE', 'ACTIVE', 0),
(73, 'จอนอ่อน 5', 'จอนอ่อน 5', 'SHORT_FORM', 'th', 'JOHN', 'WHITE', 'WHITE', 'ACTIVE', 0),
(74, 'แอลเอ็มแดง', 'แอลเอ็มแดง', 'ADMIN_ALIAS', 'th', 'L&M', 'RED', 'RED', 'ACTIVE', 0),
(74, 'แอลเอ็มแดง1', 'แอลเอ็มแดง1', 'ADMIN_ALIAS', 'th', 'L&M', 'RED', 'RED', 'ACTIVE', 0),
(74, 'แอลเอ็มแดง 1', 'แอลเอ็มแดง 1', 'SHORT_FORM', 'th', 'L&M', 'RED', 'RED', 'ACTIVE', 0),
(74, 'แอลเอ็มแดง2', 'แอลเอ็มแดง2', 'ADMIN_ALIAS', 'th', 'L&M', 'RED', 'RED', 'ACTIVE', 0),
(74, 'แอลเอ็มแดง 2', 'แอลเอ็มแดง 2', 'SHORT_FORM', 'th', 'L&M', 'RED', 'RED', 'ACTIVE', 0),
(74, 'แอลเอ็มแดง3', 'แอลเอ็มแดง3', 'ADMIN_ALIAS', 'th', 'L&M', 'RED', 'RED', 'ACTIVE', 0),
(74, 'แอลเอ็มแดง 3', 'แอลเอ็มแดง 3', 'SHORT_FORM', 'th', 'L&M', 'RED', 'RED', 'ACTIVE', 0),
(74, 'แอลเอ็มแดง4', 'แอลเอ็มแดง4', 'ADMIN_ALIAS', 'th', 'L&M', 'RED', 'RED', 'ACTIVE', 0),
(74, 'แอลเอ็มแดง 4', 'แอลเอ็มแดง 4', 'SHORT_FORM', 'th', 'L&M', 'RED', 'RED', 'ACTIVE', 0),
(74, 'แอลเอ็มแดง5', 'แอลเอ็มแดง5', 'ADMIN_ALIAS', 'th', 'L&M', 'RED', 'RED', 'ACTIVE', 0),
(74, 'แอลเอ็มแดง 5', 'แอลเอ็มแดง 5', 'SHORT_FORM', 'th', 'L&M', 'RED', 'RED', 'ACTIVE', 0),
(75, 'มาโบโร่แดง', 'มาโบโร่แดง', 'ADMIN_ALIAS', 'th', 'MARLBORO', 'RED', 'RED', 'ACTIVE', 0),
(75, 'มาโบโร่แดง1', 'มาโบโร่แดง1', 'ADMIN_ALIAS', 'th', 'MARLBORO', 'RED', 'RED', 'ACTIVE', 0),
(75, 'มาโบโร่แดง 1', 'มาโบโร่แดง 1', 'SHORT_FORM', 'th', 'MARLBORO', 'RED', 'RED', 'ACTIVE', 0),
(75, 'มาโบโร่แดง2', 'มาโบโร่แดง2', 'ADMIN_ALIAS', 'th', 'MARLBORO', 'RED', 'RED', 'ACTIVE', 0),
(75, 'มาโบโร่แดง 2', 'มาโบโร่แดง 2', 'SHORT_FORM', 'th', 'MARLBORO', 'RED', 'RED', 'ACTIVE', 0),
(75, 'มาโบโร่แดง3', 'มาโบโร่แดง3', 'ADMIN_ALIAS', 'th', 'MARLBORO', 'RED', 'RED', 'ACTIVE', 0),
(75, 'มาโบโร่แดง 3', 'มาโบโร่แดง 3', 'SHORT_FORM', 'th', 'MARLBORO', 'RED', 'RED', 'ACTIVE', 0),
(75, 'มาโบโร่แดง4', 'มาโบโร่แดง4', 'ADMIN_ALIAS', 'th', 'MARLBORO', 'RED', 'RED', 'ACTIVE', 0),
(75, 'มาโบโร่แดง 4', 'มาโบโร่แดง 4', 'SHORT_FORM', 'th', 'MARLBORO', 'RED', 'RED', 'ACTIVE', 0),
(75, 'มาโบโร่แดง5', 'มาโบโร่แดง5', 'ADMIN_ALIAS', 'th', 'MARLBORO', 'RED', 'RED', 'ACTIVE', 0),
(75, 'มาโบโร่แดง 5', 'มาโบโร่แดง 5', 'SHORT_FORM', 'th', 'MARLBORO', 'RED', 'RED', 'ACTIVE', 0)
ON CONFLICT (alias_norm) DO UPDATE SET
  alias_text = EXCLUDED.alias_text,
  product_id = EXCLUDED.product_id,
  alias_type = EXCLUDED.alias_type,
  brand_hint = EXCLUDED.brand_hint,
  category_hint = EXCLUDED.category_hint,
  variant_hint = EXCLUDED.variant_hint,
  status = EXCLUDED.status,
  updated_at = now();

INSERT INTO public.product_aliases (product_id, alias_text, alias_norm, alias_type, language_code, brand_hint, category_hint, variant_hint, status, usage_count)
VALUES
(76, 'เวสแดงพรีเมี่ยม', 'เวสแดงพรีเมี่ยม', 'ADMIN_ALIAS', 'th', 'VESS', 'RED', 'PREMIUM', 'ACTIVE', 0),
(76, 'เวสแดงพรีเมี่ยม1', 'เวสแดงพรีเมี่ยม1', 'ADMIN_ALIAS', 'th', 'VESS', 'RED', 'PREMIUM', 'ACTIVE', 0),
(76, 'เวสแดงพรีเมี่ยม 1', 'เวสแดงพรีเมี่ยม 1', 'SHORT_FORM', 'th', 'VESS', 'RED', 'PREMIUM', 'ACTIVE', 0),
(76, 'เวสแดงพรีเมี่ยม2', 'เวสแดงพรีเมี่ยม2', 'ADMIN_ALIAS', 'th', 'VESS', 'RED', 'PREMIUM', 'ACTIVE', 0),
(76, 'เวสแดงพรีเมี่ยม 2', 'เวสแดงพรีเมี่ยม 2', 'SHORT_FORM', 'th', 'VESS', 'RED', 'PREMIUM', 'ACTIVE', 0),
(76, 'เวสแดงพรีเมี่ยม3', 'เวสแดงพรีเมี่ยม3', 'ADMIN_ALIAS', 'th', 'VESS', 'RED', 'PREMIUM', 'ACTIVE', 0),
(76, 'เวสแดงพรีเมี่ยม 3', 'เวสแดงพรีเมี่ยม 3', 'SHORT_FORM', 'th', 'VESS', 'RED', 'PREMIUM', 'ACTIVE', 0),
(76, 'เวสแดงพรีเมี่ยม4', 'เวสแดงพรีเมี่ยม4', 'ADMIN_ALIAS', 'th', 'VESS', 'RED', 'PREMIUM', 'ACTIVE', 0),
(76, 'เวสแดงพรีเมี่ยม 4', 'เวสแดงพรีเมี่ยม 4', 'SHORT_FORM', 'th', 'VESS', 'RED', 'PREMIUM', 'ACTIVE', 0),
(76, 'เวสแดงพรีเมี่ยม5', 'เวสแดงพรีเมี่ยม5', 'ADMIN_ALIAS', 'th', 'VESS', 'RED', 'PREMIUM', 'ACTIVE', 0),
(76, 'เวสแดงพรีเมี่ยม 5', 'เวสแดงพรีเมี่ยม 5', 'SHORT_FORM', 'th', 'VESS', 'RED', 'PREMIUM', 'ACTIVE', 0),
(77, 'แคนยอนแดง', 'แคนยอนแดง', 'ADMIN_ALIAS', 'th', 'CANYON', 'RED', 'RED', 'ACTIVE', 0),
(77, 'แคนยอนแดง1', 'แคนยอนแดง1', 'ADMIN_ALIAS', 'th', 'CANYON', 'RED', 'RED', 'ACTIVE', 0),
(77, 'แคนยอนแดง 1', 'แคนยอนแดง 1', 'SHORT_FORM', 'th', 'CANYON', 'RED', 'RED', 'ACTIVE', 0),
(77, 'แคนยอนแดง2', 'แคนยอนแดง2', 'ADMIN_ALIAS', 'th', 'CANYON', 'RED', 'RED', 'ACTIVE', 0),
(77, 'แคนยอนแดง 2', 'แคนยอนแดง 2', 'SHORT_FORM', 'th', 'CANYON', 'RED', 'RED', 'ACTIVE', 0),
(77, 'แคนยอนแดง3', 'แคนยอนแดง3', 'ADMIN_ALIAS', 'th', 'CANYON', 'RED', 'RED', 'ACTIVE', 0),
(77, 'แคนยอนแดง 3', 'แคนยอนแดง 3', 'SHORT_FORM', 'th', 'CANYON', 'RED', 'RED', 'ACTIVE', 0),
(77, 'แคนยอนแดง4', 'แคนยอนแดง4', 'ADMIN_ALIAS', 'th', 'CANYON', 'RED', 'RED', 'ACTIVE', 0),
(77, 'แคนยอนแดง 4', 'แคนยอนแดง 4', 'SHORT_FORM', 'th', 'CANYON', 'RED', 'RED', 'ACTIVE', 0),
(77, 'แคนยอนแดง5', 'แคนยอนแดง5', 'ADMIN_ALIAS', 'th', 'CANYON', 'RED', 'RED', 'ACTIVE', 0),
(77, 'แคนยอนแดง 5', 'แคนยอนแดง 5', 'SHORT_FORM', 'th', 'CANYON', 'RED', 'RED', 'ACTIVE', 0),
(78, 'แพลตตินั่มฟ้าคูล', 'แพลตตินั่มฟ้าคูล', 'ADMIN_ALIAS', 'th', 'PLATINUM', 'BLUE', 'COOL', 'ACTIVE', 0),
(78, 'แพลตตินั่มฟ้าคูล1', 'แพลตตินั่มฟ้าคูล1', 'ADMIN_ALIAS', 'th', 'PLATINUM', 'BLUE', 'COOL', 'ACTIVE', 0),
(78, 'แพลตตินั่มฟ้าคูล 1', 'แพลตตินั่มฟ้าคูล 1', 'SHORT_FORM', 'th', 'PLATINUM', 'BLUE', 'COOL', 'ACTIVE', 0),
(78, 'แพลตตินั่มฟ้าคูล2', 'แพลตตินั่มฟ้าคูล2', 'ADMIN_ALIAS', 'th', 'PLATINUM', 'BLUE', 'COOL', 'ACTIVE', 0),
(78, 'แพลตตินั่มฟ้าคูล 2', 'แพลตตินั่มฟ้าคูล 2', 'SHORT_FORM', 'th', 'PLATINUM', 'BLUE', 'COOL', 'ACTIVE', 0),
(78, 'แพลตตินั่มฟ้าคูล3', 'แพลตตินั่มฟ้าคูล3', 'ADMIN_ALIAS', 'th', 'PLATINUM', 'BLUE', 'COOL', 'ACTIVE', 0),
(78, 'แพลตตินั่มฟ้าคูล 3', 'แพลตตินั่มฟ้าคูล 3', 'SHORT_FORM', 'th', 'PLATINUM', 'BLUE', 'COOL', 'ACTIVE', 0),
(78, 'แพลตตินั่มฟ้าคูล4', 'แพลตตินั่มฟ้าคูล4', 'ADMIN_ALIAS', 'th', 'PLATINUM', 'BLUE', 'COOL', 'ACTIVE', 0),
(78, 'แพลตตินั่มฟ้าคูล 4', 'แพลตตินั่มฟ้าคูล 4', 'SHORT_FORM', 'th', 'PLATINUM', 'BLUE', 'COOL', 'ACTIVE', 0),
(78, 'แพลตตินั่มฟ้าคูล5', 'แพลตตินั่มฟ้าคูล5', 'ADMIN_ALIAS', 'th', 'PLATINUM', 'BLUE', 'COOL', 'ACTIVE', 0),
(78, 'แพลตตินั่มฟ้าคูล 5', 'แพลตตินั่มฟ้าคูล 5', 'SHORT_FORM', 'th', 'PLATINUM', 'BLUE', 'COOL', 'ACTIVE', 0),
(79, 'แพลตตินั่มบลูมิ้นท์ 2 เม็ดบีบ', 'แพลตตินั่มบลูมิ้นท์ 2 เม็ดบีบ', 'SHORT_FORM', 'th', 'PLATINUM', 'BLUE', 'MINT_2CAPS', 'ACTIVE', 0),
(79, 'แพลตตินั่มบลูมิ้นท์ 2 เม็ดบีบ1', 'แพลตตินั่มบลูมิ้นท์ 2 เม็ดบีบ1', 'SHORT_FORM', 'th', 'PLATINUM', 'BLUE', 'MINT_2CAPS', 'ACTIVE', 0),
(79, 'แพลตตินั่มบลูมิ้นท์ 2 เม็ดบีบ 1', 'แพลตตินั่มบลูมิ้นท์ 2 เม็ดบีบ 1', 'SHORT_FORM', 'th', 'PLATINUM', 'BLUE', 'MINT_2CAPS', 'ACTIVE', 0),
(79, 'แพลตตินั่มบลูมิ้นท์ 2 เม็ดบีบ2', 'แพลตตินั่มบลูมิ้นท์ 2 เม็ดบีบ2', 'SHORT_FORM', 'th', 'PLATINUM', 'BLUE', 'MINT_2CAPS', 'ACTIVE', 0),
(79, 'แพลตตินั่มบลูมิ้นท์ 2 เม็ดบีบ 2', 'แพลตตินั่มบลูมิ้นท์ 2 เม็ดบีบ 2', 'SHORT_FORM', 'th', 'PLATINUM', 'BLUE', 'MINT_2CAPS', 'ACTIVE', 0),
(79, 'แพลตตินั่มบลูมิ้นท์ 2 เม็ดบีบ3', 'แพลตตินั่มบลูมิ้นท์ 2 เม็ดบีบ3', 'SHORT_FORM', 'th', 'PLATINUM', 'BLUE', 'MINT_2CAPS', 'ACTIVE', 0),
(79, 'แพลตตินั่มบลูมิ้นท์ 2 เม็ดบีบ 3', 'แพลตตินั่มบลูมิ้นท์ 2 เม็ดบีบ 3', 'SHORT_FORM', 'th', 'PLATINUM', 'BLUE', 'MINT_2CAPS', 'ACTIVE', 0),
(79, 'แพลตตินั่มบลูมิ้นท์ 2 เม็ดบีบ4', 'แพลตตินั่มบลูมิ้นท์ 2 เม็ดบีบ4', 'SHORT_FORM', 'th', 'PLATINUM', 'BLUE', 'MINT_2CAPS', 'ACTIVE', 0),
(79, 'แพลตตินั่มบลูมิ้นท์ 2 เม็ดบีบ 4', 'แพลตตินั่มบลูมิ้นท์ 2 เม็ดบีบ 4', 'SHORT_FORM', 'th', 'PLATINUM', 'BLUE', 'MINT_2CAPS', 'ACTIVE', 0),
(79, 'แพลตตินั่มบลูมิ้นท์ 2 เม็ดบีบ5', 'แพลตตินั่มบลูมิ้นท์ 2 เม็ดบีบ5', 'SHORT_FORM', 'th', 'PLATINUM', 'BLUE', 'MINT_2CAPS', 'ACTIVE', 0),
(79, 'แพลตตินั่มบลูมิ้นท์ 2 เม็ดบีบ 5', 'แพลตตินั่มบลูมิ้นท์ 2 เม็ดบีบ 5', 'SHORT_FORM', 'th', 'PLATINUM', 'BLUE', 'MINT_2CAPS', 'ACTIVE', 0),
(80, 'มิลาโน่ฟิซ', 'มิลาโน่ฟิซ', 'ADMIN_ALIAS', 'th', 'MILANO', 'FIZZ', 'FIZZ', 'ACTIVE', 0),
(80, 'มิลาโน่ฟิซ1', 'มิลาโน่ฟิซ1', 'ADMIN_ALIAS', 'th', 'MILANO', 'FIZZ', 'FIZZ', 'ACTIVE', 0),
(80, 'มิลาโน่ฟิซ 1', 'มิลาโน่ฟิซ 1', 'SHORT_FORM', 'th', 'MILANO', 'FIZZ', 'FIZZ', 'ACTIVE', 0),
(80, 'มิลาโน่ฟิซ2', 'มิลาโน่ฟิซ2', 'ADMIN_ALIAS', 'th', 'MILANO', 'FIZZ', 'FIZZ', 'ACTIVE', 0),
(80, 'มิลาโน่ฟิซ 2', 'มิลาโน่ฟิซ 2', 'SHORT_FORM', 'th', 'MILANO', 'FIZZ', 'FIZZ', 'ACTIVE', 0),
(80, 'มิลาโน่ฟิซ3', 'มิลาโน่ฟิซ3', 'ADMIN_ALIAS', 'th', 'MILANO', 'FIZZ', 'FIZZ', 'ACTIVE', 0),
(80, 'มิลาโน่ฟิซ 3', 'มิลาโน่ฟิซ 3', 'SHORT_FORM', 'th', 'MILANO', 'FIZZ', 'FIZZ', 'ACTIVE', 0),
(80, 'มิลาโน่ฟิซ4', 'มิลาโน่ฟิซ4', 'ADMIN_ALIAS', 'th', 'MILANO', 'FIZZ', 'FIZZ', 'ACTIVE', 0),
(80, 'มิลาโน่ฟิซ 4', 'มิลาโน่ฟิซ 4', 'SHORT_FORM', 'th', 'MILANO', 'FIZZ', 'FIZZ', 'ACTIVE', 0),
(80, 'มิลาโน่ฟิซ5', 'มิลาโน่ฟิซ5', 'ADMIN_ALIAS', 'th', 'MILANO', 'FIZZ', 'FIZZ', 'ACTIVE', 0),
(80, 'มิลาโน่ฟิซ 5', 'มิลาโน่ฟิซ 5', 'SHORT_FORM', 'th', 'MILANO', 'FIZZ', 'FIZZ', 'ACTIVE', 0),
(81, 'ซุค', 'ซุค', 'ADMIN_ALIAS', 'th', 'SUK', 'DEFAULT', 'DEFAULT', 'ACTIVE', 0),
(81, 'ซุค1', 'ซุค1', 'ADMIN_ALIAS', 'th', 'SUK', 'DEFAULT', 'DEFAULT', 'ACTIVE', 0),
(81, 'ซุค 1', 'ซุค 1', 'SHORT_FORM', 'th', 'SUK', 'DEFAULT', 'DEFAULT', 'ACTIVE', 0),
(81, 'ซุค2', 'ซุค2', 'ADMIN_ALIAS', 'th', 'SUK', 'DEFAULT', 'DEFAULT', 'ACTIVE', 0),
(81, 'ซุค 2', 'ซุค 2', 'SHORT_FORM', 'th', 'SUK', 'DEFAULT', 'DEFAULT', 'ACTIVE', 0),
(81, 'ซุค3', 'ซุค3', 'ADMIN_ALIAS', 'th', 'SUK', 'DEFAULT', 'DEFAULT', 'ACTIVE', 0),
(81, 'ซุค 3', 'ซุค 3', 'SHORT_FORM', 'th', 'SUK', 'DEFAULT', 'DEFAULT', 'ACTIVE', 0),
(81, 'ซุค4', 'ซุค4', 'ADMIN_ALIAS', 'th', 'SUK', 'DEFAULT', 'DEFAULT', 'ACTIVE', 0),
(81, 'ซุค 4', 'ซุค 4', 'SHORT_FORM', 'th', 'SUK', 'DEFAULT', 'DEFAULT', 'ACTIVE', 0),
(81, 'ซุค5', 'ซุค5', 'ADMIN_ALIAS', 'th', 'SUK', 'DEFAULT', 'DEFAULT', 'ACTIVE', 0),
(81, 'ซุค 5', 'ซุค 5', 'SHORT_FORM', 'th', 'SUK', 'DEFAULT', 'DEFAULT', 'ACTIVE', 0),
(82, 'โอริสฟ้า', 'โอริสฟ้า', 'ADMIN_ALIAS', 'th', 'ORIS', 'BLUE', '1CAPS', 'ACTIVE', 0),
(82, 'โอริสฟ้า1', 'โอริสฟ้า1', 'ADMIN_ALIAS', 'th', 'ORIS', 'BLUE', '1CAPS', 'ACTIVE', 0),
(82, 'โอริสฟ้า 1', 'โอริสฟ้า 1', 'SHORT_FORM', 'th', 'ORIS', 'BLUE', '1CAPS', 'ACTIVE', 0),
(82, 'โอริสฟ้า2', 'โอริสฟ้า2', 'ADMIN_ALIAS', 'th', 'ORIS', 'BLUE', '1CAPS', 'ACTIVE', 0),
(82, 'โอริสฟ้า 2', 'โอริสฟ้า 2', 'SHORT_FORM', 'th', 'ORIS', 'BLUE', '1CAPS', 'ACTIVE', 0),
(82, 'โอริสฟ้า3', 'โอริสฟ้า3', 'ADMIN_ALIAS', 'th', 'ORIS', 'BLUE', '1CAPS', 'ACTIVE', 0),
(82, 'โอริสฟ้า 3', 'โอริสฟ้า 3', 'SHORT_FORM', 'th', 'ORIS', 'BLUE', '1CAPS', 'ACTIVE', 0),
(82, 'โอริสฟ้า4', 'โอริสฟ้า4', 'ADMIN_ALIAS', 'th', 'ORIS', 'BLUE', '1CAPS', 'ACTIVE', 0),
(82, 'โอริสฟ้า 4', 'โอริสฟ้า 4', 'SHORT_FORM', 'th', 'ORIS', 'BLUE', '1CAPS', 'ACTIVE', 0),
(82, 'โอริสฟ้า5', 'โอริสฟ้า5', 'ADMIN_ALIAS', 'th', 'ORIS', 'BLUE', '1CAPS', 'ACTIVE', 0),
(82, 'โอริสฟ้า 5', 'โอริสฟ้า 5', 'SHORT_FORM', 'th', 'ORIS', 'BLUE', '1CAPS', 'ACTIVE', 0),
(83, 'โอริสบลู', 'โอริสบลู', 'ADMIN_ALIAS', 'th', 'ORIS', 'BLUE', '2CAPS', 'ACTIVE', 0),
(83, 'โอริสบลู1', 'โอริสบลู1', 'ADMIN_ALIAS', 'th', 'ORIS', 'BLUE', '2CAPS', 'ACTIVE', 0),
(83, 'โอริสบลู 1', 'โอริสบลู 1', 'SHORT_FORM', 'th', 'ORIS', 'BLUE', '2CAPS', 'ACTIVE', 0),
(83, 'โอริสบลู2', 'โอริสบลู2', 'ADMIN_ALIAS', 'th', 'ORIS', 'BLUE', '2CAPS', 'ACTIVE', 0),
(83, 'โอริสบลู 2', 'โอริสบลู 2', 'SHORT_FORM', 'th', 'ORIS', 'BLUE', '2CAPS', 'ACTIVE', 0),
(83, 'โอริสบลู3', 'โอริสบลู3', 'ADMIN_ALIAS', 'th', 'ORIS', 'BLUE', '2CAPS', 'ACTIVE', 0),
(83, 'โอริสบลู 3', 'โอริสบลู 3', 'SHORT_FORM', 'th', 'ORIS', 'BLUE', '2CAPS', 'ACTIVE', 0),
(83, 'โอริสบลู4', 'โอริสบลู4', 'ADMIN_ALIAS', 'th', 'ORIS', 'BLUE', '2CAPS', 'ACTIVE', 0),
(83, 'โอริสบลู 4', 'โอริสบลู 4', 'SHORT_FORM', 'th', 'ORIS', 'BLUE', '2CAPS', 'ACTIVE', 0),
(83, 'โอริสบลู5', 'โอริสบลู5', 'ADMIN_ALIAS', 'th', 'ORIS', 'BLUE', '2CAPS', 'ACTIVE', 0),
(83, 'โอริสบลู 5', 'โอริสบลู 5', 'SHORT_FORM', 'th', 'ORIS', 'BLUE', '2CAPS', 'ACTIVE', 0),
(84, 'บลูไอซ์', 'บลูไอซ์', 'ADMIN_ALIAS', 'th', 'BLUE ICE', 'ICE', 'ICE_1CAPS', 'ACTIVE', 0),
(84, 'บลูไอซ์1', 'บลูไอซ์1', 'ADMIN_ALIAS', 'th', 'BLUE ICE', 'ICE', 'ICE_1CAPS', 'ACTIVE', 0),
(84, 'บลูไอซ์ 1', 'บลูไอซ์ 1', 'SHORT_FORM', 'th', 'BLUE ICE', 'ICE', 'ICE_1CAPS', 'ACTIVE', 0),
(84, 'บลูไอซ์2', 'บลูไอซ์2', 'ADMIN_ALIAS', 'th', 'BLUE ICE', 'ICE', 'ICE_1CAPS', 'ACTIVE', 0),
(84, 'บลูไอซ์ 2', 'บลูไอซ์ 2', 'SHORT_FORM', 'th', 'BLUE ICE', 'ICE', 'ICE_1CAPS', 'ACTIVE', 0),
(84, 'บลูไอซ์3', 'บลูไอซ์3', 'ADMIN_ALIAS', 'th', 'BLUE ICE', 'ICE', 'ICE_1CAPS', 'ACTIVE', 0),
(84, 'บลูไอซ์ 3', 'บลูไอซ์ 3', 'SHORT_FORM', 'th', 'BLUE ICE', 'ICE', 'ICE_1CAPS', 'ACTIVE', 0),
(84, 'บลูไอซ์4', 'บลูไอซ์4', 'ADMIN_ALIAS', 'th', 'BLUE ICE', 'ICE', 'ICE_1CAPS', 'ACTIVE', 0),
(84, 'บลูไอซ์ 4', 'บลูไอซ์ 4', 'SHORT_FORM', 'th', 'BLUE ICE', 'ICE', 'ICE_1CAPS', 'ACTIVE', 0),
(84, 'บลูไอซ์5', 'บลูไอซ์5', 'ADMIN_ALIAS', 'th', 'BLUE ICE', 'ICE', 'ICE_1CAPS', 'ACTIVE', 0),
(84, 'บลูไอซ์ 5', 'บลูไอซ์ 5', 'SHORT_FORM', 'th', 'BLUE ICE', 'ICE', 'ICE_1CAPS', 'ACTIVE', 0),
(86, 'ดีแอนด์เจ', 'ดีแอนด์เจ', 'ADMIN_ALIAS', 'th', 'D&J', 'DEFAULT', 'DEFAULT', 'ACTIVE', 0),
(86, 'ดีแอนด์เจ1', 'ดีแอนด์เจ1', 'ADMIN_ALIAS', 'th', 'D&J', 'DEFAULT', 'DEFAULT', 'ACTIVE', 0),
(86, 'ดีแอนด์เจ 1', 'ดีแอนด์เจ 1', 'SHORT_FORM', 'th', 'D&J', 'DEFAULT', 'DEFAULT', 'ACTIVE', 0),
(86, 'ดีแอนด์เจ2', 'ดีแอนด์เจ2', 'ADMIN_ALIAS', 'th', 'D&J', 'DEFAULT', 'DEFAULT', 'ACTIVE', 0),
(86, 'ดีแอนด์เจ 2', 'ดีแอนด์เจ 2', 'SHORT_FORM', 'th', 'D&J', 'DEFAULT', 'DEFAULT', 'ACTIVE', 0),
(86, 'ดีแอนด์เจ3', 'ดีแอนด์เจ3', 'ADMIN_ALIAS', 'th', 'D&J', 'DEFAULT', 'DEFAULT', 'ACTIVE', 0),
(86, 'ดีแอนด์เจ 3', 'ดีแอนด์เจ 3', 'SHORT_FORM', 'th', 'D&J', 'DEFAULT', 'DEFAULT', 'ACTIVE', 0),
(86, 'ดีแอนด์เจ4', 'ดีแอนด์เจ4', 'ADMIN_ALIAS', 'th', 'D&J', 'DEFAULT', 'DEFAULT', 'ACTIVE', 0),
(86, 'ดีแอนด์เจ 4', 'ดีแอนด์เจ 4', 'SHORT_FORM', 'th', 'D&J', 'DEFAULT', 'DEFAULT', 'ACTIVE', 0),
(86, 'ดีแอนด์เจ5', 'ดีแอนด์เจ5', 'ADMIN_ALIAS', 'th', 'D&J', 'DEFAULT', 'DEFAULT', 'ACTIVE', 0),
(86, 'ดีแอนด์เจ 5', 'ดีแอนด์เจ 5', 'SHORT_FORM', 'th', 'D&J', 'DEFAULT', 'DEFAULT', 'ACTIVE', 0),
(87, 'ม่อนดำ', 'ม่อนดำ', 'ADMIN_ALIAS', 'th', 'MOND', 'BLACK', 'BLACK', 'ACTIVE', 0),
(87, 'ม่อนดำ1', 'ม่อนดำ1', 'ADMIN_ALIAS', 'th', 'MOND', 'BLACK', 'BLACK', 'ACTIVE', 0),
(87, 'ม่อนดำ 1', 'ม่อนดำ 1', 'SHORT_FORM', 'th', 'MOND', 'BLACK', 'BLACK', 'ACTIVE', 0),
(87, 'ม่อนดำ2', 'ม่อนดำ2', 'ADMIN_ALIAS', 'th', 'MOND', 'BLACK', 'BLACK', 'ACTIVE', 0),
(87, 'ม่อนดำ 2', 'ม่อนดำ 2', 'SHORT_FORM', 'th', 'MOND', 'BLACK', 'BLACK', 'ACTIVE', 0),
(87, 'ม่อนดำ3', 'ม่อนดำ3', 'ADMIN_ALIAS', 'th', 'MOND', 'BLACK', 'BLACK', 'ACTIVE', 0),
(87, 'ม่อนดำ 3', 'ม่อนดำ 3', 'SHORT_FORM', 'th', 'MOND', 'BLACK', 'BLACK', 'ACTIVE', 0),
(87, 'ม่อนดำ4', 'ม่อนดำ4', 'ADMIN_ALIAS', 'th', 'MOND', 'BLACK', 'BLACK', 'ACTIVE', 0),
(87, 'ม่อนดำ 4', 'ม่อนดำ 4', 'SHORT_FORM', 'th', 'MOND', 'BLACK', 'BLACK', 'ACTIVE', 0),
(87, 'ม่อนดำ5', 'ม่อนดำ5', 'ADMIN_ALIAS', 'th', 'MOND', 'BLACK', 'BLACK', 'ACTIVE', 0),
(87, 'ม่อนดำ 5', 'ม่อนดำ 5', 'SHORT_FORM', 'th', 'MOND', 'BLACK', 'BLACK', 'ACTIVE', 0),
(88, 'คาแตงโม', 'คาแตงโม', 'ADMIN_ALIAS', 'th', 'CAVALLO_WATERMELON', 'WATERMELON', 'WATERMELON', 'ACTIVE', 0),
(88, 'คา แตงโม1', 'คา แตงโม1', 'SHORT_FORM', 'th', 'CAVALLO_WATERMELON', 'WATERMELON', 'WATERMELON', 'ACTIVE', 0),
(88, '🍉 CAVALLO แตงโม', '🍉 cavallo แตงโม', 'SHORT_FORM', 'th', 'CAVALLO_WATERMELON', 'WATERMELON', 'WATERMELON', 'ACTIVE', 0),
(89, 'คามะม่วง', 'คามะม่วง', 'ADMIN_ALIAS', 'th', 'CAVALLO', 'MANGO', 'MANGO', 'ACTIVE', 0),
(89, 'คา มะม่วง', 'คา มะม่วง', 'SHORT_FORM', 'th', 'CAVALLO', 'MANGO', 'MANGO', 'ACTIVE', 0),
(89, 'CAVALLO_MANGO', 'cavallo_mango', 'SHORT_FORM', 'th', 'CAVALLO', 'MANGO', 'MANGO', 'ACTIVE', 0),
(89, 'CAVALLO DOUBLE CORE MANGO', 'cavallo double core mango', 'SHORT_FORM', 'th', 'CAVALLO', 'MANGO', 'MANGO', 'ACTIVE', 0),
(90, 'SEVIOS_WATERMELON', 'sevios_watermelon', 'SHORT_FORM', 'th', 'SEVIOS', 'WATERMELON', 'WATERMELON', 'ACTIVE', 0),
(90, 'ซีวอสแตงโม', 'ซีวอสแตงโม', 'ADMIN_ALIAS', 'th', 'SEVIOS', 'WATERMELON', 'WATERMELON', 'ACTIVE', 0),
(90, 'ซีวอส แตงโม', 'ซีวอส แตงโม', 'SHORT_FORM', 'th', 'SEVIOS', 'WATERMELON', 'WATERMELON', 'ACTIVE', 0),
(90, 'แตงโม', 'แตงโม', 'ADMIN_ALIAS', 'th', 'SEVIOS', 'WATERMELON', 'WATERMELON', 'ACTIVE', 0)
ON CONFLICT (alias_norm) DO UPDATE SET
  alias_text = EXCLUDED.alias_text,
  product_id = EXCLUDED.product_id,
  alias_type = EXCLUDED.alias_type,
  brand_hint = EXCLUDED.brand_hint,
  category_hint = EXCLUDED.category_hint,
  variant_hint = EXCLUDED.variant_hint,
  status = EXCLUDED.status,
  updated_at = now();

