-- product_master 90 records - id 1..90 fixed
truncate public.product_master cascade;
insert into public.product_master (id, sku, brand, category, variant, th_name, name_standard) overriding system value values
(1,'VESS_MINT_COOL','VESS','COOL','MINT','เวสมิ้นคูล','Vess Mint Cool'),
(2,'VESS_MINT_MENTHOL','VESS','MINT','MENTHOL','เวสมิ้นเมนทอล','Vess Mint Menthol'),
(3,'GOLD_MOUNT_GREEN_WHITE','GOLD MOUNT','MOUNT','GREEN_WHITE','โกเขียวขาว','Gold Mount Green White'),
(4,'MILANO_MENTHOL','MILANO','MENTHOL','MENTHOL','มิลาโน่เมนทอล','Milano Menthol'),
(5,'MOND_GREEN','MOND','GREEN','GREEN','🟢 MOND_GREEN  1 คอต','Mond Green'),
(6,'PLATINUM_GREEN','PLATINUM','GREEN','GREEN','แพตตินั่มเขียว','Platinum Green'),
(7,'SEVIOS_GREEN','SEVIOS','GREEN','GREEN','ซีวอสเขียว','Sevios Green'),
(8,'SMS_GREEN','SMS','GREEN','GREEN','เอสเอ็มเอสเขียว','Sms Green'),
(9,'TEXAS_GREEN','TEXAS','GREEN','GREEN','เท็กซัสเขียว','Texas Green'),
(10,'VESS_GREEN','VESS','GREEN','GREEN','เวสเขียว','Vess Green'),
(11,'VESS_GREEN_SLIMS','VESS','GREEN','SLIMS','เวสเขียวเล็ก','Vess Green Slims'),
(12,'VESS_MINT','VESS','MINT','MINT','เวสมิ้น','Vess Mint'),
(13,'VOXX_GREEN','VOXX','GREEN','GREEN','วอคเขียว','Voxx Green'),
(14,'TEXAS_BLUE','TEXAS','BLUE','BLUE','เท็กซัสฟ้า','Texas Blue'),
(15,'VESS_GREEN_BLACK','VESS','GREEN','BLACK','เวสเขียวดำ','Vess Green Black'),
(16,'SIERRA_GREEN','SIERRA','GREEN','GREEN','เซียร่าเขียว','Sierra Green'),
(17,'OS_BLUEBERRY','OS','BLUEBERRY','BLUEBERRY','OS บลูเบอร์รี่','Os Blueberry'),
(18,'OS_MANGO','OS','MANGO','MANGO','OS มะม่วง','Os Mango'),
(19,'VESS_CRUSH_MINT.X.MANGO','VESS','CRUSH','MINT.X.MANGO','เวสมะม่วง','Vess Crush Mint.X.Mango'),
(20,'OS_STRAWBERRY','OS','STRAWBERRY','STRAWBERRY','OS สตอเบอร์รี่','Os Strawberry'),
(21,'MILANO_JAPAN','MILANO','JAPAN','JAPAN','มิลาโน่ญี่ปุ่น','Milano Japan'),
(22,'OS_PINEAPPLE','OS','PINEAPPLE','PINEAPPLE','OS สับปะรด','Os Pineapple'),
(23,'VESS_CRUSH_MINT.X.APPLE','VESS','CRUSH','MINT.X.APPLE','เวสแอปเปิ้ล','Vess Crush Mint.X.Apple'),
(24,'OS_WATERMELON','OS','WATERMELON','WATERMELON','OS แตงโม','Os Watermelon'),
(25,'VESS_CRUSH_MINT.X.GRAPE','VESS','CRUSH','MINT.X.GRAPE','เวสองุ่นใหญ่','Vess Crush Mint.X.Grape'),
(26,'VESS_GRAPE_SLIMS','VESS','GRAPE','SLIMS','เวสองุ่นสลิม','Vess Grape Slims'),
(27,'MOND_RAINBOW','MOND','RAINBOW','RAINBOW','ม่อนรุ้ง','Mond Rainbow'),
(28,'SEVIOS_RED','SEVIOS','RED','RED','SEVIOS_RED','Sevios Red'),
(29,'SIERRA_RED','SIERRA','RED','RED','เซียร่า','Sierra Red'),
(30,'MOND_GOLD','MOND','GOLD','GOLD','ม่อนทอง','Mond Gold'),
(31,'VESS_GOLD','VESS','GOLD','GOLD','เวสทอง','Vess Gold'),
(32,'MILANO_GOLD','MILANO','GOLD','GOLD','มิลาโน่ทอง','Milano Gold'),
(33,'CAVALLO_RED','CAVALLO','RED','RED','คาแดง','Cavallo Red'),
(34,'MILANO_KINGS','MILANO','KINGS','KINGS','มิลาโน่คิง','Milano Kings'),
(35,'PLATINUM_BLACK','PLATINUM','BLACK','BLACK','แพตตินั่มดำ','Platinum Black'),
(36,'GOLD_MOUNT_RED_WHITE','GOLD MOUNT','MOUNT','RED_WHITE','โกเม้าแดงขาว','Gold Mount Red White'),
(37,'WALTON_RED','WALTON','RED','RED','วอลตันแดง','Walton Red'),
(38,'VOXX_BLACK','VOXX','BLACK','BLACK','วอคดำ','Voxx Black'),
(39,'TEXAS_GOLD','TEXAS','GOLD','GOLD','เท็กซัสทอง','Texas Gold'),
(40,'JOHN_RED','JOHN','RED','RED','จอนแข็ง','John Red'),
(41,'TEXAS_RED','TEXAS','RED','RED','เท็กซัสแดง','Texas Red'),
(42,'MILANO_PURPLE','MILANO','PURPLE','PURPLE','มิลาโน่ม่วง','Milano Purple'),
(43,'CAVALLO_TWIN_X_BALL','CAVALLO','TWIN','X_BALL','คาวาโล่ม่วงเม็ดบีบ','Cavallo Twin X Ball'),
(44,'BAROESAN','BAROESAN','BAROESAN','BAROESAN','บารูอิซัน','Baroesan'),
(45,'CAVALLO_GREEN','CAVALLO','GREEN','GREEN','คาเขียว','Cavallo Green'),
(46,'ROYAL_GREEN','ROYAL','GREEN','GREEN','รอยัลเขียว','Royal Green'),
(47,'235_GREEN','235','GREEN','GREEN','235 เขียว','235 Green'),
(48,'CANYON_GREEN','CANYON','GREEN','GREEN','แคนยอนเขียว','Canyon Green'),
(49,'GOLD_MOUNT_FULL_GREEN','GOLD MOUNT','MOUNT','FULL_GREEN','โกเม้าเขียวล้วน','Gold Mount Full Green'),
(50,'L&M_GREEN','L&M','GREEN','GREEN','แอลเอ็มเขียว','L&M Green'),
(51,'MARLBORO_MENTHOL','MARLBORO','MENTHOL','MENTHOL','มาโบโร่เขียว','Marlboro Menthol'),
(52,'WALTON_GREEN','WALTON','GREEN','GREEN','วอลตันเขียว','Walton Green'),
(53,'CAPITAL_BLUE','CAPITAL','BLUE','BLUE','แคปปิตอลฟ้า','Capital Blue'),
(54,'ORIS_STRAWBERRY','ORIS','STRAWBERRY','STRAWBERRY','โอริสสตรอว์เบอร์รี่','Oris Strawberry'),
(55,'ORIS_STRAWBERRY_2CAPS','ORIS','STRAWBERRY','2CAPS','ORIS_STRAWBERRY_2CAPS','Oris Strawberry 2Caps'),
(56,'PLATINUM_STRAWBERRY','PLATINUM','STRAWBERRY','STRAWBERRY','แพลตตินั่มสตรอว์เบอร์รี่','Platinum Strawberry'),
(57,'ORIS_CHERRY','ORIS','CHERRY','CHERRY','โอริสเชอร์รี่','Oris Cherry'),
(58,'JOHN_APPLE_2CAPS','JOHN','APPLE','2CAPS','จอนแอปเปิ้ล 2 เม็ดบีบ','John Apple 2Caps'),
(59,'MOND_APPLE_FRUIT','MOND','APPLE','FRUIT','ม่อนแอปเปิ้ล','Mond Apple Fruit'),
(60,'ORIS_APPLE','ORIS','APPLE','APPLE','โอริสแอปเปิ้ล','Oris Apple'),
(61,'PLATINUM_APPLE','PLATINUM','APPLE','APPLE','แพลตตินั่มแอปเปิ้ล','Platinum Apple'),
(62,'ORIS_GRAPE','ORIS','GRAPE','GRAPE','โอริสองุ่น','Oris Grape'),
(63,'JOHN_SPA','JOHN','SPA','SPA','จอนสปา','John Spa'),
(64,'ROYAL_RED','ROYAL','RED','RED','รอยัลแดง','Royal Red'),
(65,'GM_RED','GM','RED','RED','จีเอ็ม','Gm Red'),
(66,'KRONG_THIP_RED','KRONG THIP','THIP','RED','กรองทิพย์','Krong Thip Red'),
(67,'SMS_RED','SMS','RED','RED','เอสเอ็มเอสแดง','Sms Red'),
(68,'VESS_RED','VESS','RED','RED','เวสแดง','Vess Red'),
(69,'VESS_RED_LIGHT','VESS','RED','LIGHT','เวสแดงอ่อน','Vess Red Light'),
(70,'MARLBORO_GOLD','MARLBORO','GOLD','GOLD','มาโบโร่ขาว','Marlboro Gold'),
(71,'235_RED','235','RED','RED','235 แดง','235 Red'),
(72,'GOLD_MOUNT_FULL_RED','GOLD MOUNT','MOUNT','FULL_RED','โกเม้าแดงล้วน','Gold Mount Full Red'),
(73,'JOHN_WHITE','JOHN','WHITE','WHITE','จอนอ่อน','John White'),
(74,'L&M_RED','L&M','RED','RED','แอลเอ็มแดง','L&M Red'),
(75,'MARLBORO_RED','MARLBORO','RED','RED','มาโบโร่แดง','Marlboro Red'),
(76,'VESS_RED_PREMIUM','VESS','RED','PREMIUM','เวสแดงพรีเมี่ยม','Vess Red Premium'),
(77,'CANYON_RED','CANYON','RED','RED','แคนยอนแดง','Canyon Red'),
(78,'PLATINUM_BLUE_COOL','PLATINUM','BLUE','COOL','แพลตตินั่มฟ้าคูล','Platinum Blue Cool'),
(79,'PLATINUM_BLUE_MINT_2CAPS','PLATINUM','BLUE','MINT_2CAPS','แพลตตินั่มบลูมิ้นท์ 2 เม็ดบีบ','Platinum Blue Mint 2Caps'),
(80,'MILANO_FIZZ','MILANO','FIZZ','FIZZ','มิลาโน่ฟิซ','Milano Fizz'),
(81,'SUK_DEFAULT','SUK','DEFAULT','DEFAULT','ซุค','Suk Default'),
(82,'ORIS_BLUE_1CAPS','ORIS','BLUE','1CAPS','โอริสฟ้า','Oris Blue 1Caps'),
(83,'ORIS_BLUE_2CAPS','ORIS','BLUE','2CAPS','โอริสบลู','Oris Blue 2Caps'),
(84,'BLUE_ICE_ICE_1CAPS','BLUE ICE','ICE','ICE_1CAPS','บลูไอซ์','Blue Ice Ice 1Caps'),
(85,'BLUE_ICE_ICE_2CAPS','BLUE','ICE','ICE_2CAPS','BLUE_ICE_ICE_2CAPS','Blue Ice Ice 2Caps'),
(86,'D&J_DEFAULT','D&J','DEFAULT','DEFAULT','ดีแอนด์เจ','D&J Default'),
(87,'MOND_BLACK','MOND','BLACK','BLACK','ม่อนดำ','Mond Black'),
(88,'CAVALLO_WATERMELON','CAVALLO_WATERMELON','WATERMELON','WATERMELON','คาแตงโม','Cavallo Watermelon'),
(89,'CAVALLO_MANGO','CAVALLO','MANGO','MANGO','คามะม่วง','Cavallo Mango'),
(90,'SEVIOS_WATERMELON','SEVIOS','WATERMELON','WATERMELON','SEVIOS_WATERMELON','Sevios Watermelon')
on conflict (id) do update set sku=excluded.sku, brand=excluded.brand, category=excluded.category, variant=excluded.variant, th_name=excluded.th_name, name_standard=excluded.name_standard;
