-- TELEGRAM ROOMS · BB + ST
-- ใช้กับ Supabase ของแต่ละค่ายตามส่วนที่ระบุ
-- ไม่ลบข้อมูลเดิม และคงชื่อ public.bb_orders_sent_history

-- =========================================================
-- BB: เติมคอลัมน์สำหรับหน้าเว็บในตารางประวัติเดิม
-- =========================================================
ALTER TABLE public.bb_orders_sent_history
  ADD COLUMN IF NOT EXISTS telegram_chat_id text,
  ADD COLUMN IF NOT EXISTS telegram_message_id text,
  ADD COLUMN IF NOT EXISTS telegram_message_text text,
  ADD COLUMN IF NOT EXISTS telegram_room text DEFAULT 'BB_SENT_HISTORY',
  ADD COLUMN IF NOT EXISTS queue_status text DEFAULT 'SENT',
  ADD COLUMN IF NOT EXISTS order_day_color_emoji text,
  ADD COLUMN IF NOT EXISTS time_slot_label text,
  ADD COLUMN IF NOT EXISTS ghost_column text,
  ADD COLUMN IF NOT EXISTS status_color text,
  ADD COLUMN IF NOT EXISTS routing_tag text;

-- =========================================================
-- ST: สร้างประวัติใหม่ด้วยรูปแบบเดียวกับ BB
-- =========================================================
ALTER TABLE public.st_order_packer_records
  ADD COLUMN IF NOT EXISTS telegram_sent text DEFAULT 'false',
  ADD COLUMN IF NOT EXISTS telegram_sent_at timestamptz,
  ADD COLUMN IF NOT EXISTS telegram_status text DEFAULT 'PENDING',
  ADD COLUMN IF NOT EXISTS delivery_state text DEFAULT 'PENDING',
  ADD COLUMN IF NOT EXISTS sent_at timestamptz,
  ADD COLUMN IF NOT EXISTS recalled_at timestamptz,
  ADD COLUMN IF NOT EXISTS order_emoji text,
  ADD COLUMN IF NOT EXISTS order_day_color_emoji text,
  ADD COLUMN IF NOT EXISTS ghost_column text,
  ADD COLUMN IF NOT EXISTS status_color text,
  ADD COLUMN IF NOT EXISTS routing_tag text,
  ADD COLUMN IF NOT EXISTS order_hour integer,
  ADD COLUMN IF NOT EXISTS time_slot text,
  ADD COLUMN IF NOT EXISTS time_slot_label text;

CREATE TABLE IF NOT EXISTS public.st_orders_sent_history (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_key text,
  order_number text,
  sent_at timestamptz NOT NULL DEFAULT now(),
  recalled_at timestamptz,
  recall_count integer NOT NULL DEFAULT 0,
  delivery_status text NOT NULL DEFAULT 'SENT',
  snapshot jsonb NOT NULL DEFAULT '{}'::jsonb,
  telegram_chat_id text,
  telegram_message_id text,
  telegram_message_text text,
  telegram_room text NOT NULL DEFAULT 'ST_SENT_HISTORY',
  queue_status text NOT NULL DEFAULT 'SENT',
  order_day_color_emoji text,
  time_slot_label text,
  ghost_column text,
  status_color text,
  routing_tag text,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_st_sent_history_key
  ON public.st_orders_sent_history (order_key, sent_at DESC);

CREATE OR REPLACE FUNCTION public.st_record_sent_history()
RETURNS trigger LANGUAGE plpgsql AS $function$
BEGIN
  IF NEW.telegram_sent IS DISTINCT FROM OLD.telegram_sent
     AND lower(COALESCE(NEW.telegram_sent, '')) IN ('true','1','t','sent','delivered','ไปแล้วไปลับ') THEN
    NEW.delivery_state := 'SENT';
    NEW.sent_at := COALESCE(NEW.sent_at, now());
    INSERT INTO public.st_orders_sent_history(
      order_key, order_number, sent_at, snapshot, order_day_color_emoji,
      time_slot_label, ghost_column, status_color, routing_tag
    ) VALUES (
      NEW.upsert_key, NEW.order_number, NEW.sent_at, to_jsonb(NEW),
      NEW.order_day_color_emoji, NEW.time_slot_label, NEW.ghost_column,
      NEW.status_color, NEW.routing_tag
    );
  END IF;
  RETURN NEW;
END;
$function$;

DROP TRIGGER IF EXISTS trg_st_record_sent_history ON public.st_order_packer_records;
CREATE TRIGGER trg_st_record_sent_history
BEFORE UPDATE OF telegram_sent ON public.st_order_packer_records
FOR EACH ROW EXECUTE FUNCTION public.st_record_sent_history();

-- =========================================================
-- Read-only web views: คิวส่ง / ประวัติ แยกตามค่าย
-- =========================================================
CREATE OR REPLACE VIEW public.vw_bb_telegram_web_queue AS
SELECT o.*,
  'BB_SEND'::text AS telegram_room,
  'QUEUE'::text AS queue_status
FROM public.bb_orders o
WHERE lower(COALESCE(o.telegram_sent, 'false')) NOT IN
  ('true','t','1','sent','delivered','sent_to_telegram','ไปแล้วไปลับ')
  AND upper(COALESCE(o.telegram_status, '')) NOT IN ('SENT','DELIVERED','SENT_TO_TELEGRAM')
  AND upper(COALESCE(o.delivery_state, '')) NOT IN ('SENT','DELIVERED');

CREATE OR REPLACE VIEW public.vw_bb_telegram_web_history AS
SELECT
  h.id AS history_id,
  h.order_key AS upsert_key,
  h.order_number,
  h.sent_at,
  h.recalled_at,
  h.recall_count,
  h.delivery_status,
  h.telegram_chat_id,
  h.telegram_message_id,
  h.telegram_message_text,
  h.telegram_room,
  h.queue_status,
  h.order_day_color_emoji,
  h.time_slot_label,
  h.ghost_column,
  h.status_color,
  h.routing_tag,
  h.snapshot
FROM public.bb_orders_sent_history h;

CREATE OR REPLACE VIEW public.vw_st_telegram_web_queue AS
SELECT o.*,
  'ST_SEND'::text AS telegram_room,
  'QUEUE'::text AS queue_status
FROM public.st_order_packer_records o
WHERE o.order_day_color_emoji = '🌿'
  AND COALESCE(o.ghost_column, '') <> '👻 เคยผ่านแล้วใว้วันหลังนะ'
  AND lower(COALESCE(o.telegram_sent, 'false')) NOT IN
    ('true','t','1','sent','delivered','sent_to_telegram','ไปแล้วไปลับ')
  AND upper(COALESCE(o.telegram_status, '')) NOT IN ('SENT','DELIVERED','SENT_TO_TELEGRAM')
  AND upper(COALESCE(o.delivery_state, '')) NOT IN ('SENT','DELIVERED');

CREATE OR REPLACE VIEW public.vw_st_telegram_web_history AS
SELECT
  h.id AS history_id,
  h.order_key AS upsert_key,
  h.order_number,
  h.sent_at,
  h.recalled_at,
  h.recall_count,
  h.delivery_status,
  h.telegram_chat_id,
  h.telegram_message_id,
  h.telegram_message_text,
  h.telegram_room,
  h.queue_status,
  h.order_day_color_emoji,
  h.time_slot_label,
  h.ghost_column,
  h.status_color,
  h.routing_tag,
  h.snapshot
FROM public.st_orders_sent_history h;

-- ตรวจชื่อห้องและจำนวนแถวที่หน้าเว็บอ่านได้
SELECT 'BB_SEND' AS room, COUNT(*) AS rows FROM public.vw_bb_telegram_web_queue
UNION ALL
SELECT 'BB_SENT_HISTORY', COUNT(*) FROM public.vw_bb_telegram_web_history
UNION ALL
SELECT 'ST_SEND', COUNT(*) FROM public.vw_st_telegram_web_queue
UNION ALL
SELECT 'ST_SENT_HISTORY', COUNT(*) FROM public.vw_st_telegram_web_history;
